"""Connection secret-rotation helpers (#1342 — grace window + audit).

Pure, store-free: the grace-duration parser used by the rotate CLI, the audit
event-name constants, and the ``connection_secret_events`` DDL mirrored by the
auth store's ``_init_db`` (alongside alembic 0012). Kept separate from the DSL
lexer's ``parse_duration`` so the auth store doesn't depend on the core parser.
"""

from __future__ import annotations

import re
from datetime import timedelta

# Audit event names (written to connection_secret_events.event).
SECRET_EVENT_ROTATED = "rotated"
SECRET_EVENT_REVOKED_PREVIOUS = "revoked_previous"
SECRET_EVENT_KEY_REWRAPPED = "encryption_key_rewrapped"
SECRET_EVENT_SIGNING_ENABLED = "sp_signing_enabled"
SECRET_EVENT_SIGNING_DISABLED = "sp_signing_disabled"

_GRACE_UNITS = {"m": "minutes", "h": "hours", "d": "days", "w": "weeks"}
# A single positive integer (no leading zero) + one unit suffix.
_GRACE_RE = re.compile(r"^([1-9][0-9]*)([mhdw])$")


def parse_grace_duration(text: str) -> timedelta:
    """``'24h'`` / ``'7d'`` / ``'30m'`` / ``'2w'`` -> timedelta.

    A single positive integer + one unit suffix (m/h/d/w). Raises ``ValueError``
    on anything else (empty, zero/negative, no unit, compound, fractional, 'y',
    leading-zero).
    """
    match = _GRACE_RE.match(text.strip())
    if match is None:
        raise ValueError(f"invalid grace duration {text!r} — use <positive int><m|h|d|w>, e.g. 24h")
    amount = int(match.group(1))
    try:
        return timedelta(**{_GRACE_UNITS[match.group(2)]: amount})
    except OverflowError as exc:
        # An astronomically large but well-formed duration overflows timedelta's C int —
        # honor the documented ValueError contract (callers only catch ValueError).
        raise ValueError(f"grace duration {text!r} is too large") from exc


CONNECTION_SECRET_EVENTS_DDL = """
CREATE TABLE IF NOT EXISTS connection_secret_events (
    seq           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id            TEXT PRIMARY KEY,
    connection_id TEXT NOT NULL,
    tenant_id     TEXT NOT NULL,
    event         TEXT NOT NULL,
    actor         TEXT,
    detail        TEXT NOT NULL DEFAULT '{}',
    at            TEXT NOT NULL
)
"""

CONNECTION_SECRET_EVENTS_INDEXES: tuple[str, ...] = (
    "CREATE INDEX IF NOT EXISTS ix_connection_secret_events_conn "
    "ON connection_secret_events(connection_id, seq)",
)
