"""Verify the Fragment alias names every primitive type. Adding a new
primitive without adding it here is what we want this test to catch."""

import typing

from dazzle.render.fragment import Fragment


def test_fragment_alias_includes_all_primitives() -> None:
    args = typing.get_args(Fragment)
    names = {t.__name__ for t in args}
    expected = {
        # layout
        "Stack",
        "Row",
        "Split",
        "Grid",
        # containers
        "Page",
        "AppShell",
        "Sidebar",
        "Topbar",
        "NavGroup",
        "NavItem",
        "SkipLink",
        "Surface",
        "Card",
        "Region",
        "Toolbar",
        "Drawer",
        "Modal",
        "Tabs",
        "ErrorPage",
        # content
        "Text",
        "Heading",
        "Icon",
        "Badge",
        "EmptyState",
        "Skeleton",
        # interactive
        "Button",
        "Link",
        "InlineEdit",
        "Interactive",
        # data
        "Table",
        "RelatedGroup",
        "DataListScroll",
        "ColumnVisibilityMenu",
        "ListFilterBar",
        "KanbanBoard",
        "CalendarGrid",
        "Timeline",
        "KPI",
        "BarChart",
        "PivotTable",
        "PivotTableRegion",
        "QueueRegion",
        "Diagram",
        "TimeSeries",
        "Radar",
        "BoxPlot",
        "Bullet",
        "PipelineSteps",
        "Sparkline",
        "Tree",
        "ActionCard",
        "ActionGrid",
        "ProfileCard",
        "MetricTile",
        "MetricsGrid",
        "DetailGrid",
        "GridRegion",
        "ListRegion",
        "Histogram",
        "Heatmap",
        "Funnel",
        "KanbanRegion",
        "ActivityFeed",
        "StatusList",
        "BarTrack",
        "StageBar",
        "LazyTabPanel",
        "SearchBox",
        "ConfirmGate",
        "CardPicker",
        "WorkspaceShell",
        "WorkspaceToolbar",
        "WorkspaceDrawer",
        "WorkspaceContextSelector",
        "Sequence",
        "Pagination",
        "CreateButton",
        "BulkActionToolbar",
        "CohortStripRegion",
        "DayTimelineRegion",
        "TaskInboxRegion",
        "EntityCardRegion",
        "DashboardGrid",
        "DashboardCard",
        "AddCardRow",
        "FilterBar",
        "SortHeader",
        "CsvExportButton",
        "DateRangePicker",
        # forms
        "FormStack",
        "FormSection",
        "Field",
        "Combobox",
        "RefPicker",
        "SearchSelect",
        "MoneyField",
        "WidgetCombobox",
        "TagsField",
        "DatePickerField",
        "ColorField",
        "SliderField",
        "RichTextField",
        "FileUpload",
        "Submit",
        # escape
        "RawHTML",
        "Slot",
        # assets (#1130)
        "Script",
        "Stylesheet",
    }
    assert names == expected, f"missing: {expected - names}; extra: {names - expected}"
