# GitHub Labels Configuration for DAZZLE
#
# Apply with: gh label import .github/labels.yml
# Or use the setup script: ./scripts/setup-github-labels.sh

# =============================================================================
# Issue Types
# =============================================================================
- name: bug
  color: d73a4a
  description: Something isn't working

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: question
  color: d876e3
  description: Further information is requested

# =============================================================================
# AI Co-Authorship
# =============================================================================
- name: needs-ai-assistance
  color: ff7b00
  description: Issue needs AI-assisted investigation

- name: ai-verified
  color: 6f42c1
  description: AI co-authorship verified

- name: copilot-assigned
  color: 8250df
  description: Assigned to GitHub Copilot coding agent

# =============================================================================
# Triage & Status
# =============================================================================
- name: needs-triage
  color: ededed
  description: Needs initial review and categorization

- name: confirmed
  color: 0052cc
  description: Bug confirmed or feature approved

- name: wontfix
  color: ffffff
  description: This will not be worked on

- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists

- name: help-wanted
  color: 008672
  description: Extra attention is needed

- name: good-first-issue
  color: 7057ff
  description: Good for newcomers

# =============================================================================
# Priority
# =============================================================================
- name: "priority:critical"
  color: b60205
  description: Critical priority - needs immediate attention

- name: "priority:high"
  color: d93f0b
  description: High priority

- name: "priority:medium"
  color: fbca04
  description: Medium priority

- name: "priority:low"
  color: 0e8a16
  description: Low priority

# =============================================================================
# Component Areas
# =============================================================================
- name: "area:core"
  color: 1d76db
  description: Core DSL parser and linker

- name: "area:stacks"
  color: 1d76db
  description: Backend/stack generators

- name: "area:cli"
  color: 1d76db
  description: Command-line interface

- name: "area:lsp"
  color: 1d76db
  description: Language Server Protocol

- name: "area:vscode"
  color: 1d76db
  description: VS Code extension

- name: "area:mcp"
  color: 1d76db
  description: Model Context Protocol

- name: "area:ci"
  color: 1d76db
  description: CI/CD and automation
