"""Framework structural-fitness: churn×complexity hotspot ranking + complexity baseline.

Points Dazzle's drift-ratchet instinct at ``src/dazzle``'s own Python structure — the one
ungated surface (every other gate targets the DSL/IR/generated-app surface). ``dazzle fitness
code`` writes the hotspot queue (report-only); the committed baseline feeds
``tests/unit/test_complexity_ratchet.py`` (the creep gate). See
docs/superpowers/specs/2026-06-19-framework-structural-fitness-design.md.
"""

from __future__ import annotations

import logging
import subprocess
from collections import Counter
from pathlib import Path
from typing import Any

from radon.complexity import cc_visit
from radon.metrics import mi_rank, mi_visit

logger = logging.getLogger(__name__)

_MI_RANK_ORDER = {"A": 3, "B": 2, "C": 1}


def _py_files(root: Path) -> list[Path]:
    return [p for p in root.rglob("*.py") if "__pycache__" not in p.parts]


def compute_complexity(root: Path) -> dict[str, dict[str, Any]]:
    """Per-file radon metrics: ``{rel_path: {mi, mi_rank, max_cc, functions: {fullname: cc}}}``.

    ``rel_path`` is relative to ``root.parent`` so keys read ``dazzle/...`` (stable across
    machines). Files radon can't parse are skipped (logged at debug, never swallowed silently).
    """
    result: dict[str, dict[str, Any]] = {}
    for p in _py_files(root):
        src = p.read_text(encoding="utf-8", errors="replace")
        try:
            mi = mi_visit(src, multi=True)
            funcs = {f.fullname: f.complexity for f in cc_visit(src)}
        except Exception as exc:  # radon chokes on some valid-but-unusual files; skip + log
            logger.debug("radon skipped %s: %s", p, exc)
            continue
        rel = str(p.relative_to(root.parent))
        result[rel] = {
            "mi": round(mi, 2),
            "mi_rank": mi_rank(mi),
            "max_cc": max(funcs.values(), default=0),
            "functions": funcs,
        }
    return result


def change_frequency(root: Path, since_days: int = 180) -> dict[str, int]:
    """Per-file commit count over the window, keyed to match ``compute_complexity`` keys.

    ``git log --name-only`` emits **repo-root-relative** paths (``src/dazzle/...``) regardless
    of cwd, while ``compute_complexity`` keys are relative to ``root.parent`` (``dazzle/...``).
    Run from the repo root, match the ``src/dazzle/`` prefix, and drop the leading
    ``<root.parent-relative-to-repo>/`` so the two keysets join.
    """
    repo_root = root.parent.parent
    git_prefix = str(root.relative_to(repo_root)) + "/"  # e.g. "src/dazzle/"
    drop = str(root.parent.relative_to(repo_root)) + "/"  # e.g. "src/"
    out = subprocess.run(
        ["git", "log", f"--since={since_days} days ago", "--name-only", "--pretty=format:"],
        cwd=repo_root,
        capture_output=True,
        text=True,
        check=False,
    ).stdout
    counts: Counter[str] = Counter()
    for raw in out.splitlines():
        line = raw.strip()
        if line.startswith(git_prefix) and line.endswith(".py"):
            counts[line[len(drop) :]] += 1  # "src/dazzle/x" → "dazzle/x"
    return dict(counts)


def rank_hotspots(
    complexity: dict[str, dict[str, Any]], churn: dict[str, int]
) -> list[tuple[str, float, int, str]]:
    """Rank files by ``churn × (100 - MI)`` desc → ``(path, score, churn, mi_rank)``.

    Weights how often a low-maintainability file changes — the actionable structural-debt
    ordering (a complex file nobody touches is lower priority than one churned every week).
    """
    rows: list[tuple[str, float, int, str]] = []
    for path, cx in complexity.items():
        c = churn.get(path, 0)
        score = round(c * (100.0 - cx["mi"]), 1)
        rows.append((path, score, c, cx.get("mi_rank", "?")))
    return sorted(rows, key=lambda r: r[1], reverse=True)


def render_hotspots_md(ranked: list[tuple[str, float, int, str]], top: int = 30) -> str:
    lines = [
        "# Framework structural hotspots (churn × complexity)",
        "",
        "Generated by `dazzle fitness code --write`. The ordered structural-debt queue:",
        "high-churn × low-maintainability files. Report-only — refactor the top by hand; the",
        "complexity ratchet (`tests/unit/test_complexity_ratchet.py`) protects the gains.",
        "",
        "| Rank | File | Score | Churn (180d) | MI rank |",
        "|------|------|-------|--------------|---------|",
    ]
    for i, (path, score, churn, rank) in enumerate(ranked[:top], 1):
        lines.append(f"| {i} | `{path}` | {score} | {churn} | {rank} |")
    return "\n".join(lines) + "\n"


def build_complexity_baseline(root: Path) -> dict[str, dict[str, Any]]:
    """The committed ratchet snapshot: per-file ``mi_rank`` + ``functions`` (CC), key-sorted."""
    cx = compute_complexity(root)
    return {k: {"mi_rank": cx[k]["mi_rank"], "functions": cx[k]["functions"]} for k in sorted(cx)}


def compare_complexity(
    baseline: dict[str, Any], current: dict[str, Any], cc_ceiling: int = 15
) -> list[str]:
    """Ratchet check: return violation strings (empty = clean). A touched file may not drop
    MI rank; a new file may not be C; a new/changed function may not exceed the CC ceiling."""
    violations: list[str] = []
    for path, cur in current.items():
        base = baseline.get(path)
        if base is None:
            if cur["mi_rank"] == "C":
                violations.append(f"{path}: new file at MI rank C — split it before landing.")
            base_funcs: dict[str, int] = {}
        else:
            if _MI_RANK_ORDER[cur["mi_rank"]] < _MI_RANK_ORDER[base["mi_rank"]]:
                violations.append(
                    f"{path}: MI rank dropped {base['mi_rank']}→{cur['mi_rank']} — refactor, "
                    f"or regenerate the baseline with `dazzle fitness code --write-baseline`."
                )
            base_funcs = base.get("functions", {})
        for fn, cc in cur["functions"].items():
            if cc > cc_ceiling and base_funcs.get(fn, 0) <= cc_ceiling:
                violations.append(f"{path}:{fn}: cyclomatic complexity {cc} > {cc_ceiling} (new).")
    return violations
