export default [
  {
    files: ["src/dazzle_ui/**/js/*.js"],
    ignores: ["**/vendor/**"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        // Browser
        window: "readonly",
        document: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        requestAnimationFrame: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        FormData: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        HTMLElement: "readonly",
        Node: "readonly",
        NodeList: "readonly",
        Element: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        crypto: "readonly",
        NodeFilter: "readonly",
        DOMParser: "readonly",
        AbortController: "readonly",
        // Frameworks loaded via script tags
        Alpine: "readonly",
        htmx: "readonly",
        lucide: "readonly",
        Sortable: "readonly",
        Quill: "readonly",
        flatpickr: "readonly",
        TomSelect: "readonly",
        Pickr: "readonly",
      },
    },
    rules: {
      // Structural errors only — no style opinions
      "no-undef": "error",
      "no-unreachable": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty-pattern": "error",
      "no-func-assign": "error",
      "no-import-assign": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-loss-of-precision": "error",
      "no-unexpected-multiline": "error",
      "constructor-super": "error",
      "valid-typeof": "error",
    },
  },
];
