"""
Authentication pages generator for Next.js Onebox.

Generates:
- src/app/login/page.tsx
- src/app/register/page.tsx
- src/app/logout/route.ts
- src/actions/auth.ts
"""

from ...base.generator import Generator, GeneratorResult


class AuthGenerator(Generator):
    """Generates authentication pages and actions."""

    def generate(self) -> GeneratorResult:
        """Generate auth files."""
        result = GeneratorResult()

        self._generate_auth_actions(result)
        self._generate_login_page(result)
        self._generate_register_page(result)
        self._generate_logout_route(result)

        return result

    def _generate_auth_actions(self, result: GeneratorResult) -> None:
        """Generate auth server actions."""
        content = """// Auth Server Actions
// Generated by DAZZLE Next.js Onebox Stack

"use server";

import { redirect } from "next/navigation";
import { signIn, signUp, signOut } from "@/lib/auth";
import type { ActionResponse } from "@/types/api";

export interface AuthFormState {
  success: boolean;
  error?: string;
  errors?: Record<string, string[]>;
}

/**
 * Login action.
 */
export async function loginAction(
  _prevState: AuthFormState,
  formData: FormData
): Promise<AuthFormState> {
  const email = formData.get("email") as string;
  const password = formData.get("password") as string;

  // Validate input
  const errors: Record<string, string[]> = {};
  if (!email) {
    errors.email = ["Email is required"];
  }
  if (!password) {
    errors.password = ["Password is required"];
  }
  if (Object.keys(errors).length > 0) {
    return { success: false, errors };
  }

  try {
    await signIn(email, password);
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : "Login failed",
    };
  }

  redirect("/");
}

/**
 * Register action.
 */
export async function registerAction(
  _prevState: AuthFormState,
  formData: FormData
): Promise<AuthFormState> {
  const email = formData.get("email") as string;
  const password = formData.get("password") as string;
  const confirmPassword = formData.get("confirmPassword") as string;
  const name = formData.get("name") as string | undefined;

  // Validate input
  const errors: Record<string, string[]> = {};
  if (!email) {
    errors.email = ["Email is required"];
  } else if (!/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email)) {
    errors.email = ["Invalid email address"];
  }
  if (!password) {
    errors.password = ["Password is required"];
  } else if (password.length < 8) {
    errors.password = ["Password must be at least 8 characters"];
  }
  if (password !== confirmPassword) {
    errors.confirmPassword = ["Passwords do not match"];
  }
  if (Object.keys(errors).length > 0) {
    return { success: false, errors };
  }

  try {
    await signUp(email, password, name || undefined);
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : "Registration failed",
    };
  }

  redirect("/");
}

/**
 * Logout action.
 */
export async function logoutAction(): Promise<void> {
  await signOut();
  redirect("/login");
}
"""
        path = self.output_dir / "src" / "actions" / "auth.ts"
        self._write_file(path, content)
        result.add_file(path)

    def _generate_login_page(self, result: GeneratorResult) -> None:
        """Generate login page."""
        content = """"use client";

// Login Page
// Generated by DAZZLE Next.js Onebox Stack

import { useFormState, useFormStatus } from "react-dom";
import Link from "next/link";
import { loginAction, type AuthFormState } from "@/actions/auth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card";
import { FormField } from "@/components/form-field";

const initialState: AuthFormState = {
  success: false,
};

function SubmitButton() {
  const { pending } = useFormStatus();
  return (
    <Button
      type="submit"
      className="w-full"
      disabled={pending}
    >
      {pending ? "Signing in..." : "Sign In"}
    </Button>
  );
}

export default function LoginPage() {
  const [state, formAction] = useFormState(loginAction, initialState);

  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-50 px-4">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center">
          <CardTitle className="text-2xl">Sign In</CardTitle>
        </CardHeader>
        <CardContent>
          <form action={formAction} className="space-y-4">
            {state.error && (
              <div className="rounded-md bg-red-50 p-3 text-sm text-red-600">
                {state.error}
              </div>
            )}

            <FormField
              label="Email"
              htmlFor="email"
              required
              error={state.errors?.email?.[0]}
            >
              <Input
                id="email"
                name="email"
                type="email"
                autoComplete="email"
                placeholder="you@example.com"
                error={!!state.errors?.email}
              />
            </FormField>

            <FormField
              label="Password"
              htmlFor="password"
              required
              error={state.errors?.password?.[0]}
            >
              <Input
                id="password"
                name="password"
                type="password"
                autoComplete="current-password"
                placeholder="••••••••"
                error={!!state.errors?.password}
              />
            </FormField>

            <SubmitButton />
          </form>
        </CardContent>
        <CardFooter className="justify-center">
          <p className="text-sm text-gray-500">
            Don&apos;t have an account?{" "}
            <Link href="/register" className="text-blue-600 hover:underline">
              Sign up
            </Link>
          </p>
        </CardFooter>
      </Card>
    </div>
  );
}
"""
        path = self.output_dir / "src" / "app" / "login" / "page.tsx"
        self._write_file(path, content)
        result.add_file(path)

    def _generate_register_page(self, result: GeneratorResult) -> None:
        """Generate register page."""
        content = """"use client";

// Register Page
// Generated by DAZZLE Next.js Onebox Stack

import { useFormState, useFormStatus } from "react-dom";
import Link from "next/link";
import { registerAction, type AuthFormState } from "@/actions/auth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card";
import { FormField } from "@/components/form-field";

const initialState: AuthFormState = {
  success: false,
};

function SubmitButton() {
  const { pending } = useFormStatus();
  return (
    <Button
      type="submit"
      className="w-full"
      disabled={pending}
    >
      {pending ? "Creating account..." : "Create Account"}
    </Button>
  );
}

export default function RegisterPage() {
  const [state, formAction] = useFormState(registerAction, initialState);

  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-50 px-4">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center">
          <CardTitle className="text-2xl">Create Account</CardTitle>
        </CardHeader>
        <CardContent>
          <form action={formAction} className="space-y-4">
            {state.error && (
              <div className="rounded-md bg-red-50 p-3 text-sm text-red-600">
                {state.error}
              </div>
            )}

            <FormField
              label="Name"
              htmlFor="name"
              error={state.errors?.name?.[0]}
            >
              <Input
                id="name"
                name="name"
                type="text"
                autoComplete="name"
                placeholder="John Doe"
                error={!!state.errors?.name}
              />
            </FormField>

            <FormField
              label="Email"
              htmlFor="email"
              required
              error={state.errors?.email?.[0]}
            >
              <Input
                id="email"
                name="email"
                type="email"
                autoComplete="email"
                placeholder="you@example.com"
                error={!!state.errors?.email}
              />
            </FormField>

            <FormField
              label="Password"
              htmlFor="password"
              required
              error={state.errors?.password?.[0]}
              description="At least 8 characters"
            >
              <Input
                id="password"
                name="password"
                type="password"
                autoComplete="new-password"
                placeholder="••••••••"
                error={!!state.errors?.password}
              />
            </FormField>

            <FormField
              label="Confirm Password"
              htmlFor="confirmPassword"
              required
              error={state.errors?.confirmPassword?.[0]}
            >
              <Input
                id="confirmPassword"
                name="confirmPassword"
                type="password"
                autoComplete="new-password"
                placeholder="••••••••"
                error={!!state.errors?.confirmPassword}
              />
            </FormField>

            <SubmitButton />
          </form>
        </CardContent>
        <CardFooter className="justify-center">
          <p className="text-sm text-gray-500">
            Already have an account?{" "}
            <Link href="/login" className="text-blue-600 hover:underline">
              Sign in
            </Link>
          </p>
        </CardFooter>
      </Card>
    </div>
  );
}
"""
        path = self.output_dir / "src" / "app" / "register" / "page.tsx"
        self._write_file(path, content)
        result.add_file(path)

    def _generate_logout_route(self, result: GeneratorResult) -> None:
        """Generate logout route handler."""
        content = """// Logout Route
// Generated by DAZZLE Next.js Onebox Stack

import { redirect } from "next/navigation";
import { signOut } from "@/lib/auth";

export async function GET() {
  await signOut();
  redirect("/login");
}

export async function POST() {
  await signOut();
  redirect("/login");
}
"""
        path = self.output_dir / "src" / "app" / "logout" / "route.ts"
        self._write_file(path, content)
        result.add_file(path)
