"""
Components generator for Next.js Onebox.

Generates src/components/ with:
- ui/ (base UI components)
- data-table.tsx (Mantine DataTable wrapper)
- form-field.tsx (form field component)
- attention-badge.tsx (attention signal display)
- persona-switcher.tsx (persona selector)
"""

from pathlib import Path

from ....core import ir
from ...base.generator import Generator, GeneratorResult


class ComponentsGenerator(Generator):
    """Generates React components."""

    def generate(self) -> GeneratorResult:
        """Generate component files."""
        result = GeneratorResult()

        # Base UI components
        self._generate_button(result)
        self._generate_input(result)
        self._generate_card(result)
        self._generate_badge(result)

        # Feature components
        self._generate_data_table(result)
        self._generate_form_field(result)
        self._generate_attention_badge(result)
        self._generate_persona_switcher(result)
        self._generate_empty_state(result)
        self._generate_loading(result)

        # Component index
        self._generate_index(result)

        return result

    def _generate_button(self, result: GeneratorResult) -> None:
        """Generate Button component."""
        content = '''// Button Component
// Generated by DAZZLE Next.js Onebox Stack

import { forwardRef, type ButtonHTMLAttributes } from "react";
import { Slot } from "@radix-ui/react-slot";
import { cn } from "@/lib/utils";

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "primary" | "secondary" | "danger" | "ghost";
  size?: "sm" | "md" | "lg";
  asChild?: boolean;
}

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant = "primary", size = "md", asChild = false, children, ...props }, ref) => {
    const Comp = asChild ? Slot : "button";
    return (
      <Comp
        ref={ref}
        className={cn(
          "inline-flex items-center justify-center rounded-md font-medium transition-colors",
          "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2",
          "disabled:pointer-events-none disabled:opacity-50",
          {
            // Variants
            "bg-blue-600 text-white hover:bg-blue-700 focus-visible:ring-blue-500":
              variant === "primary",
            "bg-gray-100 text-gray-900 hover:bg-gray-200 focus-visible:ring-gray-500":
              variant === "secondary",
            "bg-red-600 text-white hover:bg-red-700 focus-visible:ring-red-500":
              variant === "danger",
            "hover:bg-gray-100 text-gray-700 focus-visible:ring-gray-500":
              variant === "ghost",
            // Sizes
            "h-8 px-3 text-sm": size === "sm",
            "h-10 px-4 text-sm": size === "md",
            "h-12 px-6 text-base": size === "lg",
          },
          className
        )}
        {...props}
      >
        {children}
      </Comp>
    );
  }
);

Button.displayName = "Button";
'''
        path = self.output_dir / "src" / "components" / "ui" / "button.tsx"
        self._write_file(path, content)
        result.add_file(path)

    def _generate_input(self, result: GeneratorResult) -> None:
        """Generate Input component."""
        content = '''// Input Component
// Generated by DAZZLE Next.js Onebox Stack

import { forwardRef, type InputHTMLAttributes } from "react";
import { cn } from "@/lib/utils";

export interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
  error?: boolean;
}

export const Input = forwardRef<HTMLInputElement, InputProps>(
  ({ className, error, type, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(
          "flex h-10 w-full rounded-md border bg-white px-3 py-2 text-sm",
          "placeholder:text-gray-400",
          "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-blue-500",
          "disabled:cursor-not-allowed disabled:opacity-50",
          error
            ? "border-red-500 focus-visible:ring-red-500"
            : "border-gray-300",
          className
        )}
        ref={ref}
        {...props}
      />
    );
  }
);

Input.displayName = "Input";

export interface TextareaProps
  extends React.TextareaHTMLAttributes<HTMLTextAreaElement> {
  error?: boolean;
}

export const Textarea = forwardRef<HTMLTextAreaElement, TextareaProps>(
  ({ className, error, ...props }, ref) => {
    return (
      <textarea
        className={cn(
          "flex min-h-[80px] w-full rounded-md border bg-white px-3 py-2 text-sm",
          "placeholder:text-gray-400",
          "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-blue-500",
          "disabled:cursor-not-allowed disabled:opacity-50",
          error
            ? "border-red-500 focus-visible:ring-red-500"
            : "border-gray-300",
          className
        )}
        ref={ref}
        {...props}
      />
    );
  }
);

Textarea.displayName = "Textarea";

export interface SelectProps
  extends React.SelectHTMLAttributes<HTMLSelectElement> {
  error?: boolean;
}

export const Select = forwardRef<HTMLSelectElement, SelectProps>(
  ({ className, error, children, ...props }, ref) => {
    return (
      <select
        className={cn(
          "flex h-10 w-full rounded-md border bg-white px-3 py-2 text-sm",
          "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-blue-500",
          "disabled:cursor-not-allowed disabled:opacity-50",
          error
            ? "border-red-500 focus-visible:ring-red-500"
            : "border-gray-300",
          className
        )}
        ref={ref}
        {...props}
      >
        {children}
      </select>
    );
  }
);

Select.displayName = "Select";
'''
        path = self.output_dir / "src" / "components" / "ui" / "input.tsx"
        self._write_file(path, content)
        result.add_file(path)

    def _generate_card(self, result: GeneratorResult) -> None:
        """Generate Card component."""
        content = '''// Card Component
// Generated by DAZZLE Next.js Onebox Stack

import { type HTMLAttributes, forwardRef } from "react";
import { cn } from "@/lib/utils";

export const Card = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={cn(
        "rounded-lg border border-gray-200 bg-white shadow-sm",
        className
      )}
      {...props}
    />
  )
);
Card.displayName = "Card";

export const CardHeader = forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn("flex flex-col space-y-1.5 p-6", className)}
    {...props}
  />
));
CardHeader.displayName = "CardHeader";

export const CardTitle = forwardRef<
  HTMLParagraphElement,
  HTMLAttributes<HTMLHeadingElement>
>(({ className, ...props }, ref) => (
  <h3
    ref={ref}
    className={cn(
      "text-lg font-semibold leading-none tracking-tight",
      className
    )}
    {...props}
  />
));
CardTitle.displayName = "CardTitle";

export const CardDescription = forwardRef<
  HTMLParagraphElement,
  HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => (
  <p
    ref={ref}
    className={cn("text-sm text-gray-500", className)}
    {...props}
  />
));
CardDescription.displayName = "CardDescription";

export const CardContent = forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("p-6 pt-0", className)} {...props} />
));
CardContent.displayName = "CardContent";

export const CardFooter = forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn("flex items-center p-6 pt-0", className)}
    {...props}
  />
));
CardFooter.displayName = "CardFooter";
'''
        path = self.output_dir / "src" / "components" / "ui" / "card.tsx"
        self._write_file(path, content)
        result.add_file(path)

    def _generate_badge(self, result: GeneratorResult) -> None:
        """Generate Badge component."""
        content = '''// Badge Component
// Generated by DAZZLE Next.js Onebox Stack

import { type HTMLAttributes } from "react";
import { cn } from "@/lib/utils";

export interface BadgeProps extends HTMLAttributes<HTMLDivElement> {
  variant?: "default" | "secondary" | "success" | "warning" | "danger";
}

export function Badge({
  className,
  variant = "default",
  ...props
}: BadgeProps) {
  return (
    <div
      className={cn(
        "inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-semibold",
        {
          "bg-blue-100 text-blue-800": variant === "default",
          "bg-gray-100 text-gray-800": variant === "secondary",
          "bg-green-100 text-green-800": variant === "success",
          "bg-amber-100 text-amber-800": variant === "warning",
          "bg-red-100 text-red-800": variant === "danger",
        },
        className
      )}
      {...props}
    />
  );
}
'''
        path = self.output_dir / "src" / "components" / "ui" / "badge.tsx"
        self._write_file(path, content)
        result.add_file(path)

    def _generate_data_table(self, result: GeneratorResult) -> None:
        """Generate DataTable component."""
        content = '''"use client";

// DataTable Component
// Generated by DAZZLE Next.js Onebox Stack

import { DataTable as MantineDataTable, type DataTableColumn, type DataTableSortStatus } from "mantine-datatable";
import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import "mantine-datatable/styles.css";

export interface DataTableProps<T extends Record<string, unknown>> {
  records: T[];
  columns: DataTableColumn<T>[];
  totalRecords?: number;
  recordsPerPage?: number;
  page?: number;
  onPageChange?: (page: number) => void;
  loading?: boolean;
  onRowClick?: (record: T) => void;
  emptyState?: React.ReactNode;
  sortStatus?: DataTableSortStatus<T>;
  onSortStatusChange?: (status: DataTableSortStatus<T>) => void;
}

export function DataTable<T extends Record<string, unknown>>({
  records,
  columns,
  totalRecords,
  recordsPerPage = 10,
  page = 1,
  onPageChange,
  loading,
  onRowClick,
  emptyState,
  sortStatus,
  onSortStatusChange,
}: DataTableProps<T>) {
  const tableProps: any = {
    withTableBorder: true,
    borderRadius: "md" as const,
    striped: true,
    highlightOnHover: true,
    records,
    columns,
    minHeight: 200,
  };

  if (loading !== undefined) tableProps.fetching = loading;
  if (onRowClick) tableProps.onRowClick = ({ record }: any) => onRowClick(record);
  if (emptyState) tableProps.emptyState = emptyState;
  if (sortStatus) tableProps.sortStatus = sortStatus;
  if (onSortStatusChange) tableProps.onSortStatusChange = onSortStatusChange;

  if (totalRecords !== undefined && onPageChange) {
    tableProps.totalRecords = totalRecords;
    tableProps.recordsPerPage = recordsPerPage;
    tableProps.page = page;
    tableProps.onPageChange = onPageChange;
  }

  return (
    <MantineProvider>
      <MantineDataTable {...tableProps} />
    </MantineProvider>
  );
}

export type { DataTableColumn, DataTableSortStatus };
'''
        path = self.output_dir / "src" / "components" / "data-table.tsx"
        self._write_file(path, content)
        result.add_file(path)

    def _generate_form_field(self, result: GeneratorResult) -> None:
        """Generate FormField component."""
        content = '''// FormField Component
// Generated by DAZZLE Next.js Onebox Stack

import { type ReactNode } from "react";
import { cn } from "@/lib/utils";

export interface FormFieldProps {
  label: string;
  htmlFor?: string;
  error?: string;
  required?: boolean;
  description?: string;
  children: ReactNode;
  className?: string;
}

export function FormField({
  label,
  htmlFor,
  error,
  required,
  description,
  children,
  className,
}: FormFieldProps) {
  return (
    <div className={cn("space-y-2", className)}>
      <label
        htmlFor={htmlFor}
        className="block text-sm font-medium text-gray-700"
      >
        {label}
        {required && <span className="text-red-500 ml-1">*</span>}
      </label>
      {children}
      {description && !error && (
        <p className="text-xs text-gray-500">{description}</p>
      )}
      {error && <p className="text-xs text-red-600">{error}</p>}
    </div>
  );
}
'''
        path = self.output_dir / "src" / "components" / "form-field.tsx"
        self._write_file(path, content)
        result.add_file(path)

    def _generate_attention_badge(self, result: GeneratorResult) -> None:
        """Generate AttentionBadge component."""
        content = '''// AttentionBadge Component
// Generated by DAZZLE Next.js Onebox Stack

import { AlertCircle, AlertTriangle, Info, Bell } from "lucide-react";
import { cn } from "@/lib/utils";
import type { AttentionLevel } from "@/types/ux";
import { attentionStyles } from "@/lib/attention";

export interface AttentionBadgeProps {
  level: AttentionLevel;
  message?: string;
  className?: string;
}

const icons = {
  critical: AlertCircle,
  warning: AlertTriangle,
  notice: Bell,
  info: Info,
};

export function AttentionBadge({
  level,
  message,
  className,
}: AttentionBadgeProps) {
  const Icon = icons[level];
  const styles = attentionStyles[level];

  return (
    <div
      className={cn(
        "inline-flex items-center gap-1.5 rounded-full px-2 py-0.5 text-xs font-medium",
        styles.bg,
        styles.text,
        className
      )}
    >
      <Icon className={cn("h-3 w-3", styles.icon)} />
      {message && <span>{message}</span>}
    </div>
  );
}

export interface AttentionBannerProps {
  level: AttentionLevel;
  message: string;
  className?: string;
}

export function AttentionBanner({
  level,
  message,
  className,
}: AttentionBannerProps) {
  const Icon = icons[level];
  const styles = attentionStyles[level];

  return (
    <div
      className={cn(
        "flex items-start gap-3 rounded-md border-l-4 p-4",
        styles.bg,
        styles.border,
        className
      )}
    >
      <Icon className={cn("h-5 w-5 flex-shrink-0 mt-0.5", styles.icon)} />
      <p className={cn("text-sm", styles.text)}>{message}</p>
    </div>
  );
}
'''
        path = self.output_dir / "src" / "components" / "attention-badge.tsx"
        self._write_file(path, content)
        result.add_file(path)

    def _generate_persona_switcher(self, result: GeneratorResult) -> None:
        """Generate PersonaSwitcher component."""
        content = '''"use client";

// PersonaSwitcher Component
// Generated by DAZZLE Next.js Onebox Stack

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { User, ChevronDown, Check } from "lucide-react";
import { cn } from "@/lib/utils";
import type { Persona } from "@/types/ux";

export interface PersonaSwitcherProps {
  currentPersona: Persona | null;
  personas: Persona[];
  onSwitch?: (personaId: string) => Promise<void>;
}

export function PersonaSwitcher({
  currentPersona,
  personas,
  onSwitch,
}: PersonaSwitcherProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [isPending, startTransition] = useTransition();
  const router = useRouter();

  const handleSelect = async (personaId: string) => {
    if (onSwitch) {
      startTransition(async () => {
        await onSwitch(personaId);
        router.refresh();
      });
    }
    setIsOpen(false);
  };

  if (personas.length === 0) {
    return null;
  }

  return (
    <div className="relative">
      <button
        type="button"
        onClick={() => setIsOpen(!isOpen)}
        className={cn(
          "flex items-center gap-2 rounded-md border border-gray-300 bg-white px-3 py-2 text-sm",
          "hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-blue-500",
          isPending && "opacity-50 cursor-wait"
        )}
        disabled={isPending}
      >
        <User className="h-4 w-4 text-gray-500" />
        <span>{currentPersona?.name || "Select Persona"}</span>
        <ChevronDown className="h-4 w-4 text-gray-400" />
      </button>

      {isOpen && (
        <>
          <div
            className="fixed inset-0 z-10"
            onClick={() => setIsOpen(false)}
          />
          <div className="absolute right-0 z-20 mt-1 w-56 rounded-md border border-gray-200 bg-white shadow-lg">
            <div className="py-1">
              {personas.map((persona) => (
                <button
                  key={persona.id}
                  type="button"
                  onClick={() => handleSelect(persona.id)}
                  className={cn(
                    "flex w-full items-center gap-2 px-4 py-2 text-left text-sm",
                    "hover:bg-gray-100",
                    currentPersona?.id === persona.id && "bg-gray-50"
                  )}
                >
                  <Check
                    className={cn(
                      "h-4 w-4",
                      currentPersona?.id === persona.id
                        ? "text-blue-600"
                        : "text-transparent"
                    )}
                  />
                  <div>
                    <div className="font-medium">{persona.name}</div>
                    {persona.description && (
                      <div className="text-xs text-gray-500">
                        {persona.description}
                      </div>
                    )}
                  </div>
                </button>
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  );
}
'''
        path = self.output_dir / "src" / "components" / "persona-switcher.tsx"
        self._write_file(path, content)
        result.add_file(path)

    def _generate_empty_state(self, result: GeneratorResult) -> None:
        """Generate EmptyState component."""
        content = '''// EmptyState Component
// Generated by DAZZLE Next.js Onebox Stack

import Link from "next/link";
import { Inbox } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "./ui/button";

export interface EmptyStateProps {
  title?: string;
  message: string;
  icon?: React.ReactNode;
  action?: {
    label: string;
    href?: string;
    onClick?: () => void;
  };
  className?: string;
}

export function EmptyState({
  title,
  message,
  icon,
  action,
  className,
}: EmptyStateProps) {
  return (
    <div
      className={cn(
        "flex flex-col items-center justify-center py-12 px-4 text-center",
        className
      )}
    >
      <div className="mb-4 rounded-full bg-gray-100 p-4">
        {icon || <Inbox className="h-8 w-8 text-gray-400" />}
      </div>
      {title && (
        <h3 className="mb-1 text-lg font-semibold text-gray-900">{title}</h3>
      )}
      <p className="mb-4 text-sm text-gray-500 max-w-sm">{message}</p>
      {action && (
        action.href ? (
          <Button variant="primary" asChild>
            <Link href={action.href}>
              {action.label}
            </Link>
          </Button>
        ) : (
          <Button
            variant="primary"
            onClick={action.onClick}
          >
            {action.label}
          </Button>
        )
      )}
    </div>
  );
}
'''
        path = self.output_dir / "src" / "components" / "empty-state.tsx"
        self._write_file(path, content)
        result.add_file(path)

    def _generate_loading(self, result: GeneratorResult) -> None:
        """Generate Loading component."""
        content = '''// Loading Component
// Generated by DAZZLE Next.js Onebox Stack

import { Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";

export interface LoadingProps {
  size?: "sm" | "md" | "lg";
  className?: string;
}

export function Loading({ size = "md", className }: LoadingProps) {
  const sizeClasses = {
    sm: "h-4 w-4",
    md: "h-8 w-8",
    lg: "h-12 w-12",
  };

  return (
    <div className={cn("flex items-center justify-center", className)}>
      <Loader2 className={cn("animate-spin text-blue-600", sizeClasses[size])} />
    </div>
  );
}

export function LoadingPage() {
  return (
    <div className="flex min-h-[400px] items-center justify-center">
      <Loading size="lg" />
    </div>
  );
}

export function LoadingOverlay() {
  return (
    <div className="absolute inset-0 flex items-center justify-center bg-white/80">
      <Loading size="lg" />
    </div>
  );
}
'''
        path = self.output_dir / "src" / "components" / "loading.tsx"
        self._write_file(path, content)
        result.add_file(path)

    def _generate_index(self, result: GeneratorResult) -> None:
        """Generate components index."""
        content = '''// Components Index
// Generated by DAZZLE Next.js Onebox Stack

// UI Components
export { Button, type ButtonProps } from "./ui/button";
export { Input, Textarea, Select, type InputProps, type TextareaProps, type SelectProps } from "./ui/input";
export { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "./ui/card";
export { Badge, type BadgeProps } from "./ui/badge";

// Feature Components
export { DataTable, type DataTableProps, type DataTableColumn } from "./data-table";
export { FormField, type FormFieldProps } from "./form-field";
export { AttentionBadge, AttentionBanner, type AttentionBadgeProps, type AttentionBannerProps } from "./attention-badge";
export { PersonaSwitcher, type PersonaSwitcherProps } from "./persona-switcher";
export { EmptyState, type EmptyStateProps } from "./empty-state";
export { Loading, LoadingPage, LoadingOverlay, type LoadingProps } from "./loading";
'''
        path = self.output_dir / "src" / "components" / "index.tsx"
        self._write_file(path, content)
        result.add_file(path)
