"""
CSS loader for Dazzle UI runtime.

Loads and concatenates CSS files from static/ to produce the bundled
stylesheet served at /styles/dazzle.css.

Uses CSS Cascade Layers (@layer) for explicit ordering. The layer
order and file list mirror the canonical entry stylesheet
``static/css/dazzle.css`` — that file's @import order is the source
of truth; this loader concatenates the same files in the same order
so the runtime bundle and the dev-time direct-import path resolve
identically.

Generates an inline source map for DevTools debugging.
"""

import base64
import json
from pathlib import Path

_STATIC_DIR = Path(__file__).parent / "static"

# Cascade layer order — must match `static/css/dazzle.css`. Anything
# in a later layer wins over earlier layers regardless of selector
# specificity. `overrides` is reserved for project-level escape-hatch
# rules; the loader never emits into it.
CSS_LAYER_ORDER = "@layer reset, vendor, tokens, base, utilities, components, overrides;"

# Layered source files in cascade order. Each entry is
# ``(layer_name, path_relative_to_static)``. Order WITHIN a layer
# also matters for ties resolved by source position; keep this list
# byte-for-byte aligned with the @import order in
# ``static/css/dazzle.css`` (#920).
CSS_SOURCE_FILES: tuple[tuple[str, str], ...] = (
    ("reset", "css/reset.css"),
    ("vendor", "vendor/tom-select.css"),
    ("vendor", "vendor/flatpickr.css"),
    ("vendor", "vendor/quill.snow.css"),
    # vendor/pickr.css removed in #976 — `widget=color` uses native
    # <input type="color">, no vendor CSS required.
    ("tokens", "css/tokens.css"),
    ("tokens", "css/design-system.css"),
    ("base", "css/base.css"),
    ("utilities", "css/utilities.css"),
    ("components", "css/components/badge.css"),
    ("components", "css/components/button.css"),
    ("components", "css/components/dashboard.css"),
    ("components", "css/components/detail.css"),
    ("components", "css/components/form.css"),
    ("components", "css/components/fragments.css"),
    ("components", "css/components/htmx-states.css"),
    ("components", "css/components/pdf-viewer.css"),
    ("components", "css/components/regions.css"),
    ("components", "css/components/table.css"),
    ("components", "css/dazzle-layer.css"),
    ("components", "css/site-sections.css"),
)

# Files loaded unlayered (after every @layer block) so they can
# override earlier rules regardless of layer position. Layered styles
# always lose to unlayered styles in the CSS cascade.
CSS_UNLAYERED_FILES: tuple[str, ...] = (
    "css/dz.css",
    "css/dz-widgets.css",
    "css/dz-tones.css",
)


def _load_css_file(rel_path: str) -> str:
    """Load a CSS file from the static/ directory by relative path."""
    path = _STATIC_DIR / rel_path
    if not path.exists():
        raise FileNotFoundError(f"CSS file not found: {path}")
    return path.read_text(encoding="utf-8")


def get_bundled_css(theme_css: str | None = None) -> str:
    """
    Concatenate all framework CSS into one bundle, layered to match
    ``static/css/dazzle.css``.

    Args:
        theme_css: Optional generated theme CSS to prepend (from ThemeSpec).
            Inlined into the ``tokens`` layer so generated custom-property
            values participate in the same cascade as the static tokens.

    Returns:
        Concatenated CSS with @layer wrappers and an inline source map.
    """
    parts: list[str] = [
        CSS_LAYER_ORDER,
        "",
        "/* =============================================================================",
        "   DAZZLE Framework CSS Bundle",
        "   Auto-generated by css_loader.py — mirrors static/css/dazzle.css",
        "   ============================================================================= */",
        "",
    ]

    # Generated theme CSS lands in the tokens layer alongside the
    # static custom-property declarations.
    if theme_css:
        parts.append("/* --- theme.css (generated) --- */")
        parts.append(f"@layer tokens {{\n{theme_css}\n}}")
        parts.append("")

    for layer, rel_path in CSS_SOURCE_FILES:
        parts.append(f"/* --- {rel_path} --- */")
        parts.append(f"@layer {layer} {{\n{_load_css_file(rel_path)}\n}}")
        parts.append("")

    # Unlayered files come last so they win the cascade.
    for rel_path in CSS_UNLAYERED_FILES:
        parts.append(f"/* --- {rel_path} (unlayered — cascade override) --- */")
        parts.append(_load_css_file(rel_path))
        parts.append("")

    all_sources = [path for _, path in CSS_SOURCE_FILES] + list(CSS_UNLAYERED_FILES)
    source_map = {"version": 3, "sources": all_sources, "mappings": ""}
    map_b64 = base64.b64encode(json.dumps(source_map).encode()).decode()
    parts.append(f"/*# sourceMappingURL=data:application/json;base64,{map_b64} */")

    return "\n".join(parts)
