"""Typed Fragment system — frozen-dataclass primitives + HTML renderer."""

from dazzle.render.fragment.context import RenderContext
from dazzle.render.fragment.errors import (
    CardSafetyError,
    FragmentError,
    HtmxBindingError,
    PrimitiveRegistrationError,
)
from dazzle.render.fragment.escape import RawHTML, Slot
from dazzle.render.fragment.htmx import URL, HxTrigger, TargetSelector
from dazzle.render.fragment.primitives import (
    KPI,
    ActionCard,
    ActivityFeed,
    AppShell,
    Badge,
    BarChart,
    BarTrack,
    BoxPlot,
    Bullet,
    BulletRow,
    Button,
    CalendarGrid,
    Card,
    Combobox,
    ConfirmCheckItem,
    ConfirmGate,
    CsvExportButton,
    DateRangePicker,
    DetailGrid,
    Diagram,
    Drawer,
    EmptyState,
    ErrorPage,
    Field,
    FilterBar,
    FilterColumn,
    FormStack,
    Fragment,
    Funnel,
    FunnelStage,
    Grid,
    GridCell,
    GridRegion,
    Heading,
    Histogram,
    HistogramBin,
    Icon,
    InlineEdit,
    Interactive,
    KanbanBoard,
    LazyTab,
    LazyTabPanel,
    Link,
    ListColumn,
    ListRegion,
    MetricsGrid,
    MetricTile,
    Modal,
    NavGroup,
    NavItem,
    Page,
    PipelineStage,
    PipelineSteps,
    PivotTable,
    ProfileCard,
    Radar,
    ReferenceBand,
    ReferenceLine,
    RefPicker,
    Region,
    Row,
    SearchBox,
    Sidebar,
    Skeleton,
    SkipLink,
    SortHeader,
    Sparkline,
    Split,
    Stack,
    StageBar,
    StatusList,
    StatusListEntry,
    Submit,
    Surface,
    Table,
    Tabs,
    Text,
    Timeline,
    TimelineEvent,
    TimeSeries,
    Toolbar,
    Topbar,
    Tree,
    TreeNode,
)
from dazzle.render.fragment.registry import (
    DEFAULT_REGISTRY,
    PrimitiveRegistry,
    Renderer,
    RendererRegistry,
    primitive,
)
from dazzle.render.fragment.renderer import FragmentRenderer
from dazzle.render.fragment.tokens import (
    ButtonTokens,
    CardTokens,
    Palette,
    Spacing,
    TableTokens,
    Tokens,
)

__all__ = [
    # core
    "Fragment",
    "FragmentRenderer",
    "RenderContext",
    # errors
    "FragmentError",
    "CardSafetyError",
    "HtmxBindingError",
    "PrimitiveRegistrationError",
    # escape hatches
    "RawHTML",
    "Slot",
    # htmx wrappers
    "URL",
    "TargetSelector",
    "HxTrigger",
    # registry
    "primitive",
    "PrimitiveRegistry",
    "Renderer",
    "RendererRegistry",
    "DEFAULT_REGISTRY",
    # tokens
    "Tokens",
    "CardTokens",
    "ButtonTokens",
    "TableTokens",
    "Palette",
    "Spacing",
    # primitives — layout
    "Stack",
    "Row",
    "Split",
    "Grid",
    # primitives — containers
    "Page",
    "AppShell",
    "Surface",
    "Card",
    "Region",
    "Toolbar",
    "Drawer",
    "Modal",
    "Tabs",
    "ErrorPage",
    # primitives — content
    "Text",
    "Heading",
    "Icon",
    "Badge",
    "EmptyState",
    "Skeleton",
    # primitives — interactive
    "Button",
    "Link",
    "InlineEdit",
    "Interactive",
    # primitives — data
    "Table",
    "KanbanBoard",
    "CalendarGrid",
    "Timeline",
    "TimelineEvent",
    "KPI",
    "BarChart",
    "PivotTable",
    "Diagram",
    "TimeSeries",
    "Radar",
    "BoxPlot",
    "Bullet",
    "BulletRow",
    "ActionCard",
    "ProfileCard",
    "MetricTile",
    "MetricsGrid",
    "DetailGrid",
    "GridCell",
    "GridRegion",
    "ListColumn",
    "ListRegion",
    "Histogram",
    "HistogramBin",
    "Funnel",
    "FunnelStage",
    "ActivityFeed",
    "StatusList",
    "StatusListEntry",
    "PipelineSteps",
    "PipelineStage",
    "Sparkline",
    "Tree",
    "TreeNode",
    "BarTrack",
    "StageBar",
    "ReferenceLine",
    "ReferenceBand",
    "LazyTab",
    "LazyTabPanel",
    "SearchBox",
    "ConfirmGate",
    "ConfirmCheckItem",
    "FilterBar",
    "FilterColumn",
    "SortHeader",
    "CsvExportButton",
    "DateRangePicker",
    # primitives — forms
    "FormStack",
    "Field",
    "Combobox",
    "RefPicker",
    "Submit",
    # primitives — navigation
    "Sidebar",
    "Topbar",
    "NavGroup",
    "NavItem",
    "SkipLink",
]
