"""Typed Fragment system — frozen-dataclass primitives + HTML renderer."""

from dazzle.render.fragment.context import RenderContext
from dazzle.render.fragment.errors import (
    CardSafetyError,
    FragmentError,
    HtmxBindingError,
    PrimitiveRegistrationError,
)
from dazzle.render.fragment.escape import RawHTML, Slot
from dazzle.render.fragment.htmx import URL, HxTrigger, TargetSelector
from dazzle.render.fragment.primitives import (
    KPI,
    ActionCard,
    AppShell,
    Badge,
    BarChart,
    BoxPlot,
    Button,
    CalendarGrid,
    Card,
    Combobox,
    Diagram,
    Drawer,
    EmptyState,
    ErrorPage,
    Field,
    FormStack,
    Fragment,
    Grid,
    Heading,
    Icon,
    InlineEdit,
    Interactive,
    KanbanBoard,
    Link,
    Modal,
    NavGroup,
    NavItem,
    Page,
    PivotTable,
    Radar,
    RefPicker,
    Region,
    Row,
    Sidebar,
    Skeleton,
    SkipLink,
    Split,
    Stack,
    Submit,
    Surface,
    Table,
    Tabs,
    Text,
    Timeline,
    TimeSeries,
    Toolbar,
    Topbar,
)
from dazzle.render.fragment.registry import (
    DEFAULT_REGISTRY,
    PrimitiveRegistry,
    Renderer,
    RendererRegistry,
    primitive,
)
from dazzle.render.fragment.renderer import FragmentRenderer
from dazzle.render.fragment.tokens import (
    ButtonTokens,
    CardTokens,
    Palette,
    Spacing,
    TableTokens,
    Tokens,
)

__all__ = [
    # core
    "Fragment",
    "FragmentRenderer",
    "RenderContext",
    # errors
    "FragmentError",
    "CardSafetyError",
    "HtmxBindingError",
    "PrimitiveRegistrationError",
    # escape hatches
    "RawHTML",
    "Slot",
    # htmx wrappers
    "URL",
    "TargetSelector",
    "HxTrigger",
    # registry
    "primitive",
    "PrimitiveRegistry",
    "Renderer",
    "RendererRegistry",
    "DEFAULT_REGISTRY",
    # tokens
    "Tokens",
    "CardTokens",
    "ButtonTokens",
    "TableTokens",
    "Palette",
    "Spacing",
    # primitives — layout
    "Stack",
    "Row",
    "Split",
    "Grid",
    # primitives — containers
    "Page",
    "AppShell",
    "Surface",
    "Card",
    "Region",
    "Toolbar",
    "Drawer",
    "Modal",
    "Tabs",
    "ErrorPage",
    # primitives — content
    "Text",
    "Heading",
    "Icon",
    "Badge",
    "EmptyState",
    "Skeleton",
    # primitives — interactive
    "Button",
    "Link",
    "InlineEdit",
    "Interactive",
    # primitives — data
    "Table",
    "KanbanBoard",
    "CalendarGrid",
    "Timeline",
    "KPI",
    "BarChart",
    "PivotTable",
    "Diagram",
    "TimeSeries",
    "Radar",
    "BoxPlot",
    "ActionCard",
    # primitives — forms
    "FormStack",
    "Field",
    "Combobox",
    "RefPicker",
    "Submit",
    # primitives — navigation
    "Sidebar",
    "Topbar",
    "NavGroup",
    "NavItem",
    "SkipLink",
]
