"""
CLI commands for demo data management.

Commands:
  dazzle demo load           — Load seed data into a running instance (REST)
  dazzle demo validate       — Validate seed files against DSL
  dazzle demo reset          — Clear and reload demo data (REST)
  dazzle demo reset-and-load — Test-mode reset+seed with STABLE personas (#1627)
  dazzle demo propose        — Propose a demo data blueprint from DSL
  dazzle demo save           — Save a blueprint JSON file
  dazzle demo generate       — Generate demo data files from the blueprint
  dazzle demo quality        — Score felt product/demo quality (#1626)
"""

import json
from contextlib import suppress
from pathlib import Path
from typing import Any

import typer

from dazzle.core.demo_blueprint_persistence import load_blueprint
from dazzle.demo_data.test_mode_load import demo_ops_playbook, reset_and_load
from dazzle.product_quality import score_project, score_status_lines

demo_app = typer.Typer(help="Demo data management commands.", no_args_is_help=True)

DEFAULT_TEST_PASSWORD = "dazzle-test-2026"


def _generate_test_personas_toml(
    project_root: Path,
    blueprint_result: dict[str, Any],
) -> None:
    """Generate .dazzle/test_personas.toml from the demo blueprint.

    Does not overwrite if the file already exists.
    """

    toml_path = project_root / ".dazzle" / "test_personas.toml"
    if toml_path.exists():
        typer.echo(
            f"test_personas.toml already exists at {toml_path}, skipping credential generation."
        )
        return

    # Extract persona info from blueprint result
    personas_data: list[dict[str, Any]] = blueprint_result.get("personas", [])
    if not personas_data:
        return

    # Best-effort read of test_password override; default applies on any failure (#smells-1.1).
    test_password = DEFAULT_TEST_PASSWORD
    with suppress(Exception):
        import tomllib

        toml_conf = project_root / "dazzle.toml"
        if toml_conf.exists():
            with toml_conf.open("rb") as f:
                config = tomllib.load(f)
            test_password = config.get("demo", {}).get("test_password", DEFAULT_TEST_PASSWORD)

    lines = ["# Generated by 'dazzle demo propose' for journey testing", ""]
    for persona in personas_data:
        name = persona.get("persona_name", "").lower().replace(" ", "_")
        if not name:
            continue
        email = f"{name}@demo.example.com"
        lines.append(f"[personas.{name}]")
        lines.append(f'email = "{email}"')
        lines.append(f'password = "{test_password}"')
        lines.append("")

    if len(lines) > 2:  # More than just the header
        toml_path.parent.mkdir(parents=True, exist_ok=True)
        toml_path.write_text("\n".join(lines), encoding="utf-8")
        typer.echo(f"Generated test_personas.toml at {toml_path}")


def _find_data_dir(project_root: Path) -> Path | None:
    """Find the demo data directory.

    Order of precedence:
    1. ``demo_data/`` at the project root (explicit, user-curated)
    2. ``.dazzle/demo_data/`` (generated via ``dazzle demo generate``)
    3. ``dsl/seeds/demo_data/`` (blueprint-only — the default location
       used by ``dazzle init`` and by the example apps; #817)
    """
    for candidate in [
        project_root / "demo_data",
        project_root / ".dazzle" / "demo_data",
        project_root / "dsl" / "seeds" / "demo_data",
    ]:
        if candidate.is_dir():
            return candidate
    return None


@demo_app.command(name="load")
def load_command(
    base_url: str = typer.Option(
        "http://localhost:8000",
        "--base-url",
        "-u",
        help="Base URL of the running Dazzle instance",
    ),
    email: str = typer.Option(
        None,
        "--email",
        "-e",
        help="Admin email for authentication",
    ),
    password: str = typer.Option(
        None,
        "--password",
        "-p",
        help="Admin password for authentication",
    ),
    data_dir: Path | None = typer.Option(
        None,
        "--data-dir",
        "-d",
        help="Path to seed data directory (auto-detected if omitted)",
    ),
    entities: str | None = typer.Option(
        None,
        "--entities",
        help="Comma-separated entity names to load (default: all)",
    ),
    project_root: Path = typer.Option(
        Path("."),
        "--project",
        help="Project root directory",
    ),
) -> None:
    """Load demo seed data into a running Dazzle instance."""
    from dazzle.demo_data.loader import DemoDataLoader, topological_sort_entities

    project_root = project_root.resolve()

    # Parse DSL to get entity graph
    typer.echo("Parsing DSL...")
    try:
        from dazzle.cli.utils import load_project_appspec

        appspec = load_project_appspec(project_root)
    except Exception as e:
        typer.echo(f"Failed to parse DSL: {e}", err=True)
        raise typer.Exit(1)

    # Find data directory
    if data_dir is None:
        data_dir = _find_data_dir(project_root)
        if data_dir is None:
            typer.echo(
                "No demo data directory found. Run 'dazzle demo_data generate' first.", err=True
            )
            raise typer.Exit(1)
    typer.echo(f"Data directory: {data_dir}")

    # Topological sort
    entity_order = topological_sort_entities(appspec.domain.entities)
    typer.echo(f"Entity load order: {', '.join(entity_order)}")

    # Parse entity filter
    entities_filter = [e.strip() for e in entities.split(",")] if entities else None

    # Load
    with DemoDataLoader(base_url=base_url, email=email, password=password) as loader:
        if email and password:
            typer.echo("Authenticating...")
            try:
                loader.authenticate()
            except RuntimeError as e:
                typer.echo(f"Authentication failed: {e}", err=True)
                raise typer.Exit(1)

        typer.echo("Loading demo data...")
        report = loader.load_all(data_dir, entity_order, entities_filter=entities_filter)

    typer.echo("")
    typer.echo(report.summary())

    if report.total_failed > 0:
        raise typer.Exit(1)


@demo_app.command(name="validate")
def validate_command(
    data_dir: Path | None = typer.Option(
        None,
        "--data-dir",
        "-d",
        help="Path to seed data directory (auto-detected if omitted)",
    ),
    project_root: Path = typer.Option(
        Path("."),
        "--project",
        help="Project root directory",
    ),
) -> None:
    """Validate seed files against the DSL entity definitions."""
    from dazzle.demo_data.loader import validate_seed_data

    project_root = project_root.resolve()

    # Parse DSL
    typer.echo("Parsing DSL...")
    try:
        from dazzle.cli.utils import load_project_appspec

        appspec = load_project_appspec(project_root)
    except Exception as e:
        typer.echo(f"Failed to parse DSL: {e}", err=True)
        raise typer.Exit(1)

    # Find data directory
    if data_dir is None:
        data_dir = _find_data_dir(project_root)
        if data_dir is None:
            typer.echo("No demo data directory found.", err=True)
            raise typer.Exit(1)

    typer.echo(f"Validating seed data in {data_dir}...")
    errors = validate_seed_data(data_dir, appspec.domain.entities)

    if errors:
        typer.echo(f"\n{len(errors)} validation errors found:")
        for err in errors:
            typer.echo(f"  - {err}")
        raise typer.Exit(1)
    else:
        typer.echo("All seed data is valid.")


@demo_app.command(name="reset-and-load")
def reset_and_load_command(
    project_root: Path = typer.Option(
        Path("."),
        "--project",
        help="Project root directory",
    ),
    base_url: str | None = typer.Option(
        None,
        "--base-url",
        "-u",
        help="API base URL (default: .dazzle/runtime.json api_url)",
    ),
    data_dir: Path | None = typer.Option(
        None,
        "--data-dir",
        "-d",
        help="Path to seed data directory (auto-detected if omitted)",
    ),
    yes: bool = typer.Option(
        False,
        "--yes",
        "-y",
        help="Skip confirmation prompt",
    ),
    json_output: bool = typer.Option(
        False,
        "--json",
        help="Emit full structured report as JSON",
    ),
    skip_verify: bool = typer.Option(
        False,
        "--skip-verify",
        help="Do not score persona_homes residual after seed",
    ),
) -> None:
    """Reset + seed via /__test__/* with STABLE persona ids (#1627).

    Prefer this over ``dazzle demo load`` for agent demos: it uses the
    same path as QA (no CSRF entity POSTs), reads ports/secret from
    runtime.json, and verifies assignment-aware persona homes.

    Order after this command: authenticate with role= (never before reset).
    """
    project_root = project_root.resolve()
    if not (project_root / "dazzle.toml").is_file():
        typer.echo(f"No dazzle.toml at {project_root}", err=True)
        raise typer.Exit(1)

    if not yes:
        confirm = typer.confirm(
            "This will POST /__test__/reset then seed jsonl fixtures. Continue?"
        )
        if not confirm:
            raise typer.Abort()

    report = reset_and_load(
        project_root,
        base_url=base_url,
        data_dir=data_dir,
        verify_persona_homes=not skip_verify,
    )

    if json_output:
        # Never dump raw test_secret in JSON stdout
        safe = {k: v for k, v in report.items() if k != "test_secret"}
        typer.echo(json.dumps(safe, indent=2, default=str))
    else:
        if report.get("ok"):
            typer.echo(
                f"OK reset-and-load: {report.get('fixture_count', 0)} fixtures → "
                f"{report.get('api_url')}"
            )
            residual = report.get("persona_homes_residual")
            if residual is not None:
                typer.echo(f"  persona_homes residual: {residual}")
            if report.get("warning"):
                typer.echo(f"  warning: {report['warning']}", err=True)
            typer.echo(f"  next: {report.get('next')}")
            typer.echo(
                f"  emails: {{role}}@{report.get('persona_email_domain', 'demo.dazzle.local')}"
            )
        else:
            typer.echo(f"FAIL: {report.get('error', 'unknown')}", err=True)
            playbook = report.get("playbook") or demo_ops_playbook()
            typer.echo("Tribal playbook:", err=True)
            for step in playbook.get("order", []):
                typer.echo(f"  · {step}", err=True)

    if not report.get("ok"):
        raise typer.Exit(1)


@demo_app.command(name="reset")
def reset_command(
    base_url: str = typer.Option(
        "http://localhost:8000",
        "--base-url",
        "-u",
        help="Base URL of the running Dazzle instance",
    ),
    email: str = typer.Option(
        None,
        "--email",
        "-e",
        help="Admin email for authentication",
    ),
    password: str = typer.Option(
        None,
        "--password",
        "-p",
        help="Admin password for authentication",
    ),
    data_dir: Path | None = typer.Option(
        None,
        "--data-dir",
        "-d",
        help="Path to seed data directory (auto-detected if omitted)",
    ),
    project_root: Path = typer.Option(
        Path("."),
        "--project",
        help="Project root directory",
    ),
    yes: bool = typer.Option(
        False,
        "--yes",
        "-y",
        help="Skip confirmation prompt",
    ),
) -> None:
    """Clear all entity data and reload from seed files.

    WARNING: This deletes all existing data in reverse dependency order,
    then reloads from seed files.
    """
    from dazzle.demo_data.loader import DemoDataLoader, topological_sort_entities

    project_root = project_root.resolve()

    if not yes:
        confirm = typer.confirm("This will DELETE all entity data and reload. Continue?")
        if not confirm:
            raise typer.Abort()

    # Parse DSL
    typer.echo("Parsing DSL...")
    try:
        from dazzle.cli.utils import load_project_appspec

        appspec = load_project_appspec(project_root)
    except Exception as e:
        typer.echo(f"Failed to parse DSL: {e}", err=True)
        raise typer.Exit(1)

    # Find data directory
    if data_dir is None:
        data_dir = _find_data_dir(project_root)
        if data_dir is None:
            typer.echo("No demo data directory found.", err=True)
            raise typer.Exit(1)

    entity_order = topological_sort_entities(appspec.domain.entities)

    with DemoDataLoader(base_url=base_url, email=email, password=password) as loader:
        if email and password:
            typer.echo("Authenticating...")
            try:
                loader.authenticate()
            except RuntimeError as e:
                typer.echo(f"Authentication failed: {e}", err=True)
                raise typer.Exit(1)

        # Delete in reverse order (children first)
        client = loader._get_client()
        typer.echo("Deleting existing data (reverse dependency order)...")
        for entity_name in reversed(entity_order):
            from dazzle.core.strings import to_api_plural

            endpoint = f"/{to_api_plural(entity_name)}"
            try:
                resp = client.delete(endpoint, headers=loader._headers())
                if resp.status_code in (200, 204):
                    typer.echo(f"  Cleared {entity_name}")
                elif resp.status_code == 404:
                    typer.echo(f"  {entity_name}: no delete endpoint")
                else:
                    typer.echo(f"  {entity_name}: HTTP {resp.status_code}")
            except Exception as e:
                typer.echo(f"  {entity_name}: {e}")

        # Reload
        typer.echo("\nReloading demo data...")
        report = loader.load_all(data_dir, entity_order)

    typer.echo("")
    typer.echo(report.summary())

    if report.total_failed > 0:
        raise typer.Exit(1)


@demo_app.command(name="propose")
def propose_command(
    domain_description: str = typer.Option(
        "",
        "--domain",
        "-d",
        help="Domain description (e.g. 'solar energy installer')",
    ),
    tenant_count: int = typer.Option(
        2,
        "--tenants",
        "-t",
        help="Number of demo tenants to generate",
    ),
    entities: str | None = typer.Option(
        None,
        "--entities",
        "-e",
        help="Comma-separated entity names to include (default: all)",
    ),
    include_metadata: bool = typer.Option(
        True,
        "--metadata/--no-metadata",
        help="Include tenant and persona metadata",
    ),
    quick_mode: bool = typer.Option(
        False,
        "--quick",
        "-q",
        help="Quick mode: only entities with surfaces/references",
    ),
    project_root: Path = typer.Option(
        Path("."),
        "--project",
        help="Project root directory",
    ),
    json_output: bool = typer.Option(False, "--json", help="Output as JSON"),
) -> None:
    """Analyze DSL and propose a Demo Data Blueprint."""
    from dazzle.cli._output import format_output
    from dazzle.mcp.server.handlers.demo_data import demo_propose_impl

    project_root = project_root.resolve()

    filter_entities: list[str] | None = None
    if entities:
        filter_entities = [e.strip() for e in entities.split(",")]

    try:
        result = demo_propose_impl(
            project_root,
            domain_description=domain_description,
            tenant_count=tenant_count,
            filter_entities=filter_entities,
            include_metadata=include_metadata,
            quick_mode=quick_mode,
        )
    except Exception as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(code=1)

    typer.echo(format_output(result, as_json=json_output))

    # Generate test_personas.toml for journey testing
    _generate_test_personas_toml(project_root, result)


@demo_app.command(name="save")
def save_command(
    blueprint_file: Path = typer.Option(
        ...,
        "--blueprint-file",
        "-f",
        help="Path to JSON file containing the blueprint data",
    ),
    merge_entities: bool = typer.Option(
        False,
        "--merge",
        help="Merge new entities with existing blueprint",
    ),
    validate_coverage: bool = typer.Option(
        True,
        "--validate/--no-validate",
        help="Validate entity coverage against DSL",
    ),
    project_root: Path = typer.Option(
        Path("."),
        "--project",
        help="Project root directory",
    ),
    json_output: bool = typer.Option(False, "--json", help="Output as JSON"),
) -> None:
    """Save a Demo Data Blueprint to .dazzle/demo_data/blueprint.json."""
    import json

    from dazzle.cli._output import format_output
    from dazzle.mcp.server.handlers.demo_data import demo_save_impl

    project_root = project_root.resolve()

    blueprint_path = Path(blueprint_file).resolve()
    if not blueprint_path.exists():
        typer.echo(f"File not found: {blueprint_path}", err=True)
        raise typer.Exit(code=1)

    try:
        blueprint_data = json.loads(blueprint_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as e:
        typer.echo(f"Error reading blueprint file: {e}", err=True)
        raise typer.Exit(code=1)

    try:
        result = demo_save_impl(
            project_root,
            blueprint_data=blueprint_data,
            merge_entities=merge_entities,
            validate_coverage=validate_coverage,
        )
    except Exception as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(code=1)

    typer.echo(format_output(result, as_json=json_output))


@demo_app.command(name="verify")
def verify_command(
    project_root: Path = typer.Option(
        Path("."),
        "--project",
        help="Project root directory",
    ),
    strict: bool = typer.Option(
        False,
        "--strict",
        help="Exit non-zero on warnings as well as errors",
    ),
    json_output: bool = typer.Option(False, "--json", help="Output as JSON"),
) -> None:
    """Statically check the project's demo blueprint against the AppSpec (#821).

    Finds strategy/type mismatches, unknown fields, invalid enum
    values, length-cap violations, and required fields without
    patterns — all the blueprint authoring drift that currently
    only surfaces at seed time.

    Exit codes:
      0 — no errors (warnings allowed unless --strict)
      1 — errors found (or --strict with warnings)
      2 — couldn't load blueprint or appspec
    """
    import json as _json

    from dazzle.cli.utils import load_project_appspec
    from dazzle.demo_data.verify import verify_blueprint

    project_root = project_root.resolve()

    blueprint = load_blueprint(project_root)
    if blueprint is None:
        typer.echo("No blueprint found. Run `dazzle demo propose` first.", err=True)
        raise typer.Exit(code=2)

    try:
        appspec = load_project_appspec(project_root)
    except Exception as exc:
        typer.echo(f"Failed to load AppSpec: {exc}", err=True)
        raise typer.Exit(code=2) from exc

    report = verify_blueprint(blueprint, appspec)

    if json_output:
        typer.echo(
            _json.dumps(
                {
                    "errors": [v.__dict__ for v in report.errors()],
                    "warnings": [v.__dict__ for v in report.warnings()],
                },
                indent=2,
            )
        )
    else:
        for v in report.errors():
            typer.echo(f"[error] {v.entity}.{v.field or '(entity)'}: {v.rule} — {v.message}")
        for v in report.warnings():
            typer.echo(f"[warning] {v.entity}.{v.field or '(entity)'}: {v.rule} — {v.message}")
        if not report.violations:
            typer.echo("Blueprint looks healthy — no violations.")
        else:
            typer.echo(f"\n{len(report.errors())} error(s), {len(report.warnings())} warning(s).")

    if report.has_errors or (strict and report.warnings()):
        raise typer.Exit(code=1)


@demo_app.command(name="generate")
def generate_command(
    output_format: str = typer.Option(
        "csv",
        "--format",
        help="Output format (csv or json)",
    ),
    output_dir: str = typer.Option(
        "demo_data",
        "--output-dir",
        "-o",
        help="Output directory relative to project root",
    ),
    entities: str | None = typer.Option(
        None,
        "--entities",
        "-e",
        help="Comma-separated entity names to generate (default: all)",
    ),
    project_root: Path = typer.Option(
        Path("."),
        "--project",
        help="Project root directory",
    ),
    json_output: bool = typer.Option(False, "--json", help="Output as JSON"),
) -> None:
    """Generate demo data files from the blueprint."""
    from dazzle.cli._output import format_output
    from dazzle.mcp.server.handlers.demo_data import demo_generate_impl

    project_root = project_root.resolve()

    filter_entities: list[str] | None = None
    if entities:
        filter_entities = [e.strip() for e in entities.split(",")]

    try:
        result = demo_generate_impl(
            project_root,
            output_format=output_format,
            output_dir=output_dir,
            filter_entities=filter_entities,
        )
    except Exception as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(code=1)

    typer.echo(format_output(result, as_json=json_output))


@demo_app.command(name="quality")
def quality_command(
    project_root: Path = typer.Option(
        Path("."),
        "--project",
        "-p",
        help="App root (dazzle.toml) or examples/ for the showcase fleet",
    ),
    app: str | None = typer.Option(
        None,
        "--app",
        "-a",
        help="When scoring examples/, limit persona-home/stills to this app",
    ),
    min_home_hits: int = typer.Option(
        1,
        "--min-home-hits",
        help="Minimum seed rows per current_user region (default 1)",
    ),
    json_output: bool = typer.Option(False, "--json", help="Output full report as JSON"),
    strict: bool = typer.Option(
        False,
        "--strict",
        help="Exit 1 when residual_total > 0",
    ),
) -> None:
    """Score felt product/demo quality (persona homes, metric/list, stills, maturity).

    Structural residual (validate/lint) can be green while persona desks are
    empty — this bar catches assignment-aware seed residual, metric↔list
    current_user footguns (F10/#1632), and empty-hero still floors (#1626).
    Same payload as MCP product_quality(operation=score).
    """
    root = project_root.resolve()
    report = score_project(root, app=app, min_home_hits=min_home_hits)

    if json_output:
        payload = report.to_dict()
        payload["status_lines"] = score_status_lines(report)
        typer.echo(json.dumps(payload, indent=2))
    else:
        for line in score_status_lines(report):
            typer.echo(line)
        for rec in report.recommended:
            typer.echo(f"  → {rec}")
        if report.force:
            typer.echo(f"force: {report.force}")

    if strict and report.residual_total > 0:
        raise typer.Exit(code=1)
