"""
JavaScript generator for DNR-UI runtime.

Generates pure JavaScript code from UISpec for browser execution.
No React, no frameworks - just vanilla JS with a minimal runtime.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from dazzle_dnr_ui.specs import (
    UISpec,
    ComponentSpec,
    WorkspaceSpec,
    ThemeSpec,
)
from dazzle_dnr_ui.specs.state import (
    Binding,
    LiteralBinding,
    PropBinding,
    StateBinding,
    WorkspaceStateBinding,
    AppStateBinding,
    DerivedBinding,
    StateSpec,
    StateScope,
)
from dazzle_dnr_ui.specs.view import (
    ViewNode,
    ElementNode,
    ConditionalNode,
    LoopNode,
    SlotNode,
    TextNode,
)


# =============================================================================
# Runtime Template
# =============================================================================

RUNTIME_JS = '''
/**
 * DNR-UI Runtime - Minimal reactive UI runtime
 * Generated by Dazzle Native Runtime
 */
(function(global) {
  'use strict';

  // ==========================================================================
  // Signals-based Reactivity
  // ==========================================================================

  let currentSubscriber = null;
  const signalDeps = new Map();

  function createSignal(initialValue, options = {}) {
    let value = initialValue;
    const subscribers = new Set();
    const { persistent, key } = options;

    // Load from storage if persistent
    if (persistent && key) {
      const stored = localStorage.getItem(`dnr_${key}`);
      if (stored !== null) {
        try {
          value = JSON.parse(stored);
        } catch (e) {
          console.warn(`Failed to parse stored value for ${key}`, e);
        }
      }
    }

    function getter() {
      if (currentSubscriber) {
        subscribers.add(currentSubscriber);
      }
      return value;
    }

    function setter(newValue) {
      if (typeof newValue === 'function') {
        newValue = newValue(value);
      }
      if (value !== newValue) {
        value = newValue;
        // Persist if needed
        if (persistent && key) {
          localStorage.setItem(`dnr_${key}`, JSON.stringify(value));
        }
        // Notify subscribers
        subscribers.forEach(fn => fn());
      }
    }

    return [getter, setter];
  }

  function createEffect(fn) {
    function execute() {
      currentSubscriber = execute;
      try {
        fn();
      } finally {
        currentSubscriber = null;
      }
    }
    execute();
  }

  function createMemo(fn) {
    let cachedValue;
    let dirty = true;

    createEffect(() => {
      dirty = true;
    });

    return function() {
      if (dirty) {
        cachedValue = fn();
        dirty = false;
      }
      return cachedValue;
    };
  }

  // ==========================================================================
  // State Management
  // ==========================================================================

  const stateStores = {
    local: new Map(),    // Component-local state
    workspace: new Map(), // Workspace-level state
    app: new Map(),      // App-global state
    session: new Map()   // Session-persistent state
  };

  function getState(scope, path) {
    const store = stateStores[scope];
    if (!store) return undefined;
    const [getter] = store.get(path) || [];
    return getter ? getter() : undefined;
  }

  function setState(scope, path, value) {
    const store = stateStores[scope];
    if (!store) return;
    const [, setter] = store.get(path) || [];
    if (setter) setter(value);
  }

  function registerState(scope, path, initial, persistent = false) {
    const store = stateStores[scope];
    if (!store.has(path)) {
      const signal = createSignal(initial, {
        persistent: persistent || scope === 'session',
        key: `${scope}_${path}`
      });
      store.set(path, signal);
    }
    return store.get(path);
  }

  // ==========================================================================
  // DOM Helpers
  // ==========================================================================

  function createElement(tag, props = {}, children = []) {
    const el = document.createElement(tag);

    Object.entries(props).forEach(([key, value]) => {
      if (key === 'className') {
        el.className = value;
      } else if (key === 'style' && typeof value === 'object') {
        Object.assign(el.style, value);
      } else if (key.startsWith('on') && typeof value === 'function') {
        const event = key.slice(2).toLowerCase();
        el.addEventListener(event, value);
      } else if (key === 'ref' && typeof value === 'function') {
        value(el);
      } else if (value !== null && value !== undefined && value !== false) {
        el.setAttribute(key, value);
      }
    });

    children.forEach(child => {
      if (typeof child === 'string' || typeof child === 'number') {
        el.appendChild(document.createTextNode(String(child)));
      } else if (child instanceof Node) {
        el.appendChild(child);
      } else if (Array.isArray(child)) {
        child.forEach(c => {
          if (c instanceof Node) el.appendChild(c);
          else if (c != null) el.appendChild(document.createTextNode(String(c)));
        });
      }
    });

    return el;
  }

  function render(container, component) {
    container.innerHTML = '';
    if (component instanceof Node) {
      container.appendChild(component);
    } else if (typeof component === 'function') {
      createEffect(() => {
        container.innerHTML = '';
        const result = component();
        if (result instanceof Node) {
          container.appendChild(result);
        }
      });
    }
  }

  // ==========================================================================
  // Binding Resolution
  // ==========================================================================

  function resolveBinding(binding, context) {
    if (!binding || !binding.kind) return binding;

    switch (binding.kind) {
      case 'literal':
        return binding.value;

      case 'prop':
        return getByPath(context.props, binding.path);

      case 'state':
        return getState('local', `${context.componentId}_${binding.path}`);

      case 'workspaceState':
        return getState('workspace', binding.path);

      case 'appState':
        return getState('app', binding.path);

      case 'derived':
        // Simple expression evaluation (be careful with this in production!)
        try {
          return evalExpression(binding.expr, context);
        } catch (e) {
          console.warn('Expression evaluation failed:', binding.expr, e);
          return undefined;
        }

      default:
        return binding;
    }
  }

  function getByPath(obj, path) {
    if (!obj || !path) return undefined;
    return path.split('.').reduce((o, p) => o && o[p], obj);
  }

  function evalExpression(expr, context) {
    // Safe expression evaluation using Function constructor
    // Only allows access to context values
    const fn = new Function('ctx', `with(ctx) { return ${expr}; }`);
    return fn({
      props: context.props || {},
      state: context.state || {},
      workspace: stateStores.workspace,
      app: stateStores.app
    });
  }

  // ==========================================================================
  // Component Registry
  // ==========================================================================

  const componentRegistry = new Map();

  function registerComponent(name, renderFn) {
    componentRegistry.set(name, renderFn);
  }

  function getComponent(name) {
    return componentRegistry.get(name);
  }

  // ==========================================================================
  // Built-in Primitives
  // ==========================================================================

  // Page component
  registerComponent('Page', (props, children) => {
    return createElement('div', {
      className: 'dnr-page',
      style: { padding: 'var(--spacing-md, 16px)' }
    }, [
      props.title ? createElement('h1', { className: 'dnr-page-title' }, [props.title]) : null,
      ...children
    ].filter(Boolean));
  });

  // Card component
  registerComponent('Card', (props, children) => {
    return createElement('div', {
      className: 'dnr-card',
      style: {
        border: '1px solid var(--color-border, #ddd)',
        borderRadius: 'var(--radius-md, 4px)',
        padding: 'var(--spacing-md, 16px)',
        backgroundColor: 'var(--color-surface, #fff)'
      }
    }, [
      props.title ? createElement('h2', { className: 'dnr-card-title' }, [props.title]) : null,
      ...children
    ].filter(Boolean));
  });

  // Text component
  registerComponent('Text', (props, children) => {
    const tag = props.variant === 'heading' ? 'h2' :
                props.variant === 'subheading' ? 'h3' :
                props.variant === 'label' ? 'label' : 'p';
    return createElement(tag, { className: `dnr-text dnr-text-${props.variant || 'body'}` }, children);
  });

  // Button component
  registerComponent('Button', (props, children) => {
    return createElement('button', {
      className: `dnr-button dnr-button-${props.variant || 'default'}`,
      onClick: props.onClick,
      disabled: props.disabled,
      type: props.type || 'button',
      style: {
        padding: 'var(--spacing-sm, 8px) var(--spacing-md, 16px)',
        borderRadius: 'var(--radius-sm, 2px)',
        cursor: props.disabled ? 'not-allowed' : 'pointer'
      }
    }, children.length ? children : [props.label]);
  });

  // Input component
  registerComponent('Input', (props) => {
    return createElement('input', {
      className: 'dnr-input',
      type: props.type || 'text',
      value: props.value,
      placeholder: props.placeholder,
      disabled: props.disabled,
      onInput: (e) => props.onChange && props.onChange(e.target.value),
      style: {
        padding: 'var(--spacing-sm, 8px)',
        border: '1px solid var(--color-border, #ddd)',
        borderRadius: 'var(--radius-sm, 2px)',
        width: '100%'
      }
    });
  });

  // DataTable component
  registerComponent('DataTable', (props) => {
    const { columns, data, onRowClick } = props;

    const thead = createElement('thead', {}, [
      createElement('tr', {}, (columns || []).map(col =>
        createElement('th', { style: { textAlign: 'left', padding: '8px' } }, [col.label || col.key])
      ))
    ]);

    const tbody = createElement('tbody', {}, (data || []).map((row, idx) =>
      createElement('tr', {
        onClick: () => onRowClick && onRowClick(row),
        style: { cursor: onRowClick ? 'pointer' : 'default' }
      }, (columns || []).map(col =>
        createElement('td', { style: { padding: '8px' } }, [row[col.key]])
      ))
    ));

    return createElement('table', {
      className: 'dnr-data-table',
      style: { width: '100%', borderCollapse: 'collapse' }
    }, [thead, tbody]);
  });

  // Form component
  registerComponent('Form', (props, children) => {
    return createElement('form', {
      className: 'dnr-form',
      onSubmit: (e) => {
        e.preventDefault();
        props.onSubmit && props.onSubmit(e);
      }
    }, [
      props.title ? createElement('h2', { className: 'dnr-form-title' }, [props.title]) : null,
      ...children
    ].filter(Boolean));
  });

  // Stack (flexbox) component
  registerComponent('Stack', (props, children) => {
    return createElement('div', {
      className: 'dnr-stack',
      style: {
        display: 'flex',
        flexDirection: props.direction || 'column',
        gap: `var(--spacing-${props.gap || 'md'}, 16px)`,
        alignItems: props.align || 'stretch',
        justifyContent: props.justify || 'flex-start'
      }
    }, children);
  });

  // FilterableTable pattern component
  registerComponent('FilterableTable', (props) => {
    // This is a pattern that combines filter inputs with a data table
    return createElement('div', { className: 'dnr-filterable-table' }, [
      createElement('div', { className: 'dnr-filters', style: { marginBottom: '16px' } }, [
        props.filterPlaceholder ?
          createElement('input', {
            type: 'text',
            placeholder: props.filterPlaceholder,
            style: { padding: '8px', width: '200px' }
          }) : null
      ].filter(Boolean)),
      componentRegistry.get('DataTable')(props)
    ]);
  });

  // ==========================================================================
  // View Tree Renderer
  // ==========================================================================

  function renderViewNode(node, context) {
    if (!node) return null;

    switch (node.kind) {
      case 'element':
        return renderElementNode(node, context);

      case 'conditional':
        return renderConditionalNode(node, context);

      case 'loop':
        return renderLoopNode(node, context);

      case 'slot':
        return renderSlotNode(node, context);

      case 'text':
        return renderTextNode(node, context);

      default:
        console.warn('Unknown node kind:', node.kind);
        return null;
    }
  }

  function renderElementNode(node, context) {
    const componentName = node.as || node.as_;
    const ComponentFn = componentRegistry.get(componentName);

    // Resolve all props
    const resolvedProps = {};
    Object.entries(node.props || {}).forEach(([key, binding]) => {
      resolvedProps[key] = resolveBinding(binding, context);
    });

    // Render children
    const children = (node.children || []).map(child => renderViewNode(child, context)).filter(Boolean);

    if (ComponentFn) {
      return ComponentFn(resolvedProps, children);
    } else {
      // Fall back to HTML element
      return createElement(componentName.toLowerCase(), resolvedProps, children);
    }
  }

  function renderConditionalNode(node, context) {
    const condition = resolveBinding(node.condition, context);
    if (condition) {
      return renderViewNode(node.then_branch || node.thenBranch, context);
    } else if (node.else_branch || node.elseBranch) {
      return renderViewNode(node.else_branch || node.elseBranch, context);
    }
    return null;
  }

  function renderLoopNode(node, context) {
    const items = resolveBinding(node.items, context) || [];
    const itemVar = node.item_var || node.itemVar || 'item';
    const keyPath = node.key_path || node.keyPath || 'id';

    const fragment = document.createDocumentFragment();
    items.forEach((item, index) => {
      const itemContext = {
        ...context,
        props: {
          ...context.props,
          [itemVar]: item,
          [`${itemVar}Index`]: index
        }
      };
      const child = renderViewNode(node.template, itemContext);
      if (child) {
        child.setAttribute('data-key', getByPath(item, keyPath) || index);
        fragment.appendChild(child);
      }
    });
    return fragment;
  }

  function renderSlotNode(node, context) {
    const slotContent = context.slots && context.slots[node.name];
    if (slotContent) {
      return renderViewNode(slotContent, context);
    } else if (node.fallback) {
      return renderViewNode(node.fallback, context);
    }
    return null;
  }

  function renderTextNode(node, context) {
    const content = resolveBinding(node.content, context);
    return document.createTextNode(String(content || ''));
  }

  // ==========================================================================
  // Theme System
  // ==========================================================================

  function applyTheme(theme) {
    if (!theme || !theme.tokens) return;

    const root = document.documentElement;

    // Apply colors
    Object.entries(theme.tokens.colors || {}).forEach(([name, value]) => {
      root.style.setProperty(`--color-${name}`, value);
    });

    // Apply spacing
    Object.entries(theme.tokens.spacing || {}).forEach(([name, value]) => {
      root.style.setProperty(`--spacing-${name}`, typeof value === 'number' ? `${value}px` : value);
    });

    // Apply radii
    Object.entries(theme.tokens.radii || {}).forEach(([name, value]) => {
      root.style.setProperty(`--radius-${name}`, typeof value === 'number' ? `${value}px` : value);
    });
  }

  // ==========================================================================
  // Action Execution
  // ==========================================================================

  async function executeAction(action, context) {
    if (!action) return;

    // Apply state transitions
    if (action.transitions) {
      action.transitions.forEach(transition => {
        const scope = transition.scope || 'local';
        const path = scope === 'local' ?
          `${context.componentId}_${transition.target_state || transition.targetState}` :
          (transition.target_state || transition.targetState);

        setState(scope, path, transition.update || transition.value);
      });
    }

    // Execute effect
    if (action.effect) {
      await executeEffect(action.effect, context);
    }
  }

  async function executeEffect(effect, context) {
    if (!effect) return;

    switch (effect.kind) {
      case 'fetch':
        try {
          const response = await fetch(`/api/${effect.backend_service || effect.backendService}`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(context.data || {})
          });
          const data = await response.json();
          if (effect.on_success || effect.onSuccess) {
            const successAction = context.getAction(effect.on_success || effect.onSuccess);
            if (successAction) {
              await executeAction(successAction, { ...context, data });
            }
          }
        } catch (error) {
          if (effect.on_error || effect.onError) {
            const errorAction = context.getAction(effect.on_error || effect.onError);
            if (errorAction) {
              await executeAction(errorAction, { ...context, error });
            }
          }
        }
        break;

      case 'navigate':
        const route = effect.route;
        const params = {};
        Object.entries(effect.params || {}).forEach(([key, binding]) => {
          params[key] = resolveBinding(binding, context);
        });
        // Simple navigation - replace route params
        let url = route;
        Object.entries(params).forEach(([key, value]) => {
          url = url.replace(`{${key}}`, encodeURIComponent(value));
        });
        window.history.pushState({}, '', url);
        // Trigger route change event
        window.dispatchEvent(new CustomEvent('dnr-navigate', { detail: { url } }));
        break;

      case 'log':
        console.log(resolveBinding(effect.message, context));
        break;

      case 'toast':
        alert(resolveBinding(effect.message, context)); // Simple fallback
        break;
    }
  }

  // ==========================================================================
  // Application Bootstrap
  // ==========================================================================

  function createApp(uiSpec) {
    // Register custom components from spec
    (uiSpec.components || []).forEach(comp => {
      if (comp.view && !componentRegistry.has(comp.name)) {
        registerComponent(comp.name, (props, children) => {
          // Initialize component state
          (comp.state || []).forEach(stateSpec => {
            const scope = stateSpec.scope || 'local';
            const path = scope === 'local' ? `${comp.name}_${stateSpec.name}` : stateSpec.name;
            registerState(scope, path, stateSpec.initial, stateSpec.persistent);
          });

          // Build context
          const context = {
            componentId: comp.name,
            props,
            slots: {},
            getAction: (name) => (comp.actions || []).find(a => a.name === name)
          };

          // Render view tree
          return renderViewNode(comp.view, context);
        });
      }
    });

    // Apply default theme
    if (uiSpec.default_theme || uiSpec.defaultTheme) {
      const themeName = uiSpec.default_theme || uiSpec.defaultTheme;
      const theme = (uiSpec.themes || []).find(t => t.name === themeName);
      if (theme) applyTheme(theme);
    }

    return {
      mount(container, workspaceName) {
        const workspace = (uiSpec.workspaces || []).find(w => w.name === workspaceName);
        if (!workspace) {
          console.error(`Workspace "${workspaceName}" not found`);
          return;
        }

        // Initialize workspace state
        (workspace.state || []).forEach(stateSpec => {
          registerState('workspace', stateSpec.name, stateSpec.initial, stateSpec.persistent);
        });

        // Render workspace routes
        const defaultRoute = workspace.routes && workspace.routes[0];
        if (defaultRoute) {
          const ComponentFn = componentRegistry.get(defaultRoute.component);
          if (ComponentFn) {
            render(container, () => ComponentFn({}, []));
          }
        }
      },

      navigate(route) {
        window.history.pushState({}, '', route);
        window.dispatchEvent(new CustomEvent('dnr-navigate', { detail: { url: route } }));
      },

      getState,
      setState,
      registerComponent,
      applyTheme
    };
  }

  // Export to global
  global.DNR = {
    createSignal,
    createEffect,
    createMemo,
    createElement,
    render,
    registerComponent,
    getComponent,
    createApp,
    getState,
    setState,
    applyTheme
  };

})(typeof window !== 'undefined' ? window : global);
'''


# =============================================================================
# JavaScript Generator
# =============================================================================


class JSGenerator:
    """
    Generates JavaScript code from UISpec.

    Creates pure JavaScript that can run in any browser without frameworks.
    """

    def __init__(self, spec: UISpec):
        """
        Initialize the generator.

        Args:
            spec: UI specification
        """
        self.spec = spec

    def generate_runtime(self) -> str:
        """
        Get the DNR-UI runtime JavaScript.

        Returns:
            Runtime JavaScript code
        """
        return RUNTIME_JS

    def generate_spec_json(self) -> str:
        """
        Generate JSON representation of the UISpec.

        Returns:
            JSON string
        """
        import json
        return json.dumps(self.spec.model_dump(by_alias=True), indent=2)

    def generate_app_js(self) -> str:
        """
        Generate the application JavaScript.

        Returns:
            JavaScript code that initializes the app
        """
        spec_json = self.generate_spec_json()

        return f'''
// DNR-UI Application - Generated by Dazzle Native Runtime
(function() {{
  'use strict';

  // UISpec data
  const uiSpec = {spec_json};

  // Initialize app on DOM ready
  document.addEventListener('DOMContentLoaded', function() {{
    const app = DNR.createApp(uiSpec);

    // Mount default workspace
    const container = document.getElementById('app') || document.body;
    const defaultWorkspace = uiSpec.default_workspace || uiSpec.defaultWorkspace ||
                            (uiSpec.workspaces && uiSpec.workspaces[0] && uiSpec.workspaces[0].name);

    if (defaultWorkspace) {{
      app.mount(container, defaultWorkspace);
    }}

    // Export app to window for debugging
    window.dnrApp = app;
  }});
}})();
'''

    def generate_html(
        self,
        title: str | None = None,
        include_runtime: bool = True,
    ) -> str:
        """
        Generate a complete HTML page.

        Args:
            title: Page title (defaults to spec name)
            include_runtime: Whether to include runtime inline

        Returns:
            Complete HTML document
        """
        title = title or self.spec.name or "DNR UI"
        runtime_js = self.generate_runtime() if include_runtime else ""
        app_js = self.generate_app_js()

        return f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <style>
    /* DNR-UI Base Styles */
    :root {{
      --color-primary: #0066cc;
      --color-secondary: #6c757d;
      --color-success: #28a745;
      --color-danger: #dc3545;
      --color-warning: #ffc107;
      --color-info: #17a2b8;
      --color-background: #ffffff;
      --color-surface: #f8f9fa;
      --color-text: #212529;
      --color-text-secondary: #6c757d;
      --color-border: #dee2e6;
      --spacing-xs: 4px;
      --spacing-sm: 8px;
      --spacing-md: 16px;
      --spacing-lg: 24px;
      --spacing-xl: 32px;
      --radius-sm: 2px;
      --radius-md: 4px;
      --radius-lg: 8px;
    }}

    * {{
      box-sizing: border-box;
    }}

    body {{
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      margin: 0;
      padding: 0;
      background-color: var(--color-background);
      color: var(--color-text);
      line-height: 1.5;
    }}

    #app {{
      min-height: 100vh;
    }}

    /* DNR Component Styles */
    .dnr-page {{
      padding: var(--spacing-md);
    }}

    .dnr-page-title {{
      margin: 0 0 var(--spacing-md) 0;
      font-size: 1.5rem;
    }}

    .dnr-card {{
      background: var(--color-surface);
      border: 1px solid var(--color-border);
      border-radius: var(--radius-md);
      padding: var(--spacing-md);
      margin-bottom: var(--spacing-md);
    }}

    .dnr-card-title {{
      margin: 0 0 var(--spacing-sm) 0;
      font-size: 1.25rem;
    }}

    .dnr-button {{
      display: inline-flex;
      align-items: center;
      justify-content: center;
      padding: var(--spacing-sm) var(--spacing-md);
      border: 1px solid var(--color-border);
      border-radius: var(--radius-sm);
      background: var(--color-surface);
      color: var(--color-text);
      cursor: pointer;
      font-size: 1rem;
      transition: background-color 0.2s;
    }}

    .dnr-button:hover {{
      background: var(--color-background);
    }}

    .dnr-button-primary {{
      background: var(--color-primary);
      color: white;
      border-color: var(--color-primary);
    }}

    .dnr-button-primary:hover {{
      background: #0056b3;
    }}

    .dnr-input {{
      padding: var(--spacing-sm);
      border: 1px solid var(--color-border);
      border-radius: var(--radius-sm);
      font-size: 1rem;
      width: 100%;
    }}

    .dnr-input:focus {{
      outline: none;
      border-color: var(--color-primary);
    }}

    .dnr-data-table {{
      width: 100%;
      border-collapse: collapse;
    }}

    .dnr-data-table th,
    .dnr-data-table td {{
      padding: var(--spacing-sm);
      text-align: left;
      border-bottom: 1px solid var(--color-border);
    }}

    .dnr-data-table tr:hover {{
      background: var(--color-surface);
    }}

    .dnr-form {{
      display: flex;
      flex-direction: column;
      gap: var(--spacing-md);
    }}

    .dnr-stack {{
      display: flex;
    }}
  </style>
</head>
<body>
  <div id="app"></div>
  <script>
{runtime_js}
  </script>
  <script>
{app_js}
  </script>
</body>
</html>
'''

    def write_to_directory(
        self,
        output_dir: str | Path,
        split_files: bool = True,
    ) -> list[Path]:
        """
        Write generated files to a directory.

        Args:
            output_dir: Output directory path
            split_files: Whether to split into multiple files

        Returns:
            List of created file paths
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        created_files: list[Path] = []

        if split_files:
            # Write runtime
            runtime_path = output_dir / "dnr-runtime.js"
            runtime_path.write_text(self.generate_runtime())
            created_files.append(runtime_path)

            # Write spec
            spec_path = output_dir / "ui-spec.json"
            spec_path.write_text(self.generate_spec_json())
            created_files.append(spec_path)

            # Write app
            app_path = output_dir / "app.js"
            app_path.write_text(self.generate_app_js())
            created_files.append(app_path)

            # Write HTML with script references
            html = self.generate_html(include_runtime=False)
            html = html.replace(
                '<script>\n\n  </script>\n  <script>',
                '<script src="dnr-runtime.js"></script>\n  <script src="app.js">'
            )
            html_path = output_dir / "index.html"
            html_path.write_text(html)
            created_files.append(html_path)
        else:
            # Single HTML file with everything inline
            html_path = output_dir / "index.html"
            html_path.write_text(self.generate_html())
            created_files.append(html_path)

        return created_files


# =============================================================================
# Convenience Functions
# =============================================================================


def generate_js_app(spec: UISpec, output_dir: str | Path) -> list[Path]:
    """
    Generate a complete JavaScript application from UISpec.

    Args:
        spec: UI specification
        output_dir: Output directory

    Returns:
        List of created file paths
    """
    generator = JSGenerator(spec)
    return generator.write_to_directory(output_dir, split_files=True)


def generate_single_html(spec: UISpec) -> str:
    """
    Generate a single HTML file with all code inline.

    Args:
        spec: UI specification

    Returns:
        Complete HTML document
    """
    generator = JSGenerator(spec)
    return generator.generate_html(include_runtime=True)
