"""
JavaScript generator for DNR-UI runtime.

Generates pure JavaScript code from UISpec for browser execution.
No React, no frameworks - just vanilla JS with a minimal runtime.

The JavaScript runtime is maintained in modular files under static/js/.
This module loads and bundles those files via js_loader.py.
"""

from __future__ import annotations

from pathlib import Path

from dazzle_dnr_ui.specs import (
    UISpec,
)

# =============================================================================
# Runtime Loading
# =============================================================================


def _load_runtime_js() -> str:
    """
    Load the runtime JavaScript from modular files.

    The runtime is maintained in static/js/*.js files and loaded via js_loader.
    This ensures a single source of truth for all JavaScript code.

    Raises:
        FileNotFoundError: If the modular JS files are not found
    """
    from dazzle_dnr_ui.runtime.js_loader import get_runtime_js

    return get_runtime_js(use_esm=False, include_realtime=False)


# Lazy-loaded runtime JS (loaded from files on first access)
_RUNTIME_JS_CACHED: str | None = None


def _get_runtime_js() -> str:
    """Get the runtime JS, loading from modular files."""
    global _RUNTIME_JS_CACHED
    if _RUNTIME_JS_CACHED is None:
        _RUNTIME_JS_CACHED = _load_runtime_js()
    return _RUNTIME_JS_CACHED


def get_runtime_js() -> str:
    """
    Get the DNR-UI runtime JavaScript.

    Public function for accessing the runtime JS. Loads from modular
    files in static/js/.

    Returns:
        Runtime JavaScript code

    Raises:
        FileNotFoundError: If the modular JS files are not found
    """
    return _get_runtime_js()


def clear_runtime_cache() -> None:
    """
    Clear the runtime JS cache.

    Call this to force reloading from files (e.g., during development).
    """
    global _RUNTIME_JS_CACHED
    _RUNTIME_JS_CACHED = None

    # Also clear the js_loader cache
    from dazzle_dnr_ui.runtime.js_loader import clear_cache

    clear_cache()


# =============================================================================
# JavaScript Generator
# =============================================================================


class JSGenerator:
    """
    Generates JavaScript code from UISpec.

    Creates pure JavaScript that can run in any browser without frameworks.
    """

    def __init__(self, spec: UISpec):
        """
        Initialize the generator.

        Args:
            spec: UI specification
        """
        self.spec = spec

    def generate_runtime(self) -> str:
        """
        Get the DNR-UI runtime JavaScript.

        Loads from modular files in static/js/.

        Returns:
            Runtime JavaScript code
        """
        return _get_runtime_js()

    def generate_spec_json(self) -> str:
        """
        Generate JSON representation of the UISpec.

        Returns:
            JSON string
        """
        import json

        return json.dumps(self.spec.model_dump(by_alias=True), indent=2)

    def generate_app_js(self) -> str:
        """
        Generate the application JavaScript.

        Returns:
            JavaScript code that initializes the app
        """
        spec_json = self.generate_spec_json()

        return f"""
// DNR-UI Application - Generated by Dazzle Native Runtime
(function() {{
  'use strict';

  // UISpec data
  const uiSpec = {spec_json};

  // Initialize app on DOM ready
  document.addEventListener('DOMContentLoaded', function() {{
    const app = DNR.createApp(uiSpec);

    // Mount default workspace
    const container = document.getElementById('app') || document.body;
    const defaultWorkspace = uiSpec.default_workspace || uiSpec.defaultWorkspace ||
                            (uiSpec.workspaces && uiSpec.workspaces[0] && uiSpec.workspaces[0].name);

    if (defaultWorkspace) {{
      app.mount(container, defaultWorkspace);
    }}

    // Export app to window for debugging
    window.dnrApp = app;
  }});
}})();
"""

    def generate_html(
        self,
        title: str | None = None,
        include_runtime: bool = True,
    ) -> str:
        """
        Generate a complete HTML page.

        Args:
            title: Page title (defaults to spec name)
            include_runtime: Whether to include runtime inline

        Returns:
            Complete HTML document
        """
        title = title or self.spec.name or "DNR UI"
        runtime_js = self.generate_runtime() if include_runtime else ""
        app_js = self.generate_app_js()

        # Load DDT CSS bundle for inline embedding
        ddt_css = self._get_ddt_css()

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <style>
{ddt_css}
  </style>
</head>
<body>
  <div id="app"></div>
  <script>
{runtime_js}
  </script>
  <script>
{app_js}
  </script>
</body>
</html>
"""

    def _get_ddt_css(self) -> str:
        """
        Get the DDT CSS bundle for embedding in HTML.

        Returns:
            Complete CSS string with tokens, components, and utilities.
        """
        try:
            from dazzle_dnr_ui.tokens import generate_css_bundle
            return generate_css_bundle()
        except ImportError:
            # Fallback to minimal styles if tokens module not available
            return self._get_fallback_css()

    def _get_fallback_css(self) -> str:
        """Fallback CSS if DDT module is not available."""
        return """/* DNR-UI Fallback Styles */
:root {
  --dz-color-background-default: #ffffff;
  --dz-color-foreground-default: #0f172a;
  --dz-color-border-default: #e2e8f0;
  --dz-color-intent-primary-default: #3b82f6;
  --dz-space-4: 1rem;
  --dz-space-6: 1.5rem;
  --dz-radius-md: 0.375rem;
  --dz-font-family-base: ui-sans-serif, system-ui, sans-serif;
}

*, *::before, *::after { box-sizing: border-box; }

html {
  font-family: var(--dz-font-family-base);
  color: var(--dz-color-foreground-default);
  background: var(--dz-color-background-default);
}

body { margin: 0; min-height: 100vh; }
#app { min-height: 100vh; padding: var(--dz-space-6); }

.dz-page { padding: var(--dz-space-6); }
.dz-button {
  padding: var(--dz-space-4);
  border: 1px solid var(--dz-color-border-default);
  border-radius: var(--dz-radius-md);
  cursor: pointer;
}
.dz-button--primary {
  background: var(--dz-color-intent-primary-default);
  color: white;
  border-color: var(--dz-color-intent-primary-default);
}
.dz-input {
  padding: var(--dz-space-4);
  border: 1px solid var(--dz-color-border-default);
  border-radius: var(--dz-radius-md);
  width: 100%;
}
.dz-table { width: 100%; border-collapse: collapse; }
.dz-table th, .dz-table td {
  padding: var(--dz-space-4);
  border-bottom: 1px solid var(--dz-color-border-default);
  text-align: left;
}
"""

    def write_to_directory(
        self,
        output_dir: str | Path,
        split_files: bool = True,
    ) -> list[Path]:
        """
        Write generated files to a directory.

        Args:
            output_dir: Output directory path
            split_files: Whether to split into multiple files

        Returns:
            List of created file paths
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        created_files: list[Path] = []

        if split_files:
            # Write runtime
            runtime_path = output_dir / "dnr-runtime.js"
            runtime_path.write_text(self.generate_runtime())
            created_files.append(runtime_path)

            # Write spec
            spec_path = output_dir / "ui-spec.json"
            spec_path.write_text(self.generate_spec_json())
            created_files.append(spec_path)

            # Write app
            app_path = output_dir / "app.js"
            app_path.write_text(self.generate_app_js())
            created_files.append(app_path)

            # Write HTML with script references
            html = self.generate_html(include_runtime=False)
            html = html.replace(
                "<script>\n\n  </script>\n  <script>",
                '<script src="dnr-runtime.js"></script>\n  <script src="app.js"></script>\n  <script>',
            )
            # Remove the now-empty inline script that follows
            html = html.replace(
                '<script src="app.js"></script>\n  <script>\n\n  </script>',
                '<script src="app.js"></script>',
            )
            html_path = output_dir / "index.html"
            html_path.write_text(html)
            created_files.append(html_path)
        else:
            # Single HTML file with everything inline
            html_path = output_dir / "index.html"
            html_path.write_text(self.generate_html())
            created_files.append(html_path)

        return created_files


# =============================================================================
# Convenience Functions
# =============================================================================


def generate_js_app(spec: UISpec, output_dir: str | Path) -> list[Path]:
    """
    Generate a complete JavaScript application from UISpec.

    Args:
        spec: UI specification
        output_dir: Output directory

    Returns:
        List of created file paths
    """
    generator = JSGenerator(spec)
    return generator.write_to_directory(output_dir, split_files=True)


def generate_single_html(spec: UISpec) -> str:
    """
    Generate a single HTML file with all code inline.

    Args:
        spec: UI specification

    Returns:
        Complete HTML document
    """
    generator = JSGenerator(spec)
    return generator.generate_html(include_runtime=True)
