"""
JavaScript loader for DNR-UI runtime.

Loads JavaScript modules from static files and bundles them for different use cases.
This approach keeps JavaScript code maintainable in separate files while allowing
the Python generators to include them inline when needed.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

# =============================================================================
# Path Configuration
# =============================================================================

# Get the directory containing this file
_RUNTIME_DIR = Path(__file__).parent
_STATIC_JS_DIR = _RUNTIME_DIR / "static" / "js"


# =============================================================================
# Module Loading
# =============================================================================

# Order matters for IIFE bundle - dependencies must come first
_MODULE_ORDER = [
    "signals.js",
    "state.js",
    "api-client.js",
    "toast.js",
    "dom.js",
    "bindings.js",
    "components.js",
    "renderer.js",
    "actions.js",
    "theme.js",
    "shell.js",
    "app.js",
]


@lru_cache(maxsize=32)
def load_js_module(name: str) -> str:
    """
    Load a single JavaScript module by name.

    Args:
        name: Module filename (e.g., "signals.js")

    Returns:
        JavaScript source code

    Raises:
        FileNotFoundError: If module doesn't exist
    """
    path = _STATIC_JS_DIR / name
    if not path.exists():
        raise FileNotFoundError(f"JavaScript module not found: {path}")
    return path.read_text(encoding="utf-8")


def load_js_modules(names: list[str] | None = None) -> dict[str, str]:
    """
    Load multiple JavaScript modules.

    Args:
        names: List of module names, or None for all modules

    Returns:
        Dict mapping module name to source code
    """
    if names is None:
        names = _MODULE_ORDER
    return {name: load_js_module(name) for name in names}


# =============================================================================
# Bundle Generation
# =============================================================================


def generate_iife_bundle(include_realtime: bool = False) -> str:
    """
    Generate an IIFE (Immediately Invoked Function Expression) bundle.

    This creates a single JavaScript bundle that works in browsers without
    ES module support. All modules are concatenated and wrapped in an IIFE,
    with exports attached to the global `DNR` object.

    Args:
        include_realtime: Whether to include realtime client

    Returns:
        Complete JavaScript bundle as IIFE
    """
    # Load all core modules
    modules = load_js_modules()

    # Convert ES modules to IIFE-compatible code
    bundle_parts = [
        "/**",
        " * DNR-UI Runtime - Minimal reactive UI runtime",
        " * Generated by Dazzle Native Runtime",
        " * Version: 0.4.0 (Behaviour Layer Complete)",
        " */",
        "(function(global) {",
        "  'use strict';",
        "",
    ]

    # Add each module, stripping imports/exports
    for name in _MODULE_ORDER:
        if name in modules:
            source = _convert_to_iife_compatible(modules[name], name)
            bundle_parts.append(f"  // === {name} ===")
            bundle_parts.append(source)
            bundle_parts.append("")

    # Add realtime if requested
    if include_realtime:
        try:
            realtime_source = load_js_module("realtime.js")
            realtime_source = _convert_to_iife_compatible(realtime_source, "realtime.js")
            bundle_parts.append("  // === realtime.js ===")
            bundle_parts.append(realtime_source)
            bundle_parts.append("")
        except FileNotFoundError:
            pass

    # Add global export
    bundle_parts.extend(
        [
            "  // Export to global",
            "  global.DNR = {",
            "    // Signals & Reactivity",
            "    createSignal,",
            "    createEffect,",
            "    createMemo,",
            "    createResource,",
            "    batch,",
            "",
            "    // State Management",
            "    getState,",
            "    setState,",
            "    updateState,",
            "    registerState,",
            "    globalLoading,",
            "    globalError,",
            "    notifications,",
            "",
            "    // DOM",
            "    createElement,",
            "    render,",
            "",
            "    // Components",
            "    registerComponent,",
            "    getComponent,",
            "",
            "    // Actions & Effects",
            "    registerAction,",
            "    dispatch,",
            "    executeAction,",
            "    executeEffect,",
            "",
            "    // Notifications",
            "    showToast,",
            "",
            "    // API Client",
            "    api: apiClient,",
            "",
            "    // Theme",
            "    applyTheme,",
            "",
            "    // Shell",
            "    createShell,",
            "    updateActiveNav,",
            "",
            "    // App",
            "    createApp",
            "  };",
        ]
    )

    if include_realtime:
        bundle_parts.extend(
            [
                "",
                "  // Add realtime exports",
                '  if (typeof RealtimeClient !== "undefined") {',
                "    global.DNR.Realtime = {",
                "      RealtimeClient,",
                "      OptimisticManager,",
                "      PresenceManager,",
                "      EntitySync,",
                "      createRealtimeClient",
                "    };",
                "    global.DNR.createRealtimeClient = createRealtimeClient;",
                "  }",
            ]
        )

    bundle_parts.extend(
        [
            "",
            "})(typeof window !== 'undefined' ? window : global);",
        ]
    )

    return "\n".join(bundle_parts)


def _convert_to_iife_compatible(source: str, module_name: str) -> str:
    """
    Convert ES module source to IIFE-compatible code.

    Strips import/export statements and adjusts code for IIFE context.

    Args:
        source: ES module source code
        module_name: Name of the module (for comments)

    Returns:
        IIFE-compatible JavaScript code
    """
    import re

    # First, remove multi-line export blocks: export { ... };
    # This handles cases like:
    #   export {
    #     foo,
    #     bar,
    #     baz
    #   };
    source = re.sub(r"export\s*\{[^}]*\}\s*;?", "", source, flags=re.DOTALL)

    lines = source.split("\n")
    result = []

    for line in lines:
        stripped = line.strip()

        # Skip import statements
        if stripped.startswith("import "):
            continue

        # Convert export statements
        if stripped.startswith("export "):
            # export function foo() -> function foo()
            # export const foo = -> const foo =
            # export class Foo -> class Foo
            # export default -> skip or handle
            if stripped.startswith("export default"):
                continue
            line = line.replace("export ", "", 1)

        # Indent for IIFE wrapper
        if line.strip():
            result.append("  " + line)
        else:
            result.append("")

    return "\n".join(result)


# =============================================================================
# ES Module Bundle
# =============================================================================


def generate_esm_bundle(include_realtime: bool = False) -> str:
    """
    Generate an ES module bundle.

    This creates a bundle using ES module syntax, suitable for modern
    browsers with `<script type="module">`.

    Args:
        include_realtime: Whether to include realtime client

    Returns:
        Complete JavaScript bundle as ES module
    """
    modules = load_js_modules()

    bundle_parts = [
        "/**",
        " * DNR-UI Runtime - ES Module Bundle",
        " * Generated by Dazzle Native Runtime",
        " * Version: 0.4.0",
        " */",
        "",
    ]

    # Simply concatenate all modules (they have proper import/export)
    for name in _MODULE_ORDER:
        if name in modules:
            bundle_parts.append(f"// === {name} ===")
            bundle_parts.append(modules[name])
            bundle_parts.append("")

    if include_realtime:
        try:
            realtime_source = load_js_module("realtime.js")
            bundle_parts.append("// === realtime.js ===")
            bundle_parts.append(realtime_source)
            bundle_parts.append("")
        except FileNotFoundError:
            pass

    return "\n".join(bundle_parts)


# =============================================================================
# Convenience Functions
# =============================================================================


def get_runtime_js(use_esm: bool = False, include_realtime: bool = False) -> str:
    """
    Get the complete runtime JavaScript.

    Args:
        use_esm: Whether to use ES module format
        include_realtime: Whether to include realtime client

    Returns:
        Complete JavaScript runtime code
    """
    if use_esm:
        return generate_esm_bundle(include_realtime=include_realtime)
    return generate_iife_bundle(include_realtime=include_realtime)


def get_realtime_js() -> str:
    """
    Get just the realtime client JavaScript.

    Returns:
        Realtime client JavaScript code
    """
    return load_js_module("realtime.js")


def clear_cache() -> None:
    """Clear the module loading cache."""
    load_js_module.cache_clear()
