"""
Vite project generator for DNR-UI runtime.

Generates a Vite-bundled application from UISpec while keeping
the pure JavaScript, no-framework approach.
"""

from __future__ import annotations

import json
from pathlib import Path

# =============================================================================
# ES Module Runtime Templates
# =============================================================================
# =============================================================================
# Runtime File Loading
# =============================================================================
# Instead of duplicating JS/CSS code as template strings (which causes drift),
# we load from the canonical source files in static/js/ and static/css/.
#
# The static/js/*.js files are ES modules that work directly with Vite.
# The static/css/*.css files provide the design token system (DDT).
# This ensures vite_generator always uses the latest runtime code.
from pathlib import Path as _Path

from dazzle_dnr_ui.specs import UISpec

_STATIC_DIR = _Path(__file__).parent / "static"
_STATIC_JS_DIR = _STATIC_DIR / "js"
_STATIC_CSS_DIR = _STATIC_DIR / "css"


def _load_static_file(subdir: str, filename: str) -> str:
    """Load a file from a static subdirectory."""
    path = _STATIC_DIR / subdir / filename
    if not path.exists():
        raise FileNotFoundError(f"Static file not found: {path}")
    return path.read_text(encoding="utf-8")


def _load_static_js(filename: str) -> str:
    """Load a JavaScript file from the static/js directory."""
    return _load_static_file("js", filename)


def _load_static_css(filename: str) -> str:
    """Load a CSS file from the static/css directory."""
    return _load_static_file("css", filename)


# Mapping from Vite project filenames to static source files
_VITE_TO_STATIC_MAPPING = {
    "signals.js": "signals.js",
    "state.js": "state.js",
    "dom.js": "dom.js",
    "bindings.js": "bindings.js",
    "components.js": "components.js",
    "renderer.js": "renderer.js",
    "theme.js": "theme.js",
    "actions.js": "actions.js",
    "shell.js": "shell.js",
    "app.js": "app.js",
    "index.js": "index.js",
}


def _get_runtime_files() -> dict[str, str]:
    """
    Load all runtime JS files from static/js/.

    Returns:
        Dict mapping output filename to file content
    """
    return {
        vite_name: _load_static_js(static_name)
        for vite_name, static_name in _VITE_TO_STATIC_MAPPING.items()
    }


# CSS source files to concatenate for the bundled stylesheet
# With DaisyUI loaded via CDN, we only need the thin DAZZLE semantic layer
_CSS_SOURCE_FILES = [
    "dazzle-layer.css",  # Semantic aliases on top of DaisyUI + Tailwind
]


def _get_bundled_css() -> str:
    """
    Load and concatenate CSS files from static/css/.

    With DaisyUI loaded via CDN, this only includes the thin DAZZLE
    semantic layer that provides app structure and semantic aliases.

    Returns:
        CSS content for the DAZZLE semantic layer
    """
    parts = [
        "/* =============================================================================",
        "   DAZZLE Semantic Layer",
        "   Thin aliases on top of DaisyUI (loaded via CDN) + Tailwind",
        "   DO NOT EDIT - regenerate using dazzle init or dazzle dnr serve",
        "   ============================================================================= */",
        "",
    ]
    for filename in _CSS_SOURCE_FILES:
        parts.append(f"/* --- {filename} --- */")
        parts.append(_load_static_css(filename))
        parts.append("")
    return "\n".join(parts)

# =============================================================================
# Configuration Templates
# =============================================================================

VITE_CONFIG_JS = """import { defineConfig } from 'vite';

// API URL from environment variable or default to localhost
// In Docker, set VITE_API_URL=http://host.docker.internal:8000
const apiTarget = process.env.VITE_API_URL || 'http://localhost:8000';

export default defineConfig({
  root: 'src',
  build: {
    outDir: '../dist',
    emptyOutDir: true,
    sourcemap: true,
  },
  server: {
    port: 3000,
    host: true,  // Listen on 0.0.0.0 for Docker access
    proxy: {
      '/api': {
        target: apiTarget,
        changeOrigin: true,
      }
    }
  },
  resolve: {
    alias: {
      '@dnr': '/dnr'
    }
  }
});
"""

PACKAGE_JSON_TEMPLATE = """{{
  "name": "{name}",
  "version": "1.0.0",
  "description": "DNR-UI Application - Generated by Dazzle",
  "type": "module",
  "scripts": {{
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "serve": "vite preview --port 3000"
  }},
  "devDependencies": {{
    "vite": "^5.0.0"
  }}
}}
"""

INDEX_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <!-- DaisyUI - semantic component classes (42kB gzipped) -->
  <link href="https://cdn.jsdelivr.net/npm/daisyui@5/daisyui.css" rel="stylesheet" type="text/css" />
  <!-- Tailwind Browser - minimal utilities for layout -->
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
  <!-- DAZZLE semantic layer -->
  <link rel="stylesheet" href="/styles/dnr.css">
</head>
<body class="bg-base-200 min-h-screen">
  <div id="app"></div>
  <script type="module" src="/main.js"></script>
</body>
</html>
"""

MAIN_JS_TEMPLATE = """/**
 * Application Entry Point
 * Generated by Dazzle Native Runtime
 */

import { createApp } from '@dnr/app.js';
import uiSpec from './ui-spec.json';

// Initialize app on DOM ready
document.addEventListener('DOMContentLoaded', () => {
  const app = createApp(uiSpec);

  // Get the app root element
  // Shell rendering (nav, header, footer) is handled by createShell() in app.js
  const appRoot = document.getElementById('app') || document.body;
  appRoot.classList.add('dz-app');

  // Mount default workspace - shell creates the layout structure
  const defaultWorkspace = uiSpec.default_workspace || uiSpec.defaultWorkspace ||
                          (uiSpec.workspaces?.[0]?.name);

  if (defaultWorkspace) {
    app.mount(appRoot, defaultWorkspace);
  }

  // Export app for debugging
  window.dnrApp = app;
});
"""

# Note: DNR_CSS has been removed. CSS is now loaded dynamically from static/css/
# using _get_bundled_css() to ensure a single source of truth.


# =============================================================================
# Vite Project Generator
# =============================================================================


class ViteGenerator:
    """
    Generates a Vite-bundled application from UISpec.

    Creates a complete project with:
    - ES module runtime
    - Vite configuration
    - Package.json
    - Source files
    """

    def __init__(self, spec: UISpec):
        """
        Initialize the generator.

        Args:
            spec: UI specification
        """
        self.spec = spec

    def generate_package_json(self) -> str:
        """Generate package.json content."""
        name = self.spec.name or "dnr-app"
        # Sanitize name for npm
        name = name.lower().replace(" ", "-").replace("_", "-")
        return PACKAGE_JSON_TEMPLATE.format(name=name)

    def generate_vite_config(self) -> str:
        """Generate vite.config.js content."""
        return VITE_CONFIG_JS

    def generate_index_html(self) -> str:
        """Generate index.html content."""
        title = self.spec.name or "DNR UI"
        return INDEX_HTML_TEMPLATE.format(title=title)

    def generate_main_js(self) -> str:
        """Generate main.js entry point."""
        return MAIN_JS_TEMPLATE

    def generate_spec_json(self) -> str:
        """Generate UI spec as JSON."""
        return json.dumps(self.spec.model_dump(by_alias=True), indent=2)

    def write_to_directory(
        self,
        output_dir: str | Path,
    ) -> list[Path]:
        """
        Write complete Vite project to a directory.

        Args:
            output_dir: Output directory path

        Returns:
            List of created file paths
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        created_files: list[Path] = []

        # Write root files
        package_json = output_dir / "package.json"
        package_json.write_text(self.generate_package_json())
        created_files.append(package_json)

        vite_config = output_dir / "vite.config.js"
        vite_config.write_text(self.generate_vite_config())
        created_files.append(vite_config)

        # Create src directory
        src_dir = output_dir / "src"
        src_dir.mkdir(exist_ok=True)

        # Write HTML
        index_html = src_dir / "index.html"
        index_html.write_text(self.generate_index_html())
        created_files.append(index_html)

        # Write main.js
        main_js = src_dir / "main.js"
        main_js.write_text(self.generate_main_js())
        created_files.append(main_js)

        # Write UI spec
        spec_json = src_dir / "ui-spec.json"
        spec_json.write_text(self.generate_spec_json())
        created_files.append(spec_json)

        # Create styles directory
        styles_dir = src_dir / "styles"
        styles_dir.mkdir(exist_ok=True)

        # Write CSS (loaded from static/css/ source files)
        css_file = styles_dir / "dnr.css"
        css_file.write_text(_get_bundled_css())
        created_files.append(css_file)

        # Create DNR runtime directory
        dnr_dir = src_dir / "dnr"
        dnr_dir.mkdir(exist_ok=True)

        # Write ES module runtime files (loaded from static/js/ source files)
        runtime_files = _get_runtime_files()

        for filename, content in runtime_files.items():
            file_path = dnr_dir / filename
            file_path.write_text(content)
            created_files.append(file_path)

        return created_files

    def write_runtime_only(
        self,
        output_dir: str | Path,
    ) -> list[Path]:
        """
        Write only the ES module runtime files (for integration into existing projects).

        Args:
            output_dir: Output directory path

        Returns:
            List of created file paths
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        created_files: list[Path] = []

        # Load runtime files from static/js/ source
        runtime_files = _get_runtime_files()

        for filename, content in runtime_files.items():
            file_path = output_dir / filename
            file_path.write_text(content)
            created_files.append(file_path)

        return created_files


# =============================================================================
# Convenience Functions
# =============================================================================


def generate_vite_app(spec: UISpec, output_dir: str | Path) -> list[Path]:
    """
    Generate a complete Vite application from UISpec.

    Args:
        spec: UI specification
        output_dir: Output directory

    Returns:
        List of created file paths
    """
    generator = ViteGenerator(spec)
    return generator.write_to_directory(output_dir)


def generate_es_modules(spec: UISpec, output_dir: str | Path) -> list[Path]:
    """
    Generate only the ES module runtime files.

    Args:
        spec: UI specification (not used, but kept for API consistency)
        output_dir: Output directory

    Returns:
        List of created file paths
    """
    generator = ViteGenerator(spec)
    return generator.write_runtime_only(output_dir)
