"""
Tier 2 Playwright E2E Tests for simple_task.

Auto-generated by Dazzle tier2_playwright generator.
These tests use the semantic DOM contract (data-dazzle-* attributes)
for reliable, stack-agnostic element selection.

Usage:
    pytest tests/e2e/test_tier2_generated.py -m tier2 --base-url http://localhost:3000

With scenario seeding:
    Tests that specify a scenario will automatically seed data
    via the Dazzle Bar before executing.

Note:
    The base_url is provided by pytest-playwright. Set via:
    - --base-url flag: pytest --base-url http://localhost:3000
    - Environment: export PLAYWRIGHT_BASE_URL=http://localhost:3000
"""

from __future__ import annotations

import pytest
from playwright.sync_api import Page, expect

# =============================================================================
# Helper: expect count greater than
# =============================================================================


def _expect_count_greater_than(locator, count: int, timeout: int = 5000):
    """Assert that a locator matches more than `count` elements."""
    import time

    start = time.time()
    while time.time() - start < timeout / 1000:
        if locator.count() > count:
            return
        time.sleep(0.1)
    raise AssertionError(f"Expected more than {count} elements, got {locator.count()}")


# Monkey-patch for convenience
expect.count_greater_than = lambda loc, n: _expect_count_greater_than(loc, n)


# =============================================================================
# Generated Tests
# =============================================================================


@pytest.mark.tier2
@pytest.mark.playwright
@pytest.mark.crud
@pytest.mark.list
@pytest.mark.task
def test_task_list_list(page: Page, base_url: str) -> None:
    """
    View list of Task records via Task List

    Tags: tier2, playwright, crud, list, task
    """
    # Navigate to app to access Dazzle Bar
    page.goto(base_url)
    page.wait_for_load_state("networkidle")
    # Set scenario to 'busy_sprint' via Dazzle Bar
    page.locator('[data-dazzle-control="scenario-select"]').select_option("busy_sprint")
    page.wait_for_load_state("networkidle")
    # Navigate to Task List
    page.goto(f"{base_url}/task")
    page.wait_for_load_state("networkidle")
    # Assert Task table is visible
    expect(page.locator('[data-dazzle-table="Task"]')).to_be_visible()
    # Assert seeded data rows are visible
    _expect_count_greater_than(page.locator('[data-dazzle-table="Task"] [data-dazzle-row]'), 0)


@pytest.mark.tier2
@pytest.mark.playwright
@pytest.mark.crud
@pytest.mark.view
@pytest.mark.task
def test_task_detail_view(page: Page, base_url: str) -> None:
    """
    View a single Task record via Task Detail

    Tags: tier2, playwright, crud, view, task
    """
    # Navigate to app to access Dazzle Bar
    page.goto(base_url)
    page.wait_for_load_state("networkidle")
    # Set scenario to 'busy_sprint' via Dazzle Bar
    page.locator('[data-dazzle-control="scenario-select"]').select_option("busy_sprint")
    page.wait_for_load_state("networkidle")
    # Navigate to list view first
    page.goto(f"{base_url}/task")
    page.wait_for_load_state("networkidle")
    # Click first row to view details
    page.locator('[data-dazzle-table="Task"] [data-dazzle-row]:first-child').click()
    page.wait_for_load_state("networkidle")
    # Assert Task Detail view is visible
    expect(page.locator('[data-dazzle-view="task_detail"]')).to_be_visible()


@pytest.mark.tier2
@pytest.mark.high_priority
@pytest.mark.playwright
@pytest.mark.crud
@pytest.mark.create
@pytest.mark.task
def test_task_create_create(page: Page, base_url: str) -> None:
    """
    Create a new Task via Create Task

    Tags: tier2, playwright, crud, create, task
    """
    # Navigate to Create Task
    page.goto(f"{base_url}/task/create")
    page.wait_for_load_state("networkidle")
    # Assert create form is visible
    expect(
        page.locator('[data-dazzle-form="Task"][data-dazzle-form-mode="create"]')
    ).to_be_visible()
    # Fill title field
    page.locator('[data-dazzle-form="Task"] [data-dazzle-field="Task.title"]').fill("Test Title")
    # Fill description field
    page.locator('[data-dazzle-form="Task"] [data-dazzle-field="Task.description"]').fill(
        "Sample text for description"
    )
    # Select low for priority field
    page.locator('[data-dazzle-form="Task"] [data-dazzle-field="Task.priority"]').select_option(
        "low"
    )
    # Fill due_date field
    page.locator('[data-dazzle-form="Task"] [data-dazzle-field="Task.due_date"]').fill("2025-01-15")
    # Click create/submit button
    page.locator(
        '[data-dazzle-action="Task.create"], [data-dazzle-action-role="primary"]'
    ).first.click()
    page.wait_for_load_state("networkidle")
    # Assert redirected to list or table visible
    expect(
        page.locator('[data-dazzle-table="Task"], [data-dazzle-view="task_list"]')
    ).to_be_visible(timeout=5000)


@pytest.mark.tier2
@pytest.mark.high_priority
@pytest.mark.playwright
@pytest.mark.crud
@pytest.mark.edit
@pytest.mark.task
def test_task_edit_edit(page: Page, base_url: str) -> None:
    """
    Edit a Task record via Edit Task

    Tags: tier2, playwright, crud, edit, task
    """
    # Navigate to app to access Dazzle Bar
    page.goto(base_url)
    page.wait_for_load_state("networkidle")
    # Set scenario to 'busy_sprint' via Dazzle Bar
    page.locator('[data-dazzle-control="scenario-select"]').select_option("busy_sprint")
    page.wait_for_load_state("networkidle")
    # Navigate to list view
    page.goto(f"{base_url}/task")
    page.wait_for_load_state("networkidle")
    # Click edit on first row
    page.locator(
        '[data-dazzle-table="Task"] [data-dazzle-row]:first-child [data-dazzle-action="Task.edit"]'
    ).click()
    page.wait_for_load_state("networkidle")
    # Assert edit form is visible
    expect(page.locator('[data-dazzle-form="Task"][data-dazzle-form-mode="edit"]')).to_be_visible()
    # Update title field
    page.locator('[data-dazzle-form="Task"] [data-dazzle-field="Task.title"]').fill("Updated value")
    # Click save/update button
    page.locator(
        '[data-dazzle-action="Task.save"], [data-dazzle-action="Task.update"], [data-dazzle-action-role="primary"]'
    ).first.click()
    page.wait_for_load_state("networkidle")


@pytest.mark.tier2
@pytest.mark.playwright
@pytest.mark.crud
@pytest.mark.list
@pytest.mark.user
def test_user_list_list(page: Page, base_url: str) -> None:
    """
    View list of User records via Team Members

    Tags: tier2, playwright, crud, list, user
    """
    # Navigate to app to access Dazzle Bar
    page.goto(base_url)
    page.wait_for_load_state("networkidle")
    # Set scenario to 'busy_sprint' via Dazzle Bar
    page.locator('[data-dazzle-control="scenario-select"]').select_option("busy_sprint")
    page.wait_for_load_state("networkidle")
    # Navigate to Team Members
    page.goto(f"{base_url}/user")
    page.wait_for_load_state("networkidle")
    # Assert User table is visible
    expect(page.locator('[data-dazzle-table="User"]')).to_be_visible()
    # Assert seeded data rows are visible
    _expect_count_greater_than(page.locator('[data-dazzle-table="User"] [data-dazzle-row]'), 0)


@pytest.mark.tier2
@pytest.mark.high_priority
@pytest.mark.playwright
@pytest.mark.crud
@pytest.mark.create
@pytest.mark.user
def test_user_create_create(page: Page, base_url: str) -> None:
    """
    Create a new User via Add Team Member

    Tags: tier2, playwright, crud, create, user
    """
    # Navigate to Add Team Member
    page.goto(f"{base_url}/user/create")
    page.wait_for_load_state("networkidle")
    # Assert create form is visible
    expect(
        page.locator('[data-dazzle-form="User"][data-dazzle-form-mode="create"]')
    ).to_be_visible()
    # Fill name field
    page.locator('[data-dazzle-form="User"] [data-dazzle-field="User.name"]').fill("Test Name")
    # Fill email field
    page.locator('[data-dazzle-form="User"] [data-dazzle-field="User.email"]').fill("Test Email")
    # Select admin for role field
    page.locator('[data-dazzle-form="User"] [data-dazzle-field="User.role"]').select_option("admin")
    # Fill department field
    page.locator('[data-dazzle-form="User"] [data-dazzle-field="User.department"]').fill(
        "Test Department"
    )
    # Click create/submit button
    page.locator(
        '[data-dazzle-action="User.create"], [data-dazzle-action-role="primary"]'
    ).first.click()
    page.wait_for_load_state("networkidle")
    # Assert redirected to list or table visible
    expect(
        page.locator('[data-dazzle-table="User"], [data-dazzle-view="user_list"]')
    ).to_be_visible(timeout=5000)


@pytest.mark.tier2
@pytest.mark.high_priority
@pytest.mark.playwright
@pytest.mark.crud
@pytest.mark.delete
@pytest.mark.task
def test_task_delete(page: Page, base_url: str) -> None:
    """
    Delete a Task record

    Tags: tier2, playwright, crud, delete, task
    """
    # Navigate to app to access Dazzle Bar
    page.goto(base_url)
    page.wait_for_load_state("networkidle")
    # Set scenario to 'busy_sprint' via Dazzle Bar
    page.locator('[data-dazzle-control="scenario-select"]').select_option("busy_sprint")
    page.wait_for_load_state("networkidle")
    # Navigate to list view
    page.goto(f"{base_url}/task")
    page.wait_for_load_state("networkidle")
    # Count rows before delete
    initial_count = page.locator('[data-dazzle-table="Task"] [data-dazzle-row]').count()
    # Click delete on first row
    page.locator(
        '[data-dazzle-table="Task"] [data-dazzle-row]:first-child [data-dazzle-action="Task.delete"], [data-dazzle-table="Task"] [data-dazzle-row]:first-child [data-dazzle-action-role="destructive"]'
    ).first.click()
    page.wait_for_load_state("networkidle")
    # Confirm delete if dialog appears
    if page.locator("[data-dazzle-dialog]").is_visible():
        page.locator('[data-dazzle-dialog] [data-dazzle-action-role="destructive"]').click()
        page.wait_for_load_state("networkidle")
    # Assert row count decreased by 1
    expect(page.locator('[data-dazzle-table="Task"] [data-dazzle-row]')).to_have_count(
        initial_count - 1
    )


@pytest.mark.tier2
@pytest.mark.high_priority
@pytest.mark.playwright
@pytest.mark.crud
@pytest.mark.delete
@pytest.mark.user
def test_user_delete(page: Page, base_url: str) -> None:
    """
    Delete a User record

    Tags: tier2, playwright, crud, delete, user
    """
    # Navigate to app to access Dazzle Bar
    page.goto(base_url)
    page.wait_for_load_state("networkidle")
    # Set scenario to 'busy_sprint' via Dazzle Bar
    page.locator('[data-dazzle-control="scenario-select"]').select_option("busy_sprint")
    page.wait_for_load_state("networkidle")
    # Navigate to list view
    page.goto(f"{base_url}/user")
    page.wait_for_load_state("networkidle")
    # Count rows before delete
    initial_count = page.locator('[data-dazzle-table="User"] [data-dazzle-row]').count()
    # Click delete on first row
    page.locator(
        '[data-dazzle-table="User"] [data-dazzle-row]:first-child [data-dazzle-action="User.delete"], [data-dazzle-table="User"] [data-dazzle-row]:first-child [data-dazzle-action-role="destructive"]'
    ).first.click()
    page.wait_for_load_state("networkidle")
    # Confirm delete if dialog appears
    if page.locator("[data-dazzle-dialog]").is_visible():
        page.locator('[data-dazzle-dialog] [data-dazzle-action-role="destructive"]').click()
        page.wait_for_load_state("networkidle")
    # Assert row count decreased by 1
    expect(page.locator('[data-dazzle-table="User"] [data-dazzle-row]')).to_have_count(
        initial_count - 1
    )
