"""
Settings generator for Django Micro backend.

Generates Django settings.py and other Django configuration files.
"""

import secrets
from pathlib import Path

from ....core import ir
from ...base import Generator, GeneratorResult


class SettingsGenerator(Generator):
    """
    Generate Django project configuration files.

    Creates:
    - settings.py - Django settings
    - wsgi.py - WSGI configuration
    - asgi.py - ASGI configuration
    - manage.py - Django management script
    """

    def __init__(
        self, spec: ir.AppSpec, output_dir: Path, project_name: str, app_name: str = "app"
    ):
        """
        Initialize settings generator.

        Args:
            spec: Application specification
            output_dir: Root output directory
            project_name: Name of the Django project
            app_name: Name of the Django app
        """
        super().__init__(spec, output_dir)
        self.project_name = project_name
        self.app_name = app_name

    def generate(self) -> GeneratorResult:
        """Generate Django configuration files."""
        result = GeneratorResult()

        # Generate settings.py
        settings_code = self._generate_settings()
        settings_path = self.output_dir / self.project_name / "settings.py"
        self._write_file(settings_path, settings_code)
        result.add_file(settings_path)

        # Generate wsgi.py
        wsgi_code = self._generate_wsgi()
        wsgi_path = self.output_dir / self.project_name / "wsgi.py"
        self._write_file(wsgi_path, wsgi_code)
        result.add_file(wsgi_path)

        # Generate asgi.py
        asgi_code = self._generate_asgi()
        asgi_path = self.output_dir / self.project_name / "asgi.py"
        self._write_file(asgi_path, asgi_code)
        result.add_file(asgi_path)

        # Generate manage.py (at project root, not app root)
        manage_code = self._generate_manage_py()
        manage_path = self.output_dir / "manage.py"
        self._write_file(manage_path, manage_code)
        result.add_file(manage_path)

        # Generate __init__.py for project
        init_path = self.output_dir / self.project_name / "__init__.py"
        self._write_file(init_path, "")
        result.add_file(init_path)

        # Generate secret key as artifact
        secret_key = secrets.token_urlsafe(50)
        result.add_artifact("secret_key", secret_key)

        return result

    def _generate_settings(self) -> str:
        """Generate Django settings.py."""
        secret_key = secrets.token_urlsafe(50)

        return f'''"""
Django settings for {self.project_name} project.

Generated by DAZZLE.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '{secret_key}'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    '{self.app_name}',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '{self.project_name}.urls'

TEMPLATES = [
    {{
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {{
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        }},
    }},
]

WSGI_APPLICATION = '{self.project_name}.wsgi.application'


# Database
# https://docs.djangoproject.com/en/stable/ref/settings/#databases

DATABASES = {{
    'default': {{
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }}
}}


# Password validation
# https://docs.djangoproject.com/en/stable/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {{
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    }},
    {{
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    }},
    {{
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    }},
    {{
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    }},
]


# Internationalization
# https://docs.djangoproject.com/en/stable/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/stable/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / '{self.app_name}' / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/stable/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
'''

    def _generate_wsgi(self) -> str:
        """Generate WSGI configuration."""
        return f'''"""
WSGI config for {self.project_name} project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/stable/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', '{self.project_name}.settings')

application = get_wsgi_application()
'''

    def _generate_asgi(self) -> str:
        """Generate ASGI configuration."""
        return f'''"""
ASGI config for {self.project_name} project.

It exposes the ASGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/stable/howto/deployment/asgi/
"""

import os

from django.core.asgi import get_asgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', '{self.project_name}.settings')

application = get_asgi_application()
'''

    def _generate_manage_py(self) -> str:
        """Generate manage.py script."""
        return f'''#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys


def main():
    """Run administrative tasks."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', '{self.project_name}.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()
'''
