"""RBAC compliance report generator.

Generates human-readable compliance reports from VerificationReport instances.
Cites NIST SP 800-162, Saltzer & Schroeder (1975), and ISO 27001 in the
methodology section.
"""

from typing import TYPE_CHECKING

from dazzle.rbac.verifier import CellResult, VerificationReport

if TYPE_CHECKING:
    from dazzle.rbac.access_evidence import AccessReview

# Decision glyphs used in the access matrix table.
_CELL_GLYPH: dict[CellResult, str] = {
    CellResult.PASS: "PASS",
    CellResult.VIOLATION: "**VIOLATION**",
    CellResult.WARNING: "_WARNING_",
}


def _render_summary(report: VerificationReport) -> list[str]:
    lines = [
        "## Summary",
        "",
        f"- **Application**: {report.app_name}",
        f"- **Timestamp**: {report.timestamp}",
        f"- **Dazzle version**: {report.dazzle_version}",
    ]
    if report.matrix is not None:
        lines += [
            f"- **Roles tested**: {len(report.matrix.roles)}",
            f"- **Entities**: {len(report.matrix.entities)}",
            f"- **Operations**: {len(report.matrix.operations)}",
        ]
    lines += [
        f"- **Total cells**: {report.total}",
        f"- **Passed**: {report.passed}",
        f"- **Violations**: {report.violated}",
        f"- **Warnings**: {report.warnings}",
        "",
    ]
    return lines


def _render_matrix_table(report: VerificationReport) -> list[str]:
    if not report.cells:
        return ["## Access Matrix", "", "*(no cells — run `dazzle rbac verify` first)*", ""]

    # Gather unique roles, entities, operations from cells.
    roles: list[str] = []
    entities: list[str] = []
    operations: list[str] = []
    seen_roles: set[str] = set()
    seen_entities: set[str] = set()
    seen_operations: set[str] = set()

    # Preserve insertion order.
    if report.matrix is not None:
        roles = list(report.matrix.roles)
        entities = list(report.matrix.entities)
        operations = list(report.matrix.operations)
    else:
        for cell in report.cells:
            if cell.role not in seen_roles:
                roles.append(cell.role)
                seen_roles.add(cell.role)
            if cell.entity not in seen_entities:
                entities.append(cell.entity)
                seen_entities.add(cell.entity)
            if cell.operation not in seen_operations:
                operations.append(cell.operation)
                seen_operations.add(cell.operation)

    # Build lookup: (role, entity, operation) → CellResult
    lookup: dict[tuple[str, str, str], CellResult] = {
        (c.role, c.entity, c.operation): c.result for c in report.cells
    }

    lines = ["## Access Matrix", ""]

    for entity in entities:
        lines.append(f"### {entity}")
        lines.append("")

        header = "| operation | " + " | ".join(roles) + " |"
        separator = "| --- | " + " | ".join(["---"] * len(roles)) + " |"
        lines.append(header)
        lines.append(separator)

        for op in operations:
            row_parts = [op]
            for role in roles:
                key = (role, entity, op)
                result = lookup.get(key)
                if result is None:
                    row_parts.append("-")
                else:
                    row_parts.append(_CELL_GLYPH[result])
            lines.append("| " + " | ".join(row_parts) + " |")

        lines.append("")

    return lines


def _render_violations(report: VerificationReport) -> list[str]:
    violations = [c for c in report.cells if c.result == CellResult.VIOLATION]
    warnings = [c for c in report.cells if c.result == CellResult.WARNING]

    if not violations and not warnings:
        return ["## Findings", "", "No violations or warnings detected.", ""]

    lines = ["## Findings", ""]

    if violations:
        lines += [f"### Violations ({len(violations)})", ""]
        for v in violations:
            lines.append(
                f"- **{v.role}** / **{v.entity}** / `{v.operation}`: "
                f"expected `{v.expected}`, got HTTP {v.observed_status}. "
                f"{v.detail}"
            )
        lines.append("")

    if warnings:
        lines += [f"### Warnings ({len(warnings)})", ""]
        for w in warnings:
            lines.append(
                f"- **{w.role}** / **{w.entity}** / `{w.operation}`: "
                f"expected `{w.expected}`, got HTTP {w.observed_status}. "
                f"{w.detail}"
            )
        lines.append("")

    return lines


def _render_methodology() -> list[str]:
    return [
        "## Methodology",
        "",
        "This report was generated by the Dazzle RBAC Verification Framework.",
        "",
        "### Standards and References",
        "",
        "- **NIST SP 800-162** — *Guide to Attribute Based Access Control (ABAC) Definition "
        "and Considerations* (2014).  Provides the conceptual basis for policy-based access "
        "control and the separation of policy enforcement from policy decision.",
        "",
        "- **Saltzer & Schroeder (1975)** — *The Protection of Information in Computer Systems.*  "
        "Defines the principle of least privilege and complete mediation, which underpin the "
        "DENY-by-default Cedar semantics used in this framework.",
        "",
        "- **ISO/IEC 27001:2022** — Annex A, Control 5.15 (Access Control).  Requires that "
        "access to information and associated assets is controlled and that access rules are "
        "established, documented, and reviewed.",
        "",
        "### Verification Approach",
        "",
        "1. **Layer 1 (Static)** — `dazzle rbac matrix` resolves the access matrix from DSL "
        "without starting a server.  Cedar semantics: FORBID overrides PERMIT; no matching "
        "rule implies DENY.",
        "",
        "2. **Layer 2 (Dynamic)** — `dazzle rbac verify` probes live API endpoints with "
        "synthetic credentials for each role, compares HTTP responses against the static "
        "matrix, and records every decision via the audit trail.",
        "",
        "3. **Layer 3 (Audit)** — `AccessDecisionRecord` events are emitted for every "
        "permission evaluation, enabling post-hoc forensic review.",
        "",
    ]


def generate_report(report: VerificationReport, format: str = "markdown") -> str:
    """Generate a compliance report from *report*.

    Currently only ``"markdown"`` format is supported.  Passing any other
    value also produces Markdown (format is reserved for future JSON/HTML
    output).

    When *report* has ``error`` set (boot/provisioning failure) the report
    opens with a clear notice so the rendered output is never silently empty.
    """
    lines: list[str] = [
        "# RBAC Compliance Report",
        "",
    ]
    if report.error is not None:
        lines += [
            "> **Verification did not run.**",
            f"> Error: {report.error}",
            ">",
            "> Run `dazzle rbac verify` with a reachable PostgreSQL server to generate a full report.",
            "",
        ]
    # Lazy import: report.py imports only from dazzle.rbac at module level
    # (see header). Keep the back-runtime symbol local to avoid pulling the
    # FastAPI runtime into the rbac import graph at module load.
    from dazzle.http.runtime.csrf import CSRFConfig, render_csrf_policy

    lines.extend(_render_summary(report))
    lines.extend(_render_matrix_table(report))
    lines.extend(_render_violations(report))
    lines.extend(render_csrf_policy(CSRFConfig(enabled=True)))
    lines.extend(_render_methodology())

    return "\n".join(lines)


def _md_cell(value: str) -> str:
    """Escape a value for a markdown table cell — `|` and newlines would break the
    table structure of the auditor artifact (L6: roles/reason/ids are data)."""
    return value.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ").replace("\r", " ")


def render_access_review_markdown(review: "AccessReview") -> str:
    """Render an access-review evidence pack to markdown (auth Plan 2b).

    Sections: roster (who has access + roles as of the snapshot moment), JML
    access-change stream, control coverage (which SOC 2 / ISO controls the
    evidence supports), the table↔log reconciliation, and the tamper-evidence
    integrity attestation (honestly scoped — see ``ChainAttestation``).
    """
    s = review.snapshot
    as_of = s.as_of or "now (current state)"
    lines: list[str] = [
        "# Access Review",
        "",
        f"- **Organization**: {_md_cell(review.tenant_id)}",
        f"- **Generated**: {review.generated_at}",
        f"- **Snapshot as of**: {_md_cell(as_of)} (source: {s.source})",
        f"- **Change period**: {review.period_since or '—'} → {review.period_until or '—'}",
        "",
        "## Membership Roster",
        "",
        f"_{len(s.members)} membership(s) with access to {_md_cell(review.tenant_id)}._",
        "",
        "| membership | identity | roles | status | joined |",
        "| --- | --- | --- | --- | --- |",
    ]
    for m in sorted(s.members, key=lambda x: x.identity_id):
        roles = _md_cell(", ".join(m.roles)) if m.roles else "—"
        lines.append(
            f"| `{_md_cell(m.membership_id)}` | {_md_cell(m.identity_id)} | {roles} | "
            f"{_md_cell(m.status)} | {m.joined_at or '—'} |"
        )
    lines += [
        "",
        "## Access Changes (Joiner / Mover / Leaver)",
        "",
    ]
    if not review.jml:
        lines += ["_No access changes in the period._", ""]
    else:
        lines += [
            "| when | JML | event | identity | roles before → after | status | actor | reason | controls |",
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
        for j in review.jml:
            rb = _md_cell(", ".join(j.roles_before)) if j.roles_before else "—"
            ra = _md_cell(", ".join(j.roles_after)) if j.roles_after else "—"
            st = f"{j.status_before or '—'} → {j.status_after or '—'}"
            lines.append(
                f"| {j.at} | {j.jml} | `{_md_cell(j.event_type)}` | {_md_cell(j.identity_id)} | "
                f"{rb} → {ra} | {st} | {_md_cell(j.actor_id or '—')} | "
                f"{_md_cell(j.reason or '—')} | {', '.join(j.controls)} |"
            )
        lines.append("")
    lines += ["## Control Coverage", "", "| control | evidence |", "| --- | --- |"]
    # Invert the control index: control id → the event kinds / roster that evidence it.
    control_to_sources: dict[str, list[str]] = {}
    for source, controls in review.control_index.items():
        for c in controls:
            control_to_sources.setdefault(c, []).append(source)
    for control in sorted(control_to_sources):
        lines.append(f"| **{control}** | {', '.join(sorted(control_to_sources[control]))} |")

    # Reconciliation (current-state snapshots only): table vs replay-to-now.
    if review.reconciliation is not None:
        r = review.reconciliation
        lines += ["", "## Roster Reconciliation (table vs event log)", ""]
        if r.consistent:
            lines.append(
                "- **Consistent**: the current memberships table matches a replay of the "
                "event log — every grant is backed by lifecycle events."
            )
        else:
            lines.append(
                "- **INCONSISTENT**: the current table diverges from the event log "
                "(a mutation may have bypassed the store / raw SQL):"
            )
            if r.only_in_table:
                lines.append(
                    f"  - in table but not in the log: {', '.join(f'`{x}`' for x in r.only_in_table)}"
                )
            if r.only_in_replay:
                lines.append(
                    f"  - in the log but not in the table: "
                    f"{', '.join(f'`{x}`' for x in r.only_in_replay)}"
                )
            if r.role_mismatches:
                lines.append(f"  - role mismatch: {', '.join(f'`{x}`' for x in r.role_mismatches)}")

    # Integrity attestation — honestly scoped (C1): the chain detects edited /
    # removed interior events, NOT trailing-event truncation.
    status = "INTACT" if review.chain.ok else "BROKEN"
    lines += [
        "",
        "## Evidence Integrity",
        "",
        (
            f"- **Hash chain (interior integrity)**: {status} "
            f"({review.chain.total_rows} event(s); {review.chain.mismatched_count} mismatch(es)). "
            "Detects edited or removed interior events."
        ),
        (
            "- **Scope caveat**: a self-contained chain cannot detect truncation of the most "
            "recent trailing events (no successor hash to break). A tamper-proof guarantee "
            "against tail truncation requires an external signed head anchor (not yet implemented)."
        ),
    ]
    if not review.chain.ok:
        lines.append(
            f"- **First broken event**: `{_md_cell(review.chain.first_mismatch_id or '')}`"
        )
    lines.append("")
    return "\n".join(lines)
