"""Committed readable framework schema snapshot — Task 3 of framework-migration-baseline.

This module holds the DECLARED framework schema as a plain Python dict literal.
It is the third element of the three-way parity gate::

    alembic-head ≡ ensure_framework_schema ≡ FRAMEWORK_SCHEMA_SNAPSHOT

**Source of truth:** generated by running ``ensure_framework_schema`` on a
scratch Postgres database and calling
``dazzle.db.schema_snapshot.introspect_schema(engine, only=IN_SCOPE_TABLES)``
followed by ``render_snapshot_literal``.

**In-scope tables** (30): every entry in the FRAMEWORK_SCHEMA_SNAPSHOT dict
key set (see the global-constraints list in the migration-baseline plan).

**Excluded (not in this snapshot):** ops-database tables, event-bus
``{prefix}events/offsets/dlq`` tables (dynamic prefix), tenant registry
``public.tenants``, per-tenant schemas, and app-entity tables.

**Regeneration:** run ``dazzle db reframework-baseline`` (Task 5) or:

    python -c "
    from dazzle.http.runtime.framework_schema_snapshot import regenerate_and_print
    regenerate_and_print()
    "

**Parity gate:** ``tests/integration/test_framework_baseline_parity_pg.py``
asserts all three paths agree on every in-scope table.

Generated: 2026-06-23 (framework-migration-baseline Tasks 3+4, ADR-0044)
"""

from __future__ import annotations

# Module-top dazzle imports (no circular dependency: snapshot ← db.schema_snapshot;
# snapshot ← http.runtime.framework_schema which does not import back from here).
from dazzle.db.schema_snapshot import introspect_schema, render_snapshot_literal
from dazzle.http.runtime.framework_schema import ensure_framework_schema

# ---------------------------------------------------------------------------
# In-scope table set — the filter applied during introspect_schema.
# Must stay in sync with the global-constraints list in the plan and with
# the IN_SCOPE_TABLES constant in the parity test.
# ---------------------------------------------------------------------------

IN_SCOPE_TABLES: frozenset[str] = frozenset(
    {
        "_dazzle_params",
        # auth
        "users",
        "sessions",
        "memberships",
        "organizations",
        "membership_events",
        "invitations",
        "connections",
        "connection_secret_events",
        "scim_groups",
        "scim_group_members",
        "saml_consumed_assertions",
        "password_reset_tokens",
        "magic_links",
        "email_verification_tokens",
        "user_preferences",
        "join_requests",
        # process
        "process_runs",
        "process_tasks",
        # audit / misc
        "_dazzle_audit_log",
        "_dazzle_atomic_audit",
        "dazzle_files",
        "refresh_tokens",
        "devices",
        "_grants",
        "_grant_events",
        "_dazzle_otp_codes",
        "_dazzle_recovery_codes",
        "_dazzle_event_inbox",
        "_dazzle_event_outbox",
    }
)


# ---------------------------------------------------------------------------
# The declared framework schema snapshot.
# Every key is a table name; every value is a TableSnap dict with keys:
#   columns: dict[str, ColSnap]  (type, nullable, default, pk)
#   fks:     dict[str, str]      (column -> referred_table)
#   uniques: list[str]           (sorted column names)
#   indexes: list[str]           (sorted comma-joined column name strings)
# ---------------------------------------------------------------------------

FRAMEWORK_SCHEMA_SNAPSHOT = {
    "_dazzle_atomic_audit": {
        "columns": {
            "decision": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "entity_id": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "entity_name": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "flow_name": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "matched_policy": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "operation": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "timestamp": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "user_email": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "user_id": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "user_roles": {"default": None, "nullable": True, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": ["flow_name,timestamp"],
        "uniques": [],
    },
    "_dazzle_audit_log": {
        "columns": {
            "decision": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "entity_id": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "entity_name": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "evaluation_time_us": {
                "default": None,
                "nullable": True,
                "pk": False,
                "type": "integer",
            },
            "field_changes": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "ip_address": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "matched_policy": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "operation": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "policy_effect": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "request_method": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "request_path": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "row_hash": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "tenant_id": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "timestamp": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "user_email": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "user_id": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "user_roles": {"default": None, "nullable": True, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": ["entity_name,timestamp", "timestamp", "timestamp,user_id"],
        "uniques": [],
    },
    "_dazzle_event_inbox": {
        "columns": {
            "consumer_name": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "event_id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "processed_at": {
                "default": "(now())::text",
                "nullable": False,
                "pk": False,
                "type": "text",
            },
            "result": {
                "default": "'success'::text",
                "nullable": False,
                "pk": False,
                "type": "text",
            },
            "result_data": {"default": None, "nullable": True, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": ["consumer_name", "processed_at"],
        "uniques": [],
    },
    "_dazzle_event_outbox": {
        "columns": {
            "attempts": {"default": "0", "nullable": False, "pk": False, "type": "integer"},
            "created_at": {
                "default": "(now())::text",
                "nullable": False,
                "pk": False,
                "type": "text",
            },
            "envelope_json": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "event_type": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "key": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "last_error": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "lock_expires_at": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "lock_token": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "published_at": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "status": {
                "default": "'pending'::text",
                "nullable": False,
                "pk": False,
                "type": "text",
            },
            "topic": {"default": None, "nullable": False, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": ["created_at", "status", "topic"],
        "uniques": [],
    },
    "_dazzle_otp_codes": {
        "columns": {
            "attempts": {"default": "0", "nullable": True, "pk": False, "type": "integer"},
            "code_hash": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "created_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "expires_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "id": {
                "default": "nextval('_dazzle_otp_codes_id_seq'::regclass)",
                "nullable": False,
                "pk": True,
                "type": "integer",
            },
            "max_attempts": {"default": "3", "nullable": True, "pk": False, "type": "integer"},
            "method": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "used": {"default": "false", "nullable": True, "pk": False, "type": "boolean"},
            "user_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": ["expires_at", "method,user_id"],
        "uniques": [],
    },
    "_dazzle_params": {
        "columns": {
            "key": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "scope": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "scope_id": {"default": "''::text", "nullable": False, "pk": True, "type": "text"},
            "updated_at": {
                "default": "now()",
                "nullable": True,
                "pk": False,
                "type": "timestamptz",
            },
            "updated_by": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "value_json": {"default": None, "nullable": False, "pk": False, "type": "json"},
        },
        "fks": {},
        "indexes": [],
        "uniques": [],
    },
    "_dazzle_recovery_codes": {
        "columns": {
            "code_hash": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "created_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "id": {
                "default": "nextval('_dazzle_recovery_codes_id_seq'::regclass)",
                "nullable": False,
                "pk": True,
                "type": "integer",
            },
            "used": {"default": "false", "nullable": True, "pk": False, "type": "boolean"},
            "used_at": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "user_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": ["user_id"],
        "uniques": [],
    },
    "_grant_events": {
        "columns": {
            "actor_id": {"default": None, "nullable": False, "pk": False, "type": "uuid"},
            "event_type": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "grant_id": {"default": None, "nullable": False, "pk": False, "type": "uuid"},
            "id": {"default": "gen_random_uuid()", "nullable": False, "pk": True, "type": "uuid"},
            "metadata": {"default": None, "nullable": True, "pk": False, "type": "json"},
            "timestamp": {
                "default": "now()",
                "nullable": False,
                "pk": False,
                "type": "timestamptz",
            },
        },
        "fks": {"grant_id": "_grants"},
        "indexes": ["grant_id"],
        "uniques": [],
    },
    "_grants": {
        "columns": {
            "approved_at": {"default": None, "nullable": True, "pk": False, "type": "timestamptz"},
            "approved_by_id": {"default": None, "nullable": True, "pk": False, "type": "uuid"},
            "expires_at": {"default": None, "nullable": True, "pk": False, "type": "timestamptz"},
            "granted_at": {
                "default": "now()",
                "nullable": False,
                "pk": False,
                "type": "timestamptz",
            },
            "granted_by_id": {"default": None, "nullable": False, "pk": False, "type": "uuid"},
            "id": {"default": "gen_random_uuid()", "nullable": False, "pk": True, "type": "uuid"},
            "principal_id": {"default": None, "nullable": False, "pk": False, "type": "uuid"},
            "relation": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "revoked_at": {"default": None, "nullable": True, "pk": False, "type": "timestamptz"},
            "revoked_by_id": {"default": None, "nullable": True, "pk": False, "type": "uuid"},
            "schema_name": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "scope_entity": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "scope_id": {"default": None, "nullable": False, "pk": False, "type": "uuid"},
            "status": {"default": None, "nullable": False, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": ["expires_at,status", "principal_id,relation,scope_id,status"],
        "uniques": [],
    },
    "connection_secret_events": {
        "columns": {
            "actor": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "connection_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "detail": {"default": "'{}'::text", "nullable": False, "pk": False, "type": "text"},
            "event": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "seq": {"default": None, "nullable": False, "pk": False, "type": "bigint"},
            "tenant_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": ["connection_id,seq"],
        "uniques": [],
    },
    "connections": {
        "columns": {
            "config": {"default": "'{}'::text", "nullable": False, "pk": False, "type": "text"},
            "created_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "domains": {"default": "'[]'::text", "nullable": False, "pk": False, "type": "text"},
            "encrypted_secret": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "group_mapping": {
                "default": "'{}'::text",
                "nullable": False,
                "pk": False,
                "type": "text",
            },
            "id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "previous_encrypted_secret": {
                "default": None,
                "nullable": True,
                "pk": False,
                "type": "text",
            },
            "previous_secret_expires_at": {
                "default": None,
                "nullable": True,
                "pk": False,
                "type": "text",
            },
            "provider": {
                "default": "'native'::text",
                "nullable": False,
                "pk": False,
                "type": "text",
            },
            "status": {"default": "'active'::text", "nullable": False, "pk": False, "type": "text"},
            "tenant_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "type": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "updated_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "verified_domains": {
                "default": "'[]'::text",
                "nullable": False,
                "pk": False,
                "type": "text",
            },
        },
        "fks": {},
        "indexes": ["tenant_id"],
        "uniques": [],
    },
    "dazzle_files": {
        "columns": {
            "content_type": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "created_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "entity_id": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "entity_name": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "field_name": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "filename": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "size": {"default": None, "nullable": False, "pk": False, "type": "bigint"},
            "storage_backend": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "storage_key": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "thumbnail_key": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "updated_at": {"default": None, "nullable": True, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": ["entity_id,entity_name", "entity_name,field_name"],
        "uniques": [],
    },
    "devices": {
        "columns": {
            "app_version": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "created_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "device_name": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "is_active": {"default": "true", "nullable": True, "pk": False, "type": "boolean"},
            "last_used_at": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "os_version": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "platform": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "push_token": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "user_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": ["is_active,user_id", "platform", "push_token,user_id", "user_id"],
        "uniques": ["push_token", "user_id"],
    },
    "email_verification_tokens": {
        "columns": {
            "created_by": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "expires_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "token": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "used_at": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "user_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": ["user_id"],
        "uniques": [],
    },
    "invitations": {
        "columns": {
            "accepted_at": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "created_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "email": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "expires_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "invited_by": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "org_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "roles": {"default": "'[]'::text", "nullable": False, "pk": False, "type": "text"},
            "token": {"default": None, "nullable": False, "pk": True, "type": "text"},
        },
        "fks": {},
        "indexes": ["email", "org_id"],
        "uniques": [],
    },
    "join_requests": {
        "columns": {
            "created_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "decided_at": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "decided_by": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "email": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "identity_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "status": {
                "default": "'pending'::text",
                "nullable": False,
                "pk": False,
                "type": "text",
            },
            "tenant_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": ["identity_id,tenant_id", "tenant_id"],
        "uniques": [],
    },
    "magic_links": {
        "columns": {
            "created_by": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "expires_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "token": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "used_at": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "user_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": [],
        "uniques": [],
    },
    "membership_events": {
        "columns": {
            "actor_id": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "created_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "event_type": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "identity_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "membership_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "reason": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "roles_after": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "roles_before": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "row_hash": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "seq": {"default": None, "nullable": False, "pk": False, "type": "bigint"},
            "status_after": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "status_before": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "tenant_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": ["identity_id,seq", "membership_id,seq", "seq", "seq,tenant_id"],
        "uniques": ["seq"],
    },
    "memberships": {
        "columns": {
            "created_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "external_id": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "identity_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "invited_by": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "joined_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "roles": {"default": "'[]'::text", "nullable": False, "pk": False, "type": "text"},
            "status": {"default": "'active'::text", "nullable": False, "pk": False, "type": "text"},
            "tenant_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "updated_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": ["external_id,tenant_id", "identity_id", "identity_id,tenant_id", "tenant_id"],
        "uniques": ["identity_id", "tenant_id"],
    },
    "organizations": {
        "columns": {
            "created_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "is_test": {"default": "false", "nullable": False, "pk": False, "type": "boolean"},
            "name": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "settings": {"default": "'{}'::text", "nullable": False, "pk": False, "type": "text"},
            "slug": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "status": {"default": "'active'::text", "nullable": False, "pk": False, "type": "text"},
            "updated_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": ["slug"],
        "uniques": ["slug"],
    },
    "password_reset_tokens": {
        "columns": {
            "created_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "expires_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "token": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "used": {"default": "false", "nullable": True, "pk": False, "type": "boolean"},
            "user_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
        },
        "fks": {"user_id": "users"},
        "indexes": ["user_id"],
        "uniques": [],
    },
    "process_runs": {
        "columns": {
            "attempts": {"default": "0", "nullable": False, "pk": False, "type": "integer"},
            "claimed_at": {"default": None, "nullable": True, "pk": False, "type": "timestamptz"},
            "claimed_by": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "completed_at": {"default": None, "nullable": True, "pk": False, "type": "timestamptz"},
            "context": {"default": "'{}'::jsonb", "nullable": False, "pk": False, "type": "json"},
            "current_step": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "deliver_at": {
                "default": "now()",
                "nullable": False,
                "pk": False,
                "type": "timestamptz",
            },
            "dsl_version": {
                "default": "'0.1'::text",
                "nullable": False,
                "pk": False,
                "type": "text",
            },
            "error": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "idempotency_key": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "inputs": {"default": "'{}'::jsonb", "nullable": False, "pk": False, "type": "json"},
            "lease_expires_at": {
                "default": None,
                "nullable": True,
                "pk": False,
                "type": "timestamptz",
            },
            "outputs": {"default": None, "nullable": True, "pk": False, "type": "json"},
            "payload": {"default": "'{}'::jsonb", "nullable": False, "pk": False, "type": "json"},
            "process_name": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "process_version": {
                "default": "'v1'::text",
                "nullable": False,
                "pk": False,
                "type": "text",
            },
            "run_id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "started_at": {
                "default": "now()",
                "nullable": False,
                "pk": False,
                "type": "timestamptz",
            },
            "status": {
                "default": "'pending'::text",
                "nullable": False,
                "pk": False,
                "type": "text",
            },
            "updated_at": {
                "default": "now()",
                "nullable": False,
                "pk": False,
                "type": "timestamptz",
            },
        },
        "fks": {},
        "indexes": ["deliver_at", "idempotency_key"],
        "uniques": [],
    },
    "process_tasks": {
        "columns": {
            "assignee_id": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "assignee_role": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "attempts": {"default": "0", "nullable": False, "pk": False, "type": "integer"},
            "claimed_at": {"default": None, "nullable": True, "pk": False, "type": "timestamptz"},
            "claimed_by": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "completed_at": {"default": None, "nullable": True, "pk": False, "type": "timestamptz"},
            "created_at": {
                "default": "now()",
                "nullable": False,
                "pk": False,
                "type": "timestamptz",
            },
            "deliver_at": {
                "default": "now()",
                "nullable": False,
                "pk": False,
                "type": "timestamptz",
            },
            "due_at": {"default": None, "nullable": False, "pk": False, "type": "timestamptz"},
            "entity_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "entity_name": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "escalated_at": {"default": None, "nullable": True, "pk": False, "type": "timestamptz"},
            "lease_expires_at": {
                "default": None,
                "nullable": True,
                "pk": False,
                "type": "timestamptz",
            },
            "outcome": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "outcome_data": {"default": None, "nullable": True, "pk": False, "type": "json"},
            "payload": {"default": "'{}'::jsonb", "nullable": False, "pk": False, "type": "json"},
            "run_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "status": {
                "default": "'pending'::text",
                "nullable": False,
                "pk": False,
                "type": "text",
            },
            "step_name": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "surface_name": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "task_id": {"default": None, "nullable": False, "pk": True, "type": "text"},
        },
        "fks": {"run_id": "process_runs"},
        "indexes": ["deliver_at"],
        "uniques": [],
    },
    "refresh_tokens": {
        "columns": {
            "created_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "device_id": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "expires_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "ip_address": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "last_used_at": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "revoked_at": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "token_hash": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "user_agent": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "user_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": ["device_id,user_id", "expires_at", "user_id"],
        "uniques": [],
    },
    "saml_consumed_assertions": {
        "columns": {
            "assertion_id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "connection_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "created_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "expires_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "tenant_id": {"default": None, "nullable": True, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": [],
        "uniques": [],
    },
    "scim_group_members": {
        "columns": {
            "group_id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "membership_id": {"default": None, "nullable": False, "pk": True, "type": "text"},
        },
        "fks": {"group_id": "scim_groups"},
        "indexes": ["membership_id"],
        "uniques": [],
    },
    "scim_groups": {
        "columns": {
            "connection_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "created_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "display_name": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "external_id": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "updated_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": ["connection_id", "connection_id,display_name"],
        "uniques": ["connection_id", "display_name"],
    },
    "sessions": {
        "columns": {
            "active_membership_id": {
                "default": None,
                "nullable": True,
                "pk": False,
                "type": "text",
            },
            "created_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "csrf_secret": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "expires_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "ip_address": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "user_agent": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "user_id": {"default": None, "nullable": False, "pk": False, "type": "text"},
        },
        "fks": {"user_id": "users"},
        "indexes": ["expires_at", "user_id"],
        "uniques": [],
    },
    "user_preferences": {
        "columns": {
            "key": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "updated_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "user_id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "value": {"default": None, "nullable": False, "pk": False, "type": "text"},
        },
        "fks": {"user_id": "users"},
        "indexes": ["user_id"],
        "uniques": [],
    },
    "users": {
        "columns": {
            "created_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "email": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "email_otp_enabled": {
                "default": "false",
                "nullable": True,
                "pk": False,
                "type": "boolean",
            },
            "email_verified": {
                "default": "false",
                "nullable": True,
                "pk": False,
                "type": "boolean",
            },
            "id": {"default": None, "nullable": False, "pk": True, "type": "text"},
            "is_active": {"default": "true", "nullable": True, "pk": False, "type": "boolean"},
            "is_superuser": {"default": "false", "nullable": True, "pk": False, "type": "boolean"},
            "password_hash": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "recovery_codes_generated": {
                "default": "false",
                "nullable": True,
                "pk": False,
                "type": "boolean",
            },
            "roles": {"default": "'[]'::text", "nullable": True, "pk": False, "type": "text"},
            "totp_enabled": {"default": "false", "nullable": True, "pk": False, "type": "boolean"},
            "totp_secret": {"default": None, "nullable": True, "pk": False, "type": "text"},
            "updated_at": {"default": None, "nullable": False, "pk": False, "type": "text"},
            "username": {"default": None, "nullable": True, "pk": False, "type": "text"},
        },
        "fks": {},
        "indexes": ["email", "email"],
        "uniques": ["email"],
    },
}


def regenerate_and_print() -> None:
    """Re-generate the snapshot from a fresh orchestrator run and print it.

    Useful for updating this file after schema changes.  Pipe the output
    back into this module to update the snapshot.
    """
    import uuid

    import psycopg
    import sqlalchemy as sa

    admin_url = "postgresql://localhost:5432/postgres"
    name = f"dazzle_snap_{uuid.uuid4().hex[:8]}"
    with psycopg.connect(admin_url, autocommit=True) as a:
        a.execute(
            f'CREATE DATABASE "{name}"'  # nosemgrep
        )
    try:
        conn = psycopg.connect(f"postgresql://localhost:5432/{name}")
        conn.autocommit = False
        ensure_framework_schema(conn)
        conn.close()

        eng = sa.create_engine(f"postgresql+psycopg://localhost:5432/{name}")
        try:
            snap = introspect_schema(eng, only=set(IN_SCOPE_TABLES))
            print(render_snapshot_literal(snap))
        finally:
            eng.dispose()
    finally:
        with psycopg.connect(admin_url, autocommit=True) as a:
            a.execute(
                f'DROP DATABASE IF EXISTS "{name}"'  # nosemgrep
            )
