"""
Alembic environment configuration for Dazzle.

Reads DATABASE_URL from the environment and uses the EntitySpec → SQLAlchemy
MetaData bridge as ``target_metadata`` so that ``--autogenerate`` can diff
the DSL schema against the live database.
"""

import logging
import os
import sys
from logging.config import fileConfig
from pathlib import Path
from typing import Any

import sqlalchemy
from alembic import context
from alembic.operations import ops as alembic_ops

from dazzle.core.db_url import add_psycopg_driver, normalise_postgres_scheme

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Alembic Config object (provides access to alembic.ini values)
# ---------------------------------------------------------------------------
config = context.config

# Interpret the config file for Python logging (if present).
if config.config_file_name and os.path.exists(config.config_file_name):
    fileConfig(config.config_file_name)

# ---------------------------------------------------------------------------
# Target metadata — built from DSL EntitySpecs
# ---------------------------------------------------------------------------

# Ensure the project src/ is on sys.path so imports work.
_src = str(Path(__file__).resolve().parents[2])  # src/
if _src not in sys.path:
    sys.path.insert(0, _src)


def _load_target_metadata() -> sqlalchemy.MetaData:
    """Lazily load target metadata from the active Dazzle project.

    Delegates to the side-effect-free :func:`load_target_metadata` and falls
    back to empty MetaData on failure (e.g. when running ``alembic current``
    without a project context). The actual DSL→metadata logic lives in
    ``dazzle.back.alembic.metadata_loader`` so callers outside an Alembic run
    can reuse it without importing this module (which executes
    ``config = context.config`` at import time).
    """
    from dazzle.back.alembic.metadata_loader import load_target_metadata

    try:
        return load_target_metadata()
    except Exception:
        logger.warning("Failed to load target metadata from DSL", exc_info=True)
        return sqlalchemy.MetaData()


target_metadata = _load_target_metadata()

# ---------------------------------------------------------------------------
# Database URL
# ---------------------------------------------------------------------------


def _get_url() -> str:
    """Get database URL from alembic config or env.

    Prefers ``sqlalchemy.url`` (already normalised by ``db.py``) over the raw
    ``DATABASE_URL`` env var.  Handles Heroku's ``postgres://`` scheme and
    ensures the psycopg v3 driver is used.
    """
    url = config.get_main_option("sqlalchemy.url", "") or os.environ.get("DATABASE_URL", "")
    # Heroku uses the deprecated postgres:// scheme — normalise it, then
    # ensure SQLAlchemy uses psycopg v3, not psycopg2.
    return add_psycopg_driver(normalise_postgres_scheme(url))


# ---------------------------------------------------------------------------
# Revision directive hook
# ---------------------------------------------------------------------------


def _process_revision_directives(context: Any, revision: Any, directives: list[Any]) -> None:
    """Post-process autogenerated migration directives.

    1. Suppress empty revisions (no-op when DSL hasn't changed).
    2. Inject postgresql_using clauses for safe type casts.
    """
    if not directives:
        return

    script = directives[0]
    if script.upgrade_ops is None:
        return

    # Suppress empty migrations
    if script.upgrade_ops.is_empty():
        directives[:] = []
        return

    # Inject USING clauses for safe type casts
    try:
        from dazzle.back.runtime.safe_casts import get_using_clause
    except ImportError:
        return

    for op in script.upgrade_ops.ops:
        if not isinstance(op, alembic_ops.ModifyTableOps):
            continue
        for sub_op in op.ops:
            if not isinstance(sub_op, alembic_ops.AlterColumnOp):
                continue
            if sub_op.modify_type is None or sub_op.existing_type is None:
                continue
            # Get Postgres type names from SA types
            from_name = sub_op.existing_type.__class__.__name__.upper()
            to_name = sub_op.modify_type.__class__.__name__.upper()
            using = get_using_clause(from_name, to_name, sub_op.column_name)
            if using:
                sub_op.kw["postgresql_using"] = using


# ---------------------------------------------------------------------------
# Migration runners
# ---------------------------------------------------------------------------

# Framework-owned tables created at runtime, absent from the DSL-derived
# metadata — autogenerate must not propose dropping them (#1188).
_FRAMEWORK_TABLES = {"_dazzle_params"}


def _include_object(
    obj: Any, name: str | None, type_: str, reflected: bool, compare_to: Any
) -> bool:
    """Exclude objects autogenerate would otherwise churn on every run (#1188).

    Framework-owned tables are not in the DSL metadata; unnamed unique
    constraints cannot be reconciled by name, so Alembic re-emits them.
    """
    if type_ == "table" and name in _FRAMEWORK_TABLES:
        return False
    if type_ == "unique_constraint" and name is None:
        return False
    return True


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emit SQL without connecting)."""
    url = _get_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        include_object=_include_object,
        process_revision_directives=_process_revision_directives,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live database connection."""
    from sqlalchemy import create_engine

    url = _get_url()
    if not url:
        raise RuntimeError("DATABASE_URL environment variable is required for online migrations.")

    connectable = create_engine(url)

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            include_object=_include_object,
            process_revision_directives=_process_revision_directives,
        )

        with context.begin_transaction():
            tenant_schema = config.attributes.get("tenant_schema")
            if tenant_schema:
                import re

                # Validate: slug_to_schema_name() guarantees alphanumeric +
                # underscore only, but we enforce it here too so this file is
                # safe regardless of call-site discipline.
                if not re.fullmatch(r"[a-zA-Z0-9_]+", tenant_schema):
                    raise ValueError(
                        f"Invalid tenant_schema {tenant_schema!r}: "
                        "must be alphanumeric and underscores only"
                    )
                # Use the raw DBAPI cursor to SET search_path so that SQLAlchemy's
                # text() pathway is not involved (avoids taint-analysis false positives).
                # The schema name is validated as a safe identifier above.
                dbapi_conn: Any = connection.connection
                cur = dbapi_conn.cursor()
                try:
                    from psycopg import sql as pgsql

                    # SET cannot take a bound parameter; compose the
                    # already-validated identifier safely instead (#1201).
                    stmt = pgsql.SQL("SET search_path TO {}, public").format(
                        pgsql.Identifier(tenant_schema)
                    )
                    cur.execute(stmt)  # nosemgrep
                finally:
                    cur.close()
            context.run_migrations()

    connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
