"""
DDT (Dazzle Design Tokens) Compiler.

Compiles tokens.json into CSS custom properties and utility classes.
This is an LLM-first design system optimized for deterministic generation.

Usage:
    from dazzle_dnr_ui.tokens.compiler import compile_tokens, generate_css_bundle

    # Compile to CSS variables
    css = compile_tokens()

    # Generate complete CSS bundle
    bundle = generate_css_bundle()
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

# =============================================================================
# Token Loading
# =============================================================================


def load_tokens(tokens_path: Path | None = None) -> dict[str, Any]:
    """
    Load design tokens from JSON file.

    Args:
        tokens_path: Path to tokens.json. Defaults to bundled tokens.

    Returns:
        Token dictionary
    """
    if tokens_path is None:
        tokens_path = Path(__file__).parent / "tokens.json"

    with open(tokens_path) as f:
        return json.load(f)


# =============================================================================
# CSS Variable Generation
# =============================================================================


def _flatten_tokens(
    obj: dict[str, Any],
    prefix: str = "",
    result: dict[str, str] | None = None,
) -> dict[str, str]:
    """
    Flatten nested token structure into CSS variable names.

    Args:
        obj: Token object or nested dict
        prefix: Current path prefix
        result: Accumulator for results

    Returns:
        Dict mapping CSS variable names to values
    """
    if result is None:
        result = {}

    for key, value in obj.items():
        # Skip metadata keys
        if key.startswith("$"):
            continue

        # Build CSS variable name
        var_name = f"{prefix}-{key}" if prefix else key

        if isinstance(value, dict):
            # Recurse into nested objects
            _flatten_tokens(value, var_name, result)
        else:
            # Leaf value - add to result
            result[var_name] = str(value)

    return result


def compile_tokens_to_variables(tokens: dict[str, Any] | None = None) -> str:
    """
    Compile tokens to CSS custom properties.

    Args:
        tokens: Token dictionary. Loads default if None.

    Returns:
        CSS string with :root block containing all variables
    """
    if tokens is None:
        tokens = load_tokens()

    lines = [
        "/* =============================================================================",
        "   DDT (Dazzle Design Tokens) - CSS Custom Properties",
        "   Generated by dazzle_dnr_ui.tokens.compiler",
        "   DO NOT EDIT - regenerate from tokens.json",
        "   ============================================================================= */",
        "",
        ":root {",
    ]

    # Process each top-level category
    for category in [
        "color",
        "space",
        "radius",
        "shadow",
        "font",
        "transition",
        "breakpoint",
        "zIndex",
    ]:
        if category not in tokens:
            continue

        category_tokens = tokens[category]
        flat = _flatten_tokens(category_tokens, f"dz-{category}")

        if flat:
            lines.append(f"  /* {category.title()} */")
            for var_name, value in flat.items():
                lines.append(f"  --{var_name}: {value};")
            lines.append("")

    lines.append("}")
    lines.append("")

    return "\n".join(lines)


# =============================================================================
# Dark Theme Generation
# =============================================================================


def generate_dark_theme(tokens: dict[str, Any] | None = None) -> str:
    """
    Generate dark theme overrides.

    Args:
        tokens: Token dictionary. Loads default if None.

    Returns:
        CSS string with dark theme variables
    """
    lines = [
        "/* Dark Theme Overrides */",
        "[data-theme='dark'] {",
        "  /* Background colors inverted */",
        "  --dz-color-background-default: #0f172a;",
        "  --dz-color-background-subtle: #1e293b;",
        "  --dz-color-background-muted: #334155;",
        "  --dz-color-background-inverse: #ffffff;",
        "",
        "  /* Foreground colors inverted */",
        "  --dz-color-foreground-default: #f8fafc;",
        "  --dz-color-foreground-muted: #94a3b8;",
        "  --dz-color-foreground-subtle: #64748b;",
        "  --dz-color-foreground-inverse: #0f172a;",
        "",
        "  /* Border colors */",
        "  --dz-color-border-default: #334155;",
        "  --dz-color-border-muted: #1e293b;",
        "}",
        "",
    ]

    return "\n".join(lines)


# =============================================================================
# Semantic Component Styles
# =============================================================================


def generate_component_styles() -> str:
    """
    Generate semantic component styles using CSS variables.

    Returns:
        CSS string with component class definitions
    """
    return """/* =============================================================================
   DDT Component Styles - Semantic Classes
   Uses CSS variables from tokens for consistent theming
   ============================================================================= */

/* =============================================================================
   Base Reset & Typography
   ============================================================================= */

*, *::before, *::after {
  box-sizing: border-box;
}

html {
  font-family: var(--dz-font-family-base);
  font-size: var(--dz-font-size-base);
  line-height: var(--dz-font-lineHeight-normal);
  color: var(--dz-color-foreground-default);
  background: var(--dz-color-background-default);
  -webkit-font-smoothing: antialiased;
}

body {
  margin: 0;
  min-height: 100vh;
}

#app {
  min-height: 100vh;
  padding: var(--dz-space-6);
}

/* =============================================================================
   Surface - Container for content regions
   ============================================================================= */

.dz-surface {
  background: var(--dz-color-background-default);
  border: 1px solid var(--dz-color-border-default);
  border-radius: var(--dz-radius-lg);
  padding: var(--dz-space-6);
}

.dz-surface--elevated {
  box-shadow: var(--dz-shadow-md);
  border: none;
}

.dz-surface--flush {
  border-radius: 0;
  border-left: none;
  border-right: none;
}

/* =============================================================================
   Card - Contained content block
   ============================================================================= */

.dz-card {
  background: var(--dz-color-background-default);
  border: 1px solid var(--dz-color-border-default);
  border-radius: var(--dz-radius-lg);
  padding: var(--dz-space-6);
  box-shadow: var(--dz-shadow-sm);
}

.dz-card__header {
  margin-bottom: var(--dz-space-4);
  padding-bottom: var(--dz-space-4);
  border-bottom: 1px solid var(--dz-color-border-muted);
}

.dz-card__title {
  font-size: var(--dz-font-size-lg);
  font-weight: var(--dz-font-weight-semibold);
  color: var(--dz-color-foreground-default);
  margin: 0;
}

.dz-card__body {
  color: var(--dz-color-foreground-default);
}

.dz-card__footer {
  margin-top: var(--dz-space-4);
  padding-top: var(--dz-space-4);
  border-top: 1px solid var(--dz-color-border-muted);
}

/* =============================================================================
   Button - Interactive action element
   ============================================================================= */

.dz-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--dz-space-2);
  padding: var(--dz-space-2) var(--dz-space-4);
  font-family: inherit;
  font-size: var(--dz-font-size-sm);
  font-weight: var(--dz-font-weight-medium);
  line-height: var(--dz-font-lineHeight-normal);
  border-radius: var(--dz-radius-md);
  border: 1px solid transparent;
  cursor: pointer;
  transition: all var(--dz-transition-duration-fast) var(--dz-transition-timing-default);
  text-decoration: none;
}

.dz-button:focus-visible {
  outline: 2px solid var(--dz-color-border-focus);
  outline-offset: 2px;
}

.dz-button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

/* Button variants */
.dz-button--primary {
  background: var(--dz-color-intent-primary-default);
  color: var(--dz-color-intent-primary-foreground);
}

.dz-button--primary:hover:not(:disabled) {
  background: var(--dz-color-intent-primary-hover);
}

.dz-button--primary:active:not(:disabled) {
  background: var(--dz-color-intent-primary-active);
}

.dz-button--secondary {
  background: var(--dz-color-background-subtle);
  color: var(--dz-color-foreground-default);
  border-color: var(--dz-color-border-default);
}

.dz-button--secondary:hover:not(:disabled) {
  background: var(--dz-color-background-muted);
}

.dz-button--danger {
  background: var(--dz-color-intent-danger-default);
  color: var(--dz-color-intent-danger-foreground);
}

.dz-button--danger:hover:not(:disabled) {
  background: var(--dz-color-intent-danger-hover);
}

.dz-button--ghost {
  background: transparent;
  color: var(--dz-color-foreground-default);
}

.dz-button--ghost:hover:not(:disabled) {
  background: var(--dz-color-background-subtle);
}

/* Button sizes */
.dz-button--sm {
  padding: var(--dz-space-1) var(--dz-space-3);
  font-size: var(--dz-font-size-xs);
}

.dz-button--lg {
  padding: var(--dz-space-3) var(--dz-space-6);
  font-size: var(--dz-font-size-base);
}

/* =============================================================================
   Input - Form input elements
   ============================================================================= */

.dz-input {
  display: block;
  width: 100%;
  padding: var(--dz-space-2) var(--dz-space-3);
  font-family: inherit;
  font-size: var(--dz-font-size-sm);
  line-height: var(--dz-font-lineHeight-normal);
  color: var(--dz-color-foreground-default);
  background: var(--dz-color-background-default);
  border: 1px solid var(--dz-color-border-default);
  border-radius: var(--dz-radius-md);
  transition: border-color var(--dz-transition-duration-fast) var(--dz-transition-timing-default),
              box-shadow var(--dz-transition-duration-fast) var(--dz-transition-timing-default);
}

.dz-input::placeholder {
  color: var(--dz-color-foreground-subtle);
}

.dz-input:focus {
  outline: none;
  border-color: var(--dz-color-border-focus);
  box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
}

.dz-input:disabled {
  background: var(--dz-color-background-muted);
  cursor: not-allowed;
}

.dz-input--error {
  border-color: var(--dz-color-intent-danger-default);
}

.dz-input--error:focus {
  box-shadow: 0 0 0 3px rgba(239, 68, 68, 0.1);
}

/* =============================================================================
   Label - Form labels
   ============================================================================= */

.dz-label {
  display: block;
  margin-bottom: var(--dz-space-1);
  font-size: var(--dz-font-size-sm);
  font-weight: var(--dz-font-weight-medium);
  color: var(--dz-color-foreground-default);
}

.dz-label--required::after {
  content: " *";
  color: var(--dz-color-intent-danger-default);
}

/* =============================================================================
   Form - Form container
   ============================================================================= */

.dz-form {
  display: flex;
  flex-direction: column;
  gap: var(--dz-space-4);
}

.dz-form__group {
  display: flex;
  flex-direction: column;
}

.dz-form__actions {
  display: flex;
  gap: var(--dz-space-3);
  margin-top: var(--dz-space-4);
  padding-top: var(--dz-space-4);
  border-top: 1px solid var(--dz-color-border-muted);
}

.dz-form__error {
  font-size: var(--dz-font-size-sm);
  color: var(--dz-color-intent-danger-default);
  margin-top: var(--dz-space-1);
}

/* =============================================================================
   Table - Data tables
   ============================================================================= */

.dz-table {
  width: 100%;
  border-collapse: collapse;
  font-size: var(--dz-font-size-sm);
}

.dz-table th,
.dz-table td {
  padding: var(--dz-space-3) var(--dz-space-4);
  text-align: left;
  border-bottom: 1px solid var(--dz-color-border-default);
}

.dz-table th {
  font-weight: var(--dz-font-weight-semibold);
  color: var(--dz-color-foreground-default);
  background: var(--dz-color-background-subtle);
}

.dz-table td {
  color: var(--dz-color-foreground-default);
}

.dz-table tbody tr:hover {
  background: var(--dz-color-background-subtle);
}

.dz-table--striped tbody tr:nth-child(even) {
  background: var(--dz-color-background-subtle);
}

.dz-table--compact th,
.dz-table--compact td {
  padding: var(--dz-space-2) var(--dz-space-3);
}

/* =============================================================================
   FilterableTable - Table with controls
   ============================================================================= */

.dz-filterable-table {
  display: flex;
  flex-direction: column;
  gap: var(--dz-space-4);
}

.dz-filterable-table__header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: var(--dz-space-4);
}

.dz-filterable-table__title {
  font-size: var(--dz-font-size-xl);
  font-weight: var(--dz-font-weight-semibold);
  color: var(--dz-color-foreground-default);
  margin: 0;
}

.dz-filterable-table__controls {
  display: flex;
  gap: var(--dz-space-3);
  align-items: center;
}

.dz-filterable-table__search {
  min-width: 200px;
}

.dz-filterable-table__body {
  overflow-x: auto;
}

.dz-filterable-table__footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-top: var(--dz-space-4);
  border-top: 1px solid var(--dz-color-border-muted);
}

/* =============================================================================
   Badge - Status indicators
   ============================================================================= */

.dz-badge {
  display: inline-flex;
  align-items: center;
  padding: var(--dz-space-0-5) var(--dz-space-2);
  font-size: var(--dz-font-size-xs);
  font-weight: var(--dz-font-weight-medium);
  border-radius: var(--dz-radius-full);
  text-transform: uppercase;
  letter-spacing: var(--dz-font-letterSpacing-wide);
}

.dz-badge--default {
  background: var(--dz-color-background-muted);
  color: var(--dz-color-foreground-muted);
}

.dz-badge--success {
  background: var(--dz-color-intent-success-background);
  color: var(--dz-color-intent-success-default);
}

.dz-badge--warning {
  background: var(--dz-color-intent-warning-background);
  color: var(--dz-color-intent-warning-default);
}

.dz-badge--danger {
  background: var(--dz-color-intent-danger-background);
  color: var(--dz-color-intent-danger-default);
}

.dz-badge--info {
  background: var(--dz-color-intent-info-background);
  color: var(--dz-color-intent-info-default);
}

/* =============================================================================
   Stack - Flex container for vertical/horizontal layouts
   ============================================================================= */

.dz-stack {
  display: flex;
  flex-direction: column;
}

.dz-stack--row {
  flex-direction: row;
}

.dz-stack--wrap {
  flex-wrap: wrap;
}

.dz-stack--center {
  align-items: center;
}

.dz-stack--stretch {
  align-items: stretch;
}

.dz-stack--between {
  justify-content: space-between;
}

/* =============================================================================
   Grid - CSS Grid container
   ============================================================================= */

.dz-grid {
  display: grid;
  gap: var(--dz-space-4);
}

.dz-grid--cols-2 {
  grid-template-columns: repeat(2, 1fr);
}

.dz-grid--cols-3 {
  grid-template-columns: repeat(3, 1fr);
}

.dz-grid--cols-4 {
  grid-template-columns: repeat(4, 1fr);
}

@media (max-width: 768px) {
  .dz-grid--cols-2,
  .dz-grid--cols-3,
  .dz-grid--cols-4 {
    grid-template-columns: 1fr;
  }
}

/* =============================================================================
   Page - Full page container
   ============================================================================= */

.dz-page {
  min-height: 100vh;
  padding: var(--dz-space-6);
}

.dz-page__header {
  margin-bottom: var(--dz-space-6);
}

.dz-page__title {
  font-size: var(--dz-font-size-3xl);
  font-weight: var(--dz-font-weight-bold);
  color: var(--dz-color-foreground-default);
  margin: 0 0 var(--dz-space-2) 0;
}

.dz-page__subtitle {
  font-size: var(--dz-font-size-lg);
  color: var(--dz-color-foreground-muted);
  margin: 0;
}

.dz-page__content {
  max-width: 1200px;
  margin: 0 auto;
}

/* =============================================================================
   Navigation - Nav bar and links
   ============================================================================= */

.dz-nav {
  display: flex;
  align-items: center;
  gap: var(--dz-space-4);
  padding: var(--dz-space-4) var(--dz-space-6);
  background: var(--dz-color-background-default);
  border-bottom: 1px solid var(--dz-color-border-default);
}

.dz-nav__brand {
  font-size: var(--dz-font-size-lg);
  font-weight: var(--dz-font-weight-bold);
  color: var(--dz-color-foreground-default);
  text-decoration: none;
}

.dz-nav__links {
  display: flex;
  gap: var(--dz-space-1);
  margin-left: auto;
}

.dz-nav__link {
  padding: var(--dz-space-2) var(--dz-space-3);
  font-size: var(--dz-font-size-sm);
  color: var(--dz-color-foreground-muted);
  text-decoration: none;
  border-radius: var(--dz-radius-md);
  transition: all var(--dz-transition-duration-fast) var(--dz-transition-timing-default);
}

.dz-nav__link:hover {
  color: var(--dz-color-foreground-default);
  background: var(--dz-color-background-subtle);
}

.dz-nav__link--active {
  color: var(--dz-color-intent-primary-default);
  background: var(--dz-color-background-subtle);
}

/* =============================================================================
   Dialog/Modal - Overlay dialogs
   ============================================================================= */

.dz-dialog-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: var(--dz-zIndex-overlay);
}

.dz-dialog {
  background: var(--dz-color-background-default);
  border-radius: var(--dz-radius-xl);
  box-shadow: var(--dz-shadow-xl);
  max-width: 500px;
  width: 90%;
  max-height: 90vh;
  overflow-y: auto;
  z-index: var(--dz-zIndex-modal);
}

.dz-dialog__header {
  padding: var(--dz-space-6);
  border-bottom: 1px solid var(--dz-color-border-default);
}

.dz-dialog__title {
  font-size: var(--dz-font-size-lg);
  font-weight: var(--dz-font-weight-semibold);
  margin: 0;
}

.dz-dialog__body {
  padding: var(--dz-space-6);
}

.dz-dialog__footer {
  padding: var(--dz-space-4) var(--dz-space-6);
  border-top: 1px solid var(--dz-color-border-default);
  display: flex;
  justify-content: flex-end;
  gap: var(--dz-space-3);
}

/* =============================================================================
   Toast - Notification messages
   ============================================================================= */

.dz-toast-container {
  position: fixed;
  top: var(--dz-space-4);
  right: var(--dz-space-4);
  z-index: var(--dz-zIndex-tooltip);
  display: flex;
  flex-direction: column;
  gap: var(--dz-space-2);
}

.dz-toast {
  display: flex;
  align-items: flex-start;
  gap: var(--dz-space-3);
  padding: var(--dz-space-4);
  background: var(--dz-color-background-default);
  border-radius: var(--dz-radius-lg);
  box-shadow: var(--dz-shadow-lg);
  min-width: 300px;
  max-width: 500px;
}

.dz-toast--success {
  border-left: 4px solid var(--dz-color-intent-success-default);
}

.dz-toast--error {
  border-left: 4px solid var(--dz-color-intent-danger-default);
}

.dz-toast--warning {
  border-left: 4px solid var(--dz-color-intent-warning-default);
}

.dz-toast--info {
  border-left: 4px solid var(--dz-color-intent-info-default);
}

.dz-toast__message {
  flex: 1;
  font-size: var(--dz-font-size-sm);
}

.dz-toast__close {
  padding: var(--dz-space-1);
  cursor: pointer;
  opacity: 0.5;
}

.dz-toast__close:hover {
  opacity: 1;
}

/* =============================================================================
   Empty State - No data placeholder
   ============================================================================= */

.dz-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: var(--dz-space-12);
  text-align: center;
}

.dz-empty__icon {
  font-size: var(--dz-font-size-4xl);
  color: var(--dz-color-foreground-subtle);
  margin-bottom: var(--dz-space-4);
}

.dz-empty__title {
  font-size: var(--dz-font-size-lg);
  font-weight: var(--dz-font-weight-semibold);
  color: var(--dz-color-foreground-default);
  margin: 0 0 var(--dz-space-2) 0;
}

.dz-empty__description {
  font-size: var(--dz-font-size-sm);
  color: var(--dz-color-foreground-muted);
  margin: 0 0 var(--dz-space-6) 0;
  max-width: 400px;
}

/* =============================================================================
   Loading - Loading indicators
   ============================================================================= */

.dz-loading {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: var(--dz-space-8);
}

.dz-spinner {
  width: 24px;
  height: 24px;
  border: 2px solid var(--dz-color-border-default);
  border-top-color: var(--dz-color-intent-primary-default);
  border-radius: var(--dz-radius-full);
  animation: dz-spin 0.8s linear infinite;
}

@keyframes dz-spin {
  to { transform: rotate(360deg); }
}

.dz-skeleton {
  background: linear-gradient(
    90deg,
    var(--dz-color-background-muted) 25%,
    var(--dz-color-background-subtle) 50%,
    var(--dz-color-background-muted) 75%
  );
  background-size: 200% 100%;
  animation: dz-shimmer 1.5s infinite;
  border-radius: var(--dz-radius-md);
}

@keyframes dz-shimmer {
  0% { background-position: 200% 0; }
  100% { background-position: -200% 0; }
}
"""


# =============================================================================
# Utility Classes
# =============================================================================


def generate_utility_styles() -> str:
    """
    Generate minimal utility classes.

    These are intentionally limited to avoid Tailwind-style sprawl.
    Only includes utilities that significantly reduce redundancy.

    Returns:
        CSS string with utility class definitions
    """
    return """/* =============================================================================
   DDT Utility Classes - Minimal Set
   Only includes high-value utilities that reduce common redundancy
   ============================================================================= */

/* =============================================================================
   Gap Utilities - For flex/grid containers
   ============================================================================= */

.dz-gap-0 { gap: var(--dz-space-0); }
.dz-gap-1 { gap: var(--dz-space-1); }
.dz-gap-2 { gap: var(--dz-space-2); }
.dz-gap-3 { gap: var(--dz-space-3); }
.dz-gap-4 { gap: var(--dz-space-4); }
.dz-gap-5 { gap: var(--dz-space-5); }
.dz-gap-6 { gap: var(--dz-space-6); }
.dz-gap-8 { gap: var(--dz-space-8); }

/* =============================================================================
   Padding Utilities
   ============================================================================= */

.dz-p-0 { padding: var(--dz-space-0); }
.dz-p-2 { padding: var(--dz-space-2); }
.dz-p-4 { padding: var(--dz-space-4); }
.dz-p-6 { padding: var(--dz-space-6); }
.dz-p-8 { padding: var(--dz-space-8); }

.dz-px-4 { padding-left: var(--dz-space-4); padding-right: var(--dz-space-4); }
.dz-px-6 { padding-left: var(--dz-space-6); padding-right: var(--dz-space-6); }
.dz-py-2 { padding-top: var(--dz-space-2); padding-bottom: var(--dz-space-2); }
.dz-py-4 { padding-top: var(--dz-space-4); padding-bottom: var(--dz-space-4); }

/* =============================================================================
   Margin Utilities
   ============================================================================= */

.dz-m-0 { margin: var(--dz-space-0); }
.dz-m-auto { margin: auto; }
.dz-mt-2 { margin-top: var(--dz-space-2); }
.dz-mt-4 { margin-top: var(--dz-space-4); }
.dz-mt-6 { margin-top: var(--dz-space-6); }
.dz-mb-2 { margin-bottom: var(--dz-space-2); }
.dz-mb-4 { margin-bottom: var(--dz-space-4); }
.dz-mb-6 { margin-bottom: var(--dz-space-6); }
.dz-mx-auto { margin-left: auto; margin-right: auto; }

/* =============================================================================
   Text Utilities
   ============================================================================= */

.dz-text-xs { font-size: var(--dz-font-size-xs); }
.dz-text-sm { font-size: var(--dz-font-size-sm); }
.dz-text-base { font-size: var(--dz-font-size-base); }
.dz-text-lg { font-size: var(--dz-font-size-lg); }
.dz-text-xl { font-size: var(--dz-font-size-xl); }
.dz-text-2xl { font-size: var(--dz-font-size-2xl); }

.dz-font-normal { font-weight: var(--dz-font-weight-normal); }
.dz-font-medium { font-weight: var(--dz-font-weight-medium); }
.dz-font-semibold { font-weight: var(--dz-font-weight-semibold); }
.dz-font-bold { font-weight: var(--dz-font-weight-bold); }

.dz-text-muted { color: var(--dz-color-foreground-muted); }
.dz-text-subtle { color: var(--dz-color-foreground-subtle); }
.dz-text-success { color: var(--dz-color-intent-success-default); }
.dz-text-danger { color: var(--dz-color-intent-danger-default); }
.dz-text-warning { color: var(--dz-color-intent-warning-default); }

.dz-text-left { text-align: left; }
.dz-text-center { text-align: center; }
.dz-text-right { text-align: right; }

.dz-truncate {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

/* =============================================================================
   Display Utilities
   ============================================================================= */

.dz-hidden { display: none; }
.dz-block { display: block; }
.dz-inline { display: inline; }
.dz-inline-block { display: inline-block; }
.dz-flex { display: flex; }
.dz-inline-flex { display: inline-flex; }
.dz-grid { display: grid; }

/* =============================================================================
   Flex Utilities
   ============================================================================= */

.dz-flex-row { flex-direction: row; }
.dz-flex-col { flex-direction: column; }
.dz-flex-wrap { flex-wrap: wrap; }
.dz-flex-1 { flex: 1 1 0%; }
.dz-flex-none { flex: none; }
.dz-grow { flex-grow: 1; }
.dz-shrink-0 { flex-shrink: 0; }

.dz-items-start { align-items: flex-start; }
.dz-items-center { align-items: center; }
.dz-items-end { align-items: flex-end; }
.dz-items-stretch { align-items: stretch; }

.dz-justify-start { justify-content: flex-start; }
.dz-justify-center { justify-content: center; }
.dz-justify-end { justify-content: flex-end; }
.dz-justify-between { justify-content: space-between; }

/* =============================================================================
   Width & Height Utilities
   ============================================================================= */

.dz-w-full { width: 100%; }
.dz-w-auto { width: auto; }
.dz-h-full { height: 100%; }
.dz-min-h-screen { min-height: 100vh; }
.dz-max-w-sm { max-width: 24rem; }
.dz-max-w-md { max-width: 28rem; }
.dz-max-w-lg { max-width: 32rem; }
.dz-max-w-xl { max-width: 36rem; }
.dz-max-w-2xl { max-width: 42rem; }
.dz-max-w-4xl { max-width: 56rem; }
.dz-max-w-full { max-width: 100%; }

/* =============================================================================
   Border Utilities
   ============================================================================= */

.dz-border { border: 1px solid var(--dz-color-border-default); }
.dz-border-0 { border: none; }
.dz-border-t { border-top: 1px solid var(--dz-color-border-default); }
.dz-border-b { border-bottom: 1px solid var(--dz-color-border-default); }
.dz-rounded { border-radius: var(--dz-radius-default); }
.dz-rounded-md { border-radius: var(--dz-radius-md); }
.dz-rounded-lg { border-radius: var(--dz-radius-lg); }
.dz-rounded-full { border-radius: var(--dz-radius-full); }

/* =============================================================================
   Background Utilities
   ============================================================================= */

.dz-bg-default { background-color: var(--dz-color-background-default); }
.dz-bg-subtle { background-color: var(--dz-color-background-subtle); }
.dz-bg-muted { background-color: var(--dz-color-background-muted); }

/* =============================================================================
   Shadow Utilities
   ============================================================================= */

.dz-shadow-none { box-shadow: var(--dz-shadow-none); }
.dz-shadow-sm { box-shadow: var(--dz-shadow-sm); }
.dz-shadow { box-shadow: var(--dz-shadow-default); }
.dz-shadow-md { box-shadow: var(--dz-shadow-md); }
.dz-shadow-lg { box-shadow: var(--dz-shadow-lg); }

/* =============================================================================
   Overflow Utilities
   ============================================================================= */

.dz-overflow-auto { overflow: auto; }
.dz-overflow-hidden { overflow: hidden; }
.dz-overflow-x-auto { overflow-x: auto; }
.dz-overflow-y-auto { overflow-y: auto; }

/* =============================================================================
   Position Utilities
   ============================================================================= */

.dz-relative { position: relative; }
.dz-absolute { position: absolute; }
.dz-fixed { position: fixed; }
.dz-sticky { position: sticky; top: 0; }

/* =============================================================================
   Cursor Utilities
   ============================================================================= */

.dz-cursor-pointer { cursor: pointer; }
.dz-cursor-not-allowed { cursor: not-allowed; }

/* =============================================================================
   Visibility Utilities
   ============================================================================= */

.dz-opacity-0 { opacity: 0; }
.dz-opacity-50 { opacity: 0.5; }
.dz-opacity-100 { opacity: 1; }

/* =============================================================================
   Screen Reader Utilities
   ============================================================================= */

.dz-sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}
"""


# =============================================================================
# CSS Bundle Generation
# =============================================================================


def generate_css_bundle(tokens: dict[str, Any] | None = None) -> str:
    """
    Generate the complete DDT CSS bundle.

    Args:
        tokens: Token dictionary. Loads default if None.

    Returns:
        Complete CSS string combining variables, components, and utilities
    """
    if tokens is None:
        tokens = load_tokens()

    parts = [
        compile_tokens_to_variables(tokens),
        generate_dark_theme(tokens),
        generate_component_styles(),
        generate_utility_styles(),
    ]

    return "\n".join(parts)


def write_css_bundle(
    output_dir: Path,
    tokens: dict[str, Any] | None = None,
    split: bool = False,
) -> list[Path]:
    """
    Write CSS files to output directory.

    Args:
        output_dir: Directory to write CSS files
        tokens: Token dictionary. Loads default if None.
        split: If True, write separate files. If False, write single bundle.

    Returns:
        List of written file paths
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    if tokens is None:
        tokens = load_tokens()

    written: list[Path] = []

    if split:
        # Write separate files
        variables_path = output_dir / "variables.css"
        variables_path.write_text(compile_tokens_to_variables(tokens) + generate_dark_theme(tokens))
        written.append(variables_path)

        components_path = output_dir / "components.css"
        components_path.write_text(generate_component_styles())
        written.append(components_path)

        utilities_path = output_dir / "utilities.css"
        utilities_path.write_text(generate_utility_styles())
        written.append(utilities_path)
    else:
        # Write single bundle
        bundle_path = output_dir / "ddt.css"
        bundle_path.write_text(generate_css_bundle(tokens))
        written.append(bundle_path)

    return written


# =============================================================================
# CLI Entry Point
# =============================================================================


def main() -> None:
    """CLI entry point for token compilation."""
    import argparse

    parser = argparse.ArgumentParser(description="Compile DDT design tokens to CSS")
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=Path(__file__).parent.parent / "runtime" / "static" / "css",
        help="Output directory for CSS files",
    )
    parser.add_argument(
        "--split",
        action="store_true",
        help="Write separate files instead of single bundle",
    )
    parser.add_argument(
        "--tokens",
        "-t",
        type=Path,
        help="Path to custom tokens.json file",
    )

    args = parser.parse_args()

    tokens = load_tokens(args.tokens) if args.tokens else None
    written = write_css_bundle(args.output, tokens, args.split)

    for path in written:
        print(f"Written: {path}")


if __name__ == "__main__":
    main()
