#!/usr/bin/env python3
"""
Generate promotional markdown showcasing a Dazzle example project.

Creates a markdown file with embedded screenshots demonstrating the
generated UI from DSL definitions.

Usage:
    python generate_showcase_md.py \
        --example simple_task \
        --screenshots ./screenshots/simple_task \
        --coverage ./coverage/simple_task.json \
        --output ./coverage/simple_task.md
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path


def find_screenshots(screenshot_dir: Path) -> dict[str, Path]:
    """Find and categorize screenshots by type."""
    screenshots = {}

    if not screenshot_dir.exists():
        return screenshots

    # Map screenshot filenames to semantic categories
    categories = {
        "list": ["list", "index", "home", "dashboard"],
        "detail": ["detail", "view", "show"],
        "create": ["create", "new", "add"],
        "edit": ["edit", "update", "modify"],
        "form": ["form", "input"],
        "error": ["error", "fail"],
        "empty": ["empty", "no_data"],
    }

    for img_file in screenshot_dir.glob("*.png"):
        name = img_file.stem.lower()
        categorized = False

        for category, keywords in categories.items():
            if any(kw in name for kw in keywords):
                if category not in screenshots:
                    screenshots[category] = img_file
                categorized = True
                break

        if not categorized:
            # Use numbered screenshots as generic views
            screenshots[name] = img_file

    return screenshots


def load_coverage_report(coverage_path: Path) -> dict | None:
    """Load UX coverage JSON report."""
    if not coverage_path.exists():
        return None

    try:
        with open(coverage_path) as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return None


def get_dsl_snippet(example_name: str, project_root: Path) -> str | None:
    """Extract a representative DSL snippet from the example."""
    example_path = project_root / "examples" / example_name / "dsl"

    if not example_path.exists():
        return None

    # Look for main DSL files
    dsl_files = list(example_path.glob("*.dsl"))
    if not dsl_files:
        return None

    # Read the first DSL file
    try:
        with open(dsl_files[0]) as f:
            content = f.read()

        # Extract first entity and surface definitions
        lines = content.split("\n")
        snippet_lines = []
        in_block = False
        block_count = 0

        for line in lines:
            # Include module and app declarations
            if line.startswith("module ") or line.startswith("app "):
                snippet_lines.append(line)
                continue

            # Include entity and surface blocks (first of each)
            if line.startswith("entity ") or line.startswith("surface "):
                in_block = True
                block_count += 1

            if in_block:
                snippet_lines.append(line)
                if line.strip() == "" and len(snippet_lines) > 5:
                    in_block = False
                    if block_count >= 2:
                        break

        return "\n".join(snippet_lines[:40])  # Limit to 40 lines
    except OSError:
        return None


def generate_markdown(
    example_name: str,
    screenshots: dict[str, Path],
    coverage: dict | None,
    project_root: Path,
    output_path: Path,
) -> str:
    """Generate promotional markdown content."""

    # Header
    title = example_name.replace("_", " ").title()
    md = f"""# {title} - Generated by Dazzle

> **Automatically generated CRUD application from DSL definition**

This showcase demonstrates how Dazzle transforms a simple DSL specification into
a fully functional, professionally-styled web application.

---

## Overview

| Metric | Value |
|--------|-------|
| **Example** | `{example_name}` |
| **Generated** | {datetime.now().strftime("%Y-%m-%d %H:%M")} |
"""

    # Add coverage metrics if available
    if coverage:
        overall = coverage.get("overall_coverage", 0)
        md += f"| **UX Coverage** | {overall:.1f}% |\n"

        if "entity_coverage" in coverage:
            entities = coverage["entity_coverage"]
            entity_names = list(entities.keys()) if isinstance(entities, dict) else []
            md += f"| **Entities** | {', '.join(entity_names) or 'N/A'} |\n"

    md += "\n---\n\n"

    # DSL Definition section
    dsl_snippet = get_dsl_snippet(example_name, project_root)
    if dsl_snippet:
        md += """## DSL Definition

The entire application is defined using Dazzle's declarative DSL:

```dsl
"""
        md += dsl_snippet
        md += """
```

From this simple definition, Dazzle generates a complete application with:
- RESTful API endpoints
- Interactive web UI
- Data persistence
- Form validation

---

"""

    # Screenshots section
    md += "## Generated UI\n\n"

    screenshot_descriptions = {
        "list": ("List View", "The main list view showing all items with sorting and filtering."),
        "detail": ("Detail View", "Individual item detail view with all fields displayed."),
        "create": ("Create Form", "Form for creating new items with validation."),
        "edit": ("Edit Form", "Form for editing existing items with pre-populated values."),
        "form": ("Form Interface", "The form interface for data entry."),
        "empty": ("Empty State", "The UI gracefully handles empty data states."),
    }

    if screenshots:
        for key, img_path in screenshots.items():
            # Get relative path for markdown
            rel_path = f"../screenshots/{example_name}/{img_path.name}"

            if key in screenshot_descriptions:
                title, desc = screenshot_descriptions[key]
            else:
                title = key.replace("_", " ").title()
                desc = f"Screenshot: {title}"

            md += f"### {title}\n\n"
            md += f"{desc}\n\n"
            md += f"![{title}]({rel_path})\n\n"
    else:
        md += "*No screenshots available for this example.*\n\n"

    md += "---\n\n"

    # Coverage details
    if coverage:
        md += "## UX Coverage Report\n\n"

        overall = coverage.get("overall_coverage", 0)

        # Coverage badge
        if overall >= 90:
            badge_color = "brightgreen"
        elif overall >= 70:
            badge_color = "yellow"
        else:
            badge_color = "red"

        md += f"![Coverage](https://img.shields.io/badge/UX%20Coverage-{overall:.0f}%25-{badge_color})\n\n"

        # Breakdown table
        md += "| Category | Coverage |\n"
        md += "|----------|----------|\n"

        if "route_coverage" in coverage:
            route_cov = coverage["route_coverage"]
            if isinstance(route_cov, dict):
                visited = route_cov.get("visited", 0)
                total = route_cov.get("total", 1)
                pct = (visited / total * 100) if total > 0 else 0
                md += f"| Routes | {pct:.0f}% ({visited}/{total}) |\n"

        if "component_coverage" in coverage:
            comp_cov = coverage["component_coverage"]
            if isinstance(comp_cov, dict):
                tested = sum(
                    1 for c in comp_cov.values() if isinstance(c, dict) and c.get("tested", False)
                )
                total = len(comp_cov)
                pct = (tested / total * 100) if total > 0 else 0
                md += f"| Components | {pct:.0f}% ({tested}/{total}) |\n"

        if "entity_coverage" in coverage:
            entity_cov = coverage["entity_coverage"]
            if isinstance(entity_cov, dict):
                for entity_name, entity_data in entity_cov.items():
                    if isinstance(entity_data, dict):
                        crud = entity_data.get("crud_operations", {})
                        if isinstance(crud, dict):
                            ops_tested = sum(1 for v in crud.values() if v)
                            md += f"| {entity_name} CRUD | {ops_tested}/4 operations |\n"

        md += "\n"

    # Footer
    md += (
        """---

## Try It Yourself

```bash
# Clone the Dazzle repository
git clone https://github.com/your-org/dazzle.git
cd dazzle

# Run this example
cd examples/"""
        + example_name
        + """
dazzle serve

# Open in browser
# UI: http://localhost:3000
# API: http://localhost:8000/docs
```

---

*Generated by [Dazzle](https://github.com/your-org/dazzle) - DSL-first application development*
"""
    )

    return md


def main():
    parser = argparse.ArgumentParser(
        description="Generate promotional markdown for Dazzle examples"
    )
    parser.add_argument("--example", required=True, help="Name of the example project")
    parser.add_argument("--screenshots", required=True, help="Directory containing screenshots")
    parser.add_argument("--coverage", required=True, help="Path to UX coverage JSON report")
    parser.add_argument("--output", required=True, help="Output markdown file path")
    parser.add_argument(
        "--project-root", default=None, help="Project root directory (default: auto-detect)"
    )

    args = parser.parse_args()

    # Resolve paths
    screenshot_dir = Path(args.screenshots)
    coverage_path = Path(args.coverage)
    output_path = Path(args.output)

    # Auto-detect project root
    if args.project_root:
        project_root = Path(args.project_root)
    else:
        # Navigate up from script location
        script_dir = Path(__file__).parent
        project_root = script_dir.parent.parent.parent

    # Find screenshots
    screenshots = find_screenshots(screenshot_dir)
    print(f"Found {len(screenshots)} screenshots")

    # Load coverage report
    coverage = load_coverage_report(coverage_path)
    if coverage:
        print(f"Loaded coverage report: {coverage.get('overall_coverage', 0):.1f}%")
    else:
        print("No coverage report found")

    # Generate markdown
    markdown = generate_markdown(
        example_name=args.example,
        screenshots=screenshots,
        coverage=coverage,
        project_root=project_root,
        output_path=output_path,
    )

    # Write output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write(markdown)

    print(f"Generated: {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
