#!/bin/bash
# Run UX Coverage tests for a Dazzle example project
#
# Usage:
#   ./run_ux_coverage.sh <example_name> [--coverage-threshold 90]
#
# Outputs:
#   - screenshots/<example>/      Screenshots of UI states
#   - coverage/<example>.json     UX coverage report
#   - coverage/<example>.md       Promotional markdown with embedded screenshots
#
# Exit codes:
#   0 - Success, coverage meets threshold
#   1 - Coverage below threshold
#   2 - Infrastructure/test failure

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# Parse arguments
EXAMPLE_NAME="${1:-simple_task}"
COVERAGE_THRESHOLD=90

shift || true
while [[ $# -gt 0 ]]; do
    case $1 in
        --coverage-threshold)
            COVERAGE_THRESHOLD="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            exit 2
            ;;
    esac
done

# Validate example exists
EXAMPLE_PATH="$PROJECT_ROOT/examples/$EXAMPLE_NAME"
if [[ ! -d "$EXAMPLE_PATH" ]]; then
    echo "Error: Example '$EXAMPLE_NAME' not found at $EXAMPLE_PATH"
    exit 2
fi

echo "========================================"
echo "UX Coverage Test: $EXAMPLE_NAME"
echo "Threshold: ${COVERAGE_THRESHOLD}%"
echo "========================================"

# Create output directories
SCREENSHOT_DIR="$SCRIPT_DIR/screenshots/$EXAMPLE_NAME"
COVERAGE_DIR="$SCRIPT_DIR/coverage"
mkdir -p "$SCREENSHOT_DIR" "$COVERAGE_DIR"

# Generate dynamic docker-compose for this example
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.$EXAMPLE_NAME.yaml"
cat > "$COMPOSE_FILE" <<EOF
# Auto-generated Docker Compose for E2E testing: $EXAMPLE_NAME
# Generated by run_ux_coverage.sh

services:
  dnr-app:
    build:
      context: $PROJECT_ROOT
      dockerfile: tests/e2e/docker/Dockerfile.dnr
      args:
        PROJECT_PATH: examples/$EXAMPLE_NAME
    container_name: dazzle-e2e-$EXAMPLE_NAME
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      - DNR_TEST_MODE=1
      - DNR_HOST=0.0.0.0
      - DNR_API_PORT=8000
      - DNR_FRONTEND_PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - e2e-network

  playwright:
    image: mcr.microsoft.com/playwright/python:v1.55.0-noble
    container_name: dazzle-e2e-playwright-$EXAMPLE_NAME
    depends_on:
      dnr-app:
        condition: service_healthy
    environment:
      - DNR_BASE_URL=http://dnr-app:8000
      - DNR_UI_URL=http://dnr-app:3000
      - SCREENSHOT_DIR=/screenshots
      - EXAMPLE_NAME=$EXAMPLE_NAME
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    volumes:
      - $PROJECT_ROOT/tests:/tests:ro
      - $PROJECT_ROOT/src:/src:ro
      - $SCREENSHOT_DIR:/screenshots
    working_dir: /tests/e2e/docker
    networks:
      - e2e-network

networks:
  e2e-network:
    driver: bridge
EOF

# Cleanup function
cleanup() {
    echo "Cleaning up Docker containers..."
    docker compose -f "$COMPOSE_FILE" down --volumes --remove-orphans 2>/dev/null || true
    rm -f "$COMPOSE_FILE" 2>/dev/null || true
}
trap cleanup EXIT

# Build and start containers
echo "Building Docker images..."
docker compose -f "$COMPOSE_FILE" build --quiet

echo "Starting containers..."
docker compose -f "$COMPOSE_FILE" up -d

# Wait for health check
echo "Waiting for DNR app to be healthy..."
for i in {1..60}; do
    if docker compose -f "$COMPOSE_FILE" ps | grep -q "healthy"; then
        echo "DNR app is healthy!"
        break
    fi
    if [[ $i -eq 60 ]]; then
        echo "Timeout waiting for DNR app"
        docker compose -f "$COMPOSE_FILE" logs dnr-app
        exit 2
    fi
    sleep 1
done

# Run tests
echo "Running UX validation tests..."
TEST_EXIT_CODE=0

# Install dependencies and run tests
# Pin playwright version to match the Docker image version (1.55.0)
docker compose -f "$COMPOSE_FILE" run --rm playwright \
    bash -c "pip install httpx pytest-playwright 'playwright==1.55.0' --quiet && \
             python -m pytest test_ux_validation.py -v --tb=short" \
    || TEST_EXIT_CODE=$?

# Copy coverage report
if [[ -f "$SCREENSHOT_DIR/ux_coverage.json" ]]; then
    cp "$SCREENSHOT_DIR/ux_coverage.json" "$COVERAGE_DIR/$EXAMPLE_NAME.json"
    echo "Coverage report saved to: $COVERAGE_DIR/$EXAMPLE_NAME.json"
else
    echo "Warning: No coverage report generated"
fi

# Check coverage threshold
if [[ -f "$COVERAGE_DIR/$EXAMPLE_NAME.json" ]]; then
    OVERALL_COVERAGE=$(python3 -c "
import json
with open('$COVERAGE_DIR/$EXAMPLE_NAME.json') as f:
    data = json.load(f)
    print(data.get('overall_coverage', 0))
")

    echo "Overall UX Coverage: ${OVERALL_COVERAGE}%"

    # Compare with threshold
    PASSES=$(python3 -c "print('yes' if $OVERALL_COVERAGE >= $COVERAGE_THRESHOLD else 'no')")

    if [[ "$PASSES" == "no" ]]; then
        echo "FAIL: Coverage ${OVERALL_COVERAGE}% is below threshold ${COVERAGE_THRESHOLD}%"
        exit 1
    fi

    echo "PASS: Coverage ${OVERALL_COVERAGE}% meets threshold ${COVERAGE_THRESHOLD}%"
fi

# Generate promotional markdown
echo "Generating promotional markdown..."
python3 "$SCRIPT_DIR/generate_showcase_md.py" \
    --example "$EXAMPLE_NAME" \
    --screenshots "$SCREENSHOT_DIR" \
    --coverage "$COVERAGE_DIR/$EXAMPLE_NAME.json" \
    --output "$COVERAGE_DIR/$EXAMPLE_NAME.md" \
    || echo "Warning: Could not generate markdown"

echo "========================================"
echo "UX Coverage Test Complete: $EXAMPLE_NAME"
echo "========================================"

exit $TEST_EXIT_CODE
