"""
Deployment generator for Django Micro backend.

Generates deployment configuration files.
"""

from pathlib import Path

from ...base import Generator, GeneratorResult


class DeploymentGenerator(Generator):
    """
    Generate deployment configuration files.

    Creates:
    - requirements.txt - Python dependencies
    - Procfile - Heroku/Railway deployment
    - runtime.txt - Python version
    - README.md - Project documentation
    - .gitignore - Git ignore patterns
    """

    def __init__(self, spec, output_dir: Path, project_name: str):
        """
        Initialize deployment generator.

        Args:
            spec: Application specification
            output_dir: Root output directory
            project_name: Name of the Django project
        """
        super().__init__(spec, output_dir)
        self.project_name = project_name

    def generate(self) -> GeneratorResult:
        """Generate deployment files."""
        result = GeneratorResult()

        # Generate requirements.txt
        requirements = self._generate_requirements()
        req_path = self.output_dir / "requirements.txt"
        self._write_file(req_path, requirements)
        result.add_file(req_path)

        # Generate Procfile
        procfile = self._generate_procfile()
        proc_path = self.output_dir / "Procfile"
        self._write_file(proc_path, procfile)
        result.add_file(proc_path)

        # Generate runtime.txt
        runtime = self._generate_runtime()
        runtime_path = self.output_dir / "runtime.txt"
        self._write_file(runtime_path, runtime)
        result.add_file(runtime_path)

        # Generate README.md
        readme = self._generate_readme()
        readme_path = self.output_dir / "README.md"
        self._write_file(readme_path, readme)
        result.add_file(readme_path)

        # Generate .gitignore
        gitignore = self._generate_gitignore()
        gitignore_path = self.output_dir / ".gitignore"
        self._write_file(gitignore_path, gitignore)
        result.add_file(gitignore_path)

        return result

    def _generate_requirements(self) -> str:
        """Generate requirements.txt."""
        return '''# Django Micro Application Requirements
# Generated by DAZZLE

Django>=4.2,<5.0
gunicorn>=21.0.0
'''

    def _generate_procfile(self) -> str:
        """Generate Procfile for Heroku/Railway."""
        return f'''web: gunicorn {self.project_name}.wsgi --log-file -
'''

    def _generate_runtime(self) -> str:
        """Generate runtime.txt for Python version."""
        return 'python-3.11.6\n'

    def _generate_readme(self) -> str:
        """Generate README.md."""
        app_name = self.spec.name or self.project_name

        return f'''# {app_name}

Generated by [DAZZLE](https://github.com/dazzle-framework/dazzle) - A declarative application specification language.

## Quick Start

### 1. Install Dependencies

```bash
pip install -r requirements.txt
```

### 2. Run Migrations

```bash
python manage.py migrate
```

### 3. Create Admin User

See `.admin_credentials` file for default credentials, or create your own:

```bash
python manage.py createsuperuser
```

### 4. Run Development Server

```bash
python manage.py runserver
```

Visit:
- http://localhost:8000/ - Application home
- http://localhost:8000/admin/ - Admin interface

## Deployment

### Heroku

```bash
# Login to Heroku
heroku login

# Create app
heroku create your-app-name

# Deploy
git push heroku main

# Run migrations
heroku run python manage.py migrate

# Create admin user
heroku run python manage.py createsuperuser
```

### Railway

1. Connect your Git repository to Railway
2. Railway will auto-detect Django and deploy
3. Run migrations via Railway CLI:
   ```bash
   railway run python manage.py migrate
   ```

### PythonAnywhere

1. Upload code via Git or Files
2. Create virtual environment
3. Configure WSGI file to point to `{self.project_name}.wsgi`
4. Run migrations in console
5. Collect static files: `python manage.py collectstatic`

## Project Structure

```
{self.project_name}/
├── {self.project_name}/       # Django project
│   ├── settings.py
│   ├── urls.py
│   ├── wsgi.py
│   └── asgi.py
├── app/                  # Django application
│   ├── models.py
│   ├── views.py
│   ├── forms.py
│   ├── urls.py
│   ├── admin.py
│   ├── templates/
│   └── static/
├── manage.py
├── requirements.txt
├── Procfile
└── README.md
```

## Features

- ✅ Full CRUD operations
- ✅ Django Admin interface
- ✅ Responsive design
- ✅ Form validation
- ✅ SQLite database
- ✅ Production-ready deployment configs

## Development

### Run Tests

```bash
python manage.py test
```

### Create Migrations

```bash
python manage.py makemigrations
python manage.py migrate
```

### Collect Static Files

```bash
python manage.py collectstatic
```

## Security Notes

⚠️ **Before deploying to production:**

1. Change `SECRET_KEY` in `settings.py`
2. Set `DEBUG = False` in `settings.py`
3. Update `ALLOWED_HOSTS` in `settings.py`
4. Change admin credentials from `.admin_credentials`
5. Use environment variables for sensitive data
6. Set up proper database (PostgreSQL recommended)

## License

Generated code is yours to use as you see fit.

## Support

For DAZZLE-related issues, visit: https://github.com/dazzle-framework/dazzle
'''

    def _generate_gitignore(self) -> str:
        """Generate .gitignore."""
        return '''# DAZZLE Generated .gitignore

# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# Django
*.log
local_settings.py
db.sqlite3
db.sqlite3-journal
/staticfiles/
/media/

# Virtual Environment
venv/
ENV/
env/
.venv

# IDE
.vscode/
.idea/
*.swp
*.swo
*~
.DS_Store

# Secrets
.env
.env.local
*.key
*.pem
.admin_credentials

# Testing
.coverage
htmlcov/
.pytest_cache/
.tox/

# Deployment
*.pid
*.seed
*.pid.lock
'''
