"""Add membership_events table (auth Plan 2a — lifecycle compliance evidence).

Append-only, hash-chained record of membership JML changes (provision /
role-change / suspend / reactivate / remove). Written in the same transaction as
the mutation by the auth store (durable; must-not-drop). Idempotent: guards on
table presence so the dev `_init_db` create path and this migration are
interchangeable (mirrors 0007/0008). No DB FK from membership_id/identity_id (the
auth tables are not in the Alembic-managed DSL metadata; joins enforced in store).
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect as sa_inspect

revision = "0009_membership_events"
down_revision = "0008_organizations"
branch_labels = None
depends_on = None


def _has_table(table: str) -> bool:
    return sa_inspect(op.get_bind()).has_table(table)


def upgrade() -> None:
    if not _has_table("membership_events"):
        op.create_table(
            "membership_events",
            # GENERATED BY DEFAULT AS IDENTITY — byte-identical to the _init_db dev
            # DDL (`seq BIGINT GENERATED BY DEFAULT AS IDENTITY`), so dev and prod
            # schemas match. always=False permits (unused) explicit seq inserts;
            # the writer always omits seq, so the DB assigns it monotonically.
            sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), unique=True),
            sa.Column("id", sa.Text(), primary_key=True),
            sa.Column("event_type", sa.Text(), nullable=False),
            sa.Column("membership_id", sa.Text(), nullable=False),
            sa.Column("tenant_id", sa.Text(), nullable=False),
            sa.Column("identity_id", sa.Text(), nullable=False),
            sa.Column("actor_id", sa.Text(), nullable=True),
            sa.Column("roles_before", sa.Text(), nullable=True),
            sa.Column("roles_after", sa.Text(), nullable=True),
            sa.Column("status_before", sa.Text(), nullable=True),
            sa.Column("status_after", sa.Text(), nullable=True),
            sa.Column("reason", sa.Text(), nullable=True),
            sa.Column("created_at", sa.Text(), nullable=False),
            sa.Column("row_hash", sa.Text(), nullable=False),
        )
        op.create_index("ix_membership_events_tenant", "membership_events", ["tenant_id", "seq"])
        op.create_index(
            "ix_membership_events_identity", "membership_events", ["identity_id", "seq"]
        )
        op.create_index(
            "ix_membership_events_membership", "membership_events", ["membership_id", "seq"]
        )


def downgrade() -> None:
    if _has_table("membership_events"):
        op.drop_table("membership_events")
