"""Render compliance markdown documents to branded PDF via WeasyPrint.

WeasyPrint and markdown are optional dependencies — this module
gracefully handles their absence with a clear error message.

Post-#1050 (v0.67.86+): the HTML wrapper template uses stdlib
`string.Template` (variable substitution only — no logic in the
template) instead of Jinja2.
"""

from datetime import date
from pathlib import Path
from string import Template
from typing import Any

import yaml

from dazzle.i18n.display_locale import calendar_today, get_display_locale

try:
    import markdown  # type: ignore[import-untyped,unused-ignore]
    import weasyprint

    HAS_RENDERER_DEPS = True
except ImportError:
    HAS_RENDERER_DEPS = False


PACKAGE_DIR = Path(__file__).parent
CSS_PATH = PACKAGE_DIR / "css" / "compliance.css"
TEMPLATE_PATH = PACKAGE_DIR / "templates" / "document.html"


def _compliance_doc_date() -> str:
    """Document control date from DisplayLocaleProfile (#1597 D).

    Long form (e.g. ``16 July 2026``) matches UK letter/PDF conventions;
    falls back to ISO when i18n is unavailable.
    """
    try:
        return get_display_locale().format_long_date(calendar_today())
    except Exception:
        return date.today().isoformat()


# Minimal brandspec for projects without one
DEFAULT_BRANDSPEC: dict[str, Any] = {
    "brand": {
        "identity": {"name": "Untitled Project", "legal_name": "Untitled Project"},
        "colours": {
            "primary": "#1a365d",
            "secondary": "#2b6cb0",
            "accent": "#38a169",
            "text": "#1a202c",
            "muted": "#718096",
        },
        "compliance": {
            "document_control": {
                "author": "Generated by Dazzle Compliance Pipeline",
                "classification": "Confidential",
            }
        },
    }
}


def load_brandspec(path: Path | None = None, project_path: Path | None = None) -> dict[str, Any]:
    """Load brandspec.yaml from explicit path or project root.

    Falls back to DEFAULT_BRANDSPEC if not found.
    """
    if path and path.exists():
        result: dict[str, Any] = yaml.safe_load(path.read_text(encoding="utf-8"))
        return result

    if project_path:
        candidate = project_path / ".dazzle" / "compliance" / "brandspec.yaml"
        if candidate.exists():
            result = yaml.safe_load(candidate.read_text(encoding="utf-8"))
            return result

    return DEFAULT_BRANDSPEC


def render_document(
    markdown_path: Path,
    output_path: Path,
    brandspec: dict[str, Any],
    document_title: str,
    document_id: str,
    version: str = "1.0",
    reviewer: str = "",
    approver: str = "",
) -> Path:
    """Render a markdown document to a branded PDF.

    Requires weasyprint and markdown packages.
    Install with: pip install weasyprint markdown
    """
    if not HAS_RENDERER_DEPS:
        raise RuntimeError(
            "PDF rendering requires optional dependencies. "
            "Install with: pip install weasyprint markdown"
        )

    brand = brandspec["brand"]
    identity = brand["identity"]
    colours = brand["colours"]
    compliance = brand.get("compliance", {})
    doc_control = compliance.get("document_control", {})

    md_text = markdown_path.read_text(encoding="utf-8")
    content_html = markdown.markdown(
        md_text,
        extensions=["tables", "toc", "fenced_code"],
    )

    if not TEMPLATE_PATH.exists():
        raise FileNotFoundError(f"Template not found: {TEMPLATE_PATH}")
    if not CSS_PATH.exists():
        raise FileNotFoundError(f"CSS not found: {CSS_PATH}")

    template = Template(TEMPLATE_PATH.read_text(encoding="utf-8"))
    html_str = template.substitute(
        content=content_html,
        document_title=document_title,
        document_id=document_id,
        version=version,
        date=_compliance_doc_date(),
        organisation_name=identity["name"],
        legal_name=identity.get("legal_name", identity["name"]),
        classification=doc_control.get("classification", "Confidential"),
        author=doc_control.get("author", "Compliance Pipeline"),
        reviewer=reviewer or doc_control.get("reviewer", ""),
        approver=approver or doc_control.get("approver", ""),
        colour_primary=colours["primary"],
        colour_secondary=colours["secondary"],
        colour_accent=colours["accent"],
        css_path=str(CSS_PATH),
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    weasyprint.HTML(string=html_str, base_url=str(PACKAGE_DIR)).write_pdf(str(output_path))

    return output_path
