"""Tests for dazzle build --target codegen pipeline (#284)."""

from __future__ import annotations

from pathlib import Path

import pytest

import dazzle.core.ir as ir


def _minimal_appspec() -> ir.AppSpec:
    """Create a minimal AppSpec for testing build targets."""
    entity = ir.EntitySpec(
        name="Task",
        title="Task",
        fields=[
            ir.FieldSpec(
                name="id",
                type=ir.FieldType(kind=ir.FieldTypeKind.UUID),
                modifiers=[ir.FieldModifier.PK],
            ),
            ir.FieldSpec(
                name="title",
                type=ir.FieldType(kind=ir.FieldTypeKind.STR),
                modifiers=[ir.FieldModifier.REQUIRED],
            ),
            ir.FieldSpec(
                name="completed",
                type=ir.FieldType(kind=ir.FieldTypeKind.BOOL),
            ),
        ],
    )
    domain = ir.DomainSpec(entities=[entity])
    surface = ir.SurfaceSpec(
        name="task_list",
        title="Tasks",
        entity_ref="Task",
        mode=ir.SurfaceMode.LIST,
    )
    return ir.AppSpec(
        name="test_app",
        title="Test App",
        version="1.0.0",
        domain=domain,
        surfaces=[surface],
    )


# ── SQL target ──────────────────────────────────────────────────────


class TestSQLTarget:
    """_generate_sql_target produces valid SQL DDL."""

    @pytest.fixture(autouse=True)
    def _skip_if_no_backend(self) -> None:
        pytest.importorskip("dazzle_back")

    def test_sql_file_created(self, tmp_path: Path) -> None:
        from dazzle.cli.runtime_impl.build import _generate_sql_target

        appspec = _minimal_appspec()
        _generate_sql_target(appspec, tmp_path)

        sql_file = tmp_path / "schema.sql"
        assert sql_file.exists()

    def test_sql_contains_create_table(self, tmp_path: Path) -> None:
        from dazzle.cli.runtime_impl.build import _generate_sql_target

        appspec = _minimal_appspec()
        _generate_sql_target(appspec, tmp_path)

        content = (tmp_path / "schema.sql").read_text()
        assert 'CREATE TABLE IF NOT EXISTS "Task"' in content

    def test_sql_contains_columns(self, tmp_path: Path) -> None:
        from dazzle.cli.runtime_impl.build import _generate_sql_target

        appspec = _minimal_appspec()
        _generate_sql_target(appspec, tmp_path)

        content = (tmp_path / "schema.sql").read_text()
        assert '"id"' in content
        assert '"title"' in content
        assert '"completed"' in content

    def test_sql_header_comment(self, tmp_path: Path) -> None:
        from dazzle.cli.runtime_impl.build import _generate_sql_target

        appspec = _minimal_appspec()
        _generate_sql_target(appspec, tmp_path)

        content = (tmp_path / "schema.sql").read_text()
        assert "-- SQL schema for test_app" in content
        assert "-- Generated by dazzle build" in content


# ── OpenAPI target ──────────────────────────────────────────────────


class TestOpenAPITarget:
    """_generate_openapi_target produces OpenAPI spec files."""

    def test_openapi_files_created(self, tmp_path: Path) -> None:
        from dazzle.cli.runtime_impl.build import _generate_openapi_target

        appspec = _minimal_appspec()
        _generate_openapi_target(appspec, tmp_path)

        assert (tmp_path / "openapi.yaml").exists()
        assert (tmp_path / "openapi.json").exists()

    def test_openapi_yaml_valid(self, tmp_path: Path) -> None:
        import json

        from dazzle.cli.runtime_impl.build import _generate_openapi_target

        appspec = _minimal_appspec()
        _generate_openapi_target(appspec, tmp_path)

        json_content = json.loads((tmp_path / "openapi.json").read_text())
        assert json_content.get("openapi", "").startswith("3.")
        assert "paths" in json_content


# ── AsyncAPI target ─────────────────────────────────────────────────


class TestAsyncAPITarget:
    """_generate_asyncapi_target produces AsyncAPI spec files."""

    def test_asyncapi_files_created(self, tmp_path: Path) -> None:
        from dazzle.cli.runtime_impl.build import _generate_asyncapi_target

        appspec = _minimal_appspec()
        _generate_asyncapi_target(appspec, tmp_path)

        assert (tmp_path / "asyncapi.yaml").exists()
        assert (tmp_path / "asyncapi.json").exists()


# ── Target dispatch ─────────────────────────────────────────────────


class TestRunCodegenTargets:
    """_run_codegen_targets dispatches to correct targets."""

    @pytest.fixture(autouse=True)
    def _skip_if_no_backend(self) -> None:
        pytest.importorskip("dazzle_back")

    def test_all_target_generates_all_files(self, tmp_path: Path) -> None:
        from dazzle.cli.runtime_impl.build import _run_codegen_targets

        appspec = _minimal_appspec()
        _run_codegen_targets(appspec, tmp_path, "all")

        assert (tmp_path / "schema.sql").exists()
        assert (tmp_path / "openapi.yaml").exists()
        assert (tmp_path / "openapi.json").exists()
        assert (tmp_path / "asyncapi.yaml").exists()
        assert (tmp_path / "asyncapi.json").exists()

    def test_sql_target_only(self, tmp_path: Path) -> None:
        from dazzle.cli.runtime_impl.build import _run_codegen_targets

        appspec = _minimal_appspec()
        _run_codegen_targets(appspec, tmp_path, "sql")

        assert (tmp_path / "schema.sql").exists()
        assert not (tmp_path / "openapi.yaml").exists()

    def test_openapi_target_only(self, tmp_path: Path) -> None:
        from dazzle.cli.runtime_impl.build import _run_codegen_targets

        appspec = _minimal_appspec()
        _run_codegen_targets(appspec, tmp_path, "openapi")

        assert (tmp_path / "openapi.yaml").exists()
        assert not (tmp_path / "schema.sql").exists()
